### ISSUE TITLE
__interfaces is defined twice with inheritance

### ISSUE THREAD

**Issue by lgrignon** [cincheo/jsweet#104]
class A implements X {}

class B extends A {}

generates in TS two constructors:
for A:
public constructor() {
            Object.defineProperty(this, '__interfaces', { value: ["X"] });
         }
for B 
constructor() {
            Object.defineProperty(this, '__interfaces', { value: ["X"] });
        }

2 problems: (i) call to super() is not printed ==> compilation error (ii) if super() explicitely written in jsweet; property __interfaces is defined twice ==> error at runtime

**Comment by renaudpawlak** [comment]
Thanks Louis, it is fixed. Sorry for the inconvenience :)
Handling ``instanceof``` for interfaces requires some runtime operations that might imply some side effects. It is getting better though. I have added some tests and will add more later.
