### ISSUE TITLE
ERROR: cannot find name 'long' with java long field.

### ISSUE THREAD

**Issue by uuidcode** [cincheo/jsweet#106]
run mvn jsweet:jsweet below java code.
ERROR: cannot find name 'long' is occured.
```
public class Project {
    private Long projectId;
    private String name;

    public String getName() {
        return this.name;
    }

    public Project setName(String name) {
        this.name = name;
        return this;
    }
    public Long getProjectId() {
        return this.projectId;
    }

    public Project setProjectId(Long projectId) {
        this.projectId = projectId;
        return this;
    }
}

```

**Comment by renaudpawlak** [comment]
Ouch. It looks like you have found the forgotten type. I have just committed mapping for Java longs to TypeScript numbers. For some reason, it was ok for all number types, except for longs. It should work with the latest snapshot now. Thanks for reporting this.

**Comment by uuidcode** [comment]
I checked it. OK! thanks.
