### ISSUE TITLE
TypeScript upgrade

### ISSUE THREAD

**Issue by lgrignon** [cincheo/jsweet#110]
JSweet uses a specific typescript installation (cf `private static File NPM_DIR = new File(USER_HOME_DIR, ".jsweet-node_modules");`). Thus, the typescript installation in this npm directory is not upgraded by user when he performs the regular `npm install typescript -g`
Indeed, it would require executing: `npm install typescript --prefix ~/.jsweet-node_modules -g`

Since JSweet uses DefTyped definitions which is based on the latest TypeScript version, we should upgrade the JSweet's typescript installation in order to keep tsc in sync with its def.

That being said, some user could rely on old candies based on an older version of typescript. 
Maybe it would be better to have an option specifying the TypeScript version to use, which defaults to the latest. 
This last option seems too manual I think.

**Comment by renaudpawlak** [comment]
Now, a JSweet version is bound to a tsc version and installs the right one. It solves the tsc upgrade issue.
