### ISSUE TITLE
Thorax Candy

### ISSUE THREAD

**Issue by kiamesdavies** [cincheo/jsweet#117]
Can't find thorax candy. http://thoraxjs.org/

**Comment by lgrignon** [comment]
Hello, indeed the Thorax TS definition files weren't provided by the [community](https://github.com/DefinitelyTyped/DefinitelyTyped). I suggest you write it and do the pull request to [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped) so everyone could enjoy your definitions. 
The day after your PR will be accepted, the candy will be available!

I presume that you need the candy pretty quickly so in the mean time you could use the [online TS definition to candy online translator](http://www.jsweet.org/online-typescript-to-java-api-translator). This way you could use your candy before the PR is accepted (the Definitely Typed validator guys are not really responsive ;))

Hope you will find time for this! :)

**Comment by renaudpawlak** [comment]
JSweet provides a basis of automatically generated candies. It is now very easy to anyone to write his own candies as explained at https://github.com/jsweet-candies. We encourage JSweet users to contribute to existing candies and create new ones.
