### ISSUE TITLE
Generics translation misses comma

### ISSUE THREAD

**Issue by fedorov-s-n** [cincheo/jsweet#122]
I tried to paste the code below to QuickStart example. I've got errors

ERROR: ',' expected at quickstart/QuickStart.ts(40)
ERROR: ',' expected at quickstart/QuickStart.ts(42)
ERROR: ',' expected at quickstart/QuickStart.ts(112)

Errors correspond to lines in .ts code:
40            `operations : ((p1: Tp2: Tp1: T) => T)[];`
42            `unary : Stack<(p1: Tp1: T) => T> = new Stack<any>();`
112          `var op : (p1: Tp2: Tp1: T) => T = this.operations[level];`

I'm not an expert in ts, but it looks to me that they should be
40            `operations : ((p1: T, p2: T) => T)[];`
42            `unary : Stack<(p1: T) => T> = new Stack<any>();`
112          `var op : (p1: T, p2: T) => T = this.operations[level];`

Java lines are:

        private final BinaryOperator<T>[] operations;
        private final Stack<UnaryOperator<T>> unary = new Stack<>();
        BinaryOperator<T> op = operations[level];

Full code:

    public static class ExpressionBuilder<T> {

        private final int defaultLevel;
        private final BinaryOperator<T>[] operations;
        private final Stack<UnaryOperator<T>> unary = new Stack<>();
        private final ExpressionBuilder<T> parent;
        private final Stack<Integer> levelHistory;
        private final Deque<T>[] elements;
        private int currentLevel;
        private boolean operationDeclared;

        public ExpressionBuilder(int defaultLevel, BinaryOperator<T>... precedence) {
            this(null, defaultLevel, precedence);
        }

        private ExpressionBuilder(ExpressionBuilder<T> parent, int defaultLevel, BinaryOperator<T>... precedence) {
            this.operations = precedence;
            this.parent = parent;
            this.defaultLevel = defaultLevel;
            this.levelHistory = new Stack<>();
            this.currentLevel = 0;
            this.operationDeclared = true;
            this.elements = new LinkedList[operations.length];
            for (int i = 0; i < elements.length; ++i) {
                this.elements[i] = new LinkedList<>();
            }
        }

        public ExpressionBuilder<T> add(T element) {
            if (element == null) {
                throw new NullPointerException();
            }
            if (!operationDeclared) {
                if (defaultLevel < 0) {
                    throw new IllegalArgumentException("two elements in row");
                } else {
                    insertOperation(defaultLevel);
                }
            }
            while (!unary.isEmpty()) {
                element = unary.pop().apply(element);
            }
            elements[currentLevel].addLast(element);
            operationDeclared = false;

            return this;
        }

        private T evaluate(int level) {
            Deque<T> q = elements[level];
            BinaryOperator<T> op = operations[level];
            T result = q.pollFirst();
            while (!q.isEmpty()) {
                result = op.apply(result, q.pollFirst());
            }
            return result;
        }

        private void insertOperation(int i) {
            while (currentLevel > i) {
                T result = evaluate(currentLevel);
                currentLevel = levelHistory.pop();
                elements[currentLevel].addLast(result);
            }
            if (i > currentLevel) {
                elements[i].addLast(elements[currentLevel].pollLast());
                levelHistory.add(currentLevel);
            }
            currentLevel = i;
            operationDeclared = true;
        }

        public ExpressionBuilder<T> operation(UnaryOperator<T> op) {
            unary.add(op);
            return this;
        }

        public ExpressionBuilder<T> operation(int number) {
            if (operationDeclared) {
                throw new IllegalStateException("cannot insert two operations in row");
            }
            if (number < 0 || number >= operations.length) {
                throw new ArrayIndexOutOfBoundsException("unknown operation number");
            }
            insertOperation(number);
            return this;
        }

        public ExpressionBuilder<T> push() {
            return new ExpressionBuilder<>(this, defaultLevel, operations);
        }

        public ExpressionBuilder<T> pop() {
            if (parent == null) {
                throw new IllegalStateException("non-matched brackets detected");
            } else {
                parent.add(build());
                return parent;
            }
        }

        public T build() {
            while (true) {
                T result = evaluate(currentLevel);
                if (levelHistory.isEmpty()) {
                    return result;
                }
                currentLevel = levelHistory.pop();
                elements[currentLevel].addLast(result);
            }
        }
    }

**Comment by renaudpawlak** [comment]
Ouch! It looks like you found a bug in the new release.
I will patch it ASAP.
Thanks.

**Comment by renaudpawlak** [comment]
BTW, this code will not go through anyways because the stream API is not supported yet by J4TS. I'll put it on the todo list though. Besides the bug and the stream API, I don't see any other reasons why this code wouldn't work with JSweet.

**Comment by fedorov-s-n** [comment]
Actually, stream API isn't needed here - only generics and lambdas. I've edited issue message.

**Comment by renaudpawlak** [comment]
Ok. This should work with the patch then.
Actually, your code revealed a couple of additional issues:
- bug in constructor overloading with varargs (I already fixed it)
- lack of support for constructor references: ``LinkedList::new`` and ``LinkedList[]::new`` (I have almost finished, although not needed if you don't use the stream API) 

The stream API will be a good thing to support anyway because they intensively use lambdas.

I will deploy a patch release (1.1.1) ASAP.

**Comment by fedorov-s-n** [comment]
Thanks for fast response!
I want to continue testing jsweet possibilities. Is there a snapshot with your fix?

**Comment by renaudpawlak** [comment]
You can try using 1.1.1-SNAPSHOT (just use this version on the maven plugin and it should work).
Be careful though, it is a dev version and may contain occasional regressions...
I'll keep in touch.

**Comment by fedorov-s-n** [comment]
Thanks! But I failed to get update. It looks like updated plugin links to 1.1.0 transpiler. Have I missed something?

		<dependency>
			<groupId>org.jsweet</groupId>
			<artifactId>jsweet-transpiler</artifactId>
			<version>1.1.0</version>
		</dependency>

**Comment by renaudpawlak** [comment]
You are right, I messed up (sorry).
It should be fine now.
BTW, I have finished and tested the patch so make sure you have the latest jar in your repo.
I guess that I'll wait that you perform further tests before I release the 1.1.1 patch version ;)

**Comment by renaudpawlak** [comment]
Looks like this have been at least partially resolved. If anything remains, please report specific issues. Thanks.
