### ISSUE TITLE
Code for the compilation server

### ISSUE THREAD

**Issue by tomitrescak** [cincheo/jsweet#125]
Hi, thanks for this fantastic package. I wanted to ask, if by any chance you have somewhere the code for that web service that you use to compile the code in your sandbox editor.

I am not very good in java web development and it would save me significant time to try to play with it. Kindly appreciated.

**Comment by renaudpawlak** [comment]
We will think on the best way to do it and we need to clean up the code first ;)
But on the principles I agree. I am closing this issue in favor or issue #124 which is related.
