### ISSUE TITLE
Support enum fields and constructors

### ISSUE THREAD

**Issue by ikarienator** [cincheo/jsweet#128]
For that, we need wrapper objects.

````java
enum E {
  A(3), B(5);
  private int a;
  E(int a) { this. a = a; }
  public int getA() { return a; }
}
```
into

```typescript

export enum E {
  A,
  B,
}

class E_$WRAPPER extends java.lang.Enum {
  private a: number;
  constructor(a: int) { this.a = a; }
  public getA() : number { return this.a; }
}

E.$WRAPPERS = {};
E.$WRAPPERS[E.A] = new E_$WRAPPER(3);
E.$WRAPPERS[E.B] = new E_$WRAPPER(5);

**Comment by renaudpawlak** [comment]
Thanks! I think that we should plan full enum support for 1.2.

I would skip the wrapper part and generate enums almost exactly like Java does internally, which means that I would totally drop TypeScript enums (which I find hacky anyways...).

So, your example code would give:

```typescript
class E extends java.lang.Enum<E> {
  public static final A : E = new E(3);
  public static final B : E = new E(5);
  private int a;
  private E(int a) { this. a = a; }
  public int getA() { return a; }
}
```

I am not inventing anything here but just doing something similar to what Java is doing.

Then I think that depending whether the ``java.lang.Enum`` class is available or not (it is only available if the j4ts candy is there), then we can either inline or extend the ``java.lang.Enum`` class...

What I am not sure of is whether we will miss anything by dropping completely TypeScript enums.

What do you thing?

**Comment by ikarienator** [comment]
For `switch` statements, we can use `.ordinal()`. In fact, if this is way we want to go, we can simply ignore the special casing for enums in transpiler and go with the normal code generation. I'll try to create a pull request this afternoon.

**Comment by renaudpawlak** [comment]
That would be great. 👍

**Comment by mb720** [comment]
Do you need help implementing this, or is this already done?
I'd really like to use enums.

**Comment by renaudpawlak** [comment]
@ikarienator : No news on this issue? Maybe we are missing some difficult point?
@mb720 : it looks that we might need help on this issue :)

Guys, I have created an ``enums_support`` branch. We can use it to try the enums thoroughly and experiment or validate any proposal, so don't be afraid to PR on this branch. I will myself try some things out when I have more time.

**Comment by renaudpawlak** [comment]
Hi! I have finally found the time to support full enums. The new implementation is very close to @ikarienator initial proposal, which was excellent. It adds wrappers around regular TypeScript enums only when needed. So, it remains completely compatible with TypeScript enums (which means no regression or interop issues in theory). Note that so far, the enum wrapper do not extend the ``java.lang.Enum`` class to avoid depending on a runtime. Instead it inlines the ``name()`` and ``ordinal()`` method in each enum wrappers. Feedback will determine if we keep it this way.

I hope you will enjoy it and thanks again to @ikarienator.
