### ISSUE TITLE
jsweet::is-my-json-valid - How do I validate JSON data, with full error report?

### ISSUE THREAD

**Issue by ustegrew** [cincheo/jsweet#144]
I'm working on a Javascript project and use the JSweet framework for writing the Javascript part. As part of it's function, my application will asynchronously load some JSON data (stored as separate file). I would like to validate that data using a JSON schema validator. JSweet offers several such validators, one of which is a port of 'is-my-json-valid' (original Javascript library in https://github.com/mafintosh/is-my-json-valid, JSweet port in http://public.jsweet.org/apidocs/releases/org/jsweet/candies/is-my-json-valid).

I am already able to use the is-my-json-valid library to give me a true/false indication of whether a given JSON chunk conforms to a given JSON schema. However, in case of a failing validation, I would also like to retrieve error details as to why it failed (e.g. 'required attribute blah').

How would I have to use the is-my-json-valid library in JSweet so I get more than a true/false indication - i.e. I am also getting a full report telling me what was wrong with my JSON data?

Here is my JSweet test program. The transpiled Javascript already throws the exception correctly - the only thing that would gladden my heart is a detailed error report:

```
package json_valid.test_01;

import static def.is_my_json_valid.Globals.is_my_json_valid;

import jsweet.lang.Error;
import jsweet.lang.JSON;

public class Test_01
{
    public static void main (String[] args)
    {
        String              sSchema;
        String              sTestFail;
        String              sTestPass;

        sSchema     =
            "{\n"
            + "  \"required\": true,\n"
            + "  \"type\": \"object\",\n"
            + "  \"properties\": {\n"
            + "    \"hello\": {\n"
            + "      \"required\": true,\n"
            + "      \"type\": \"string\"\n"
            + "    }\n"
            + "  }\n"
            + "}\n";
        sTestFail       = "{\"a\": \"b\"}";
        sTestPass       = "{\"hello\": \"world\"}";
        _AssertConforms (sTestPass, sSchema);   /* Ok - expect nothing printed to console  */
        _AssertConforms (sTestFail, sSchema);   /* AiaOw - expect error message on console */
    }

    private static void _AssertConforms (String jsonData, String jsonSchema)
    {
        Object              oSchema;
        Object              oTested;
        boolean             result;
        String              specifics;
        String              message;

        oTested = JSON.parse (jsonData);
        oSchema = JSON.parse (jsonSchema);
        result = is_my_json_valid (oSchema).apply (oTested);
        if (! result)
        {
            specifics = "Sorry, still waiting for that nifty code to extract error specifics from is-my-json-valid.";
            message   = "Validation failed. Error specifics: " + specifics;
            throw new Error (message);
        }
    }
}
```

For the method `_AssertConforms` I have already tried the following variant:

```
private static void _AssertConforms (String jsonData, String jsonSchema)
{
    Object              oSchema;
    Object              oTested;
    boolean             result;
    String              specifics;
    String              message;
    ValidateFunction    vf;
    ValidationError[]   vee;
    int                 i;
    ValidationError     ve;

    oTested = JSON.parse (jsonData);
    oSchema = JSON.parse (jsonSchema);
    vf      = is_my_json_valid (oSchema);
    result  = vf.apply (oTested);
    if (! result)
    {
        specifics = "";
        vee       = vf.errors;
        if (vee.length >= 1)
        {
            for (i = 0; i < vee.length; i++)
            {
                ve         = vee [i];
                specifics += ve.field + " --> " + ve.message + "\n";
            }
        }

        message   = "Validation failed. Error specifics:\n" + specifics;
        throw new Error (message);
    }
}
```

However, this gives me the following JSWeet transpiler errors:

```
Description Resource    Path    Location    Type
';' expected.   jsweet-test-01      Unknown JSweet Problem
';' expected.   jsweet-test-01      Unknown JSweet Problem
```

These seem to come from the following imports:
`import def.is_my_json_valid.is_my_json_valid.ValidateFunction;`
`import def.is_my_json_valid.is_my_json_valid.ValidationError;`

In my trials, I got the JSweet transpiler errors by merely importing `def.is_my_json_valid.is_my_json_valid.ValidateFunction` even without actually using the import.

My HTML test page is rather boring:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="US-ASCII">
<title>JSON validator test</title>
<script src="../../../target/dist/bundle-test_01.js"></script>
</head>
<body>

</body>
</html>
```

However, when I load the page into my Chrome web browser, the web console provides me with an exception as expected:

```
bundle-test_01.js:1535 Uncaught Error: Validation failed. Error specifics: Sorry, still waiting for that nifty code to extract error specifics from is-my-json-valid.
    Test_01._AssertConforms @ bundle-test_01.js:1535
    Test_01.main @ bundle-test_01.js:1521
    12.is-my-json-valid @ bundle-test_01.js:1541
    s @ bundle-test_01.js:1
    e @ bundle-test_01.js:1
    (anonymous function) @ bundle-test_01.js:1
```

All I am missing is the error details in the exception message.

Just a potshot - would this be related to issue https://github.com/cincheo/jsweet/issues/145 ?

Thank you so much for your consideration!

Development setup:
- Eclipse platform:
  `Eclipse Java EE IDE for Web Developers. Version: Mars.1 Release (4.5.1), Build id: 20150924-1200`
- JSweet plugin:
  `JSweet 0.9.3.201602051118 org.jsweet.feature.feature.group JSweet`

My pom.xml

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <groupId>jsweet-test-01</groupId>
 <artifactId>jsweet-test-01</artifactId>
 <version>0.0.1-SNAPSHOT</version>


 <!--­­ repositories ­­ -->
  <repositories>
    <repository>
      <id>jsweet-central</id>
      <name>libs-release</name>
      <url>http://repository.jsweet.org/artifactory/libs-release-local</url>
    </repository>
    <repository>  
      <snapshots />  
      <id>jsweet-­snapshots</id>  
      <name>libs-­snapshot</name>  
      <url>http://repository.jsweet.org/artifactory/libs­-snapshot-­local</url>  
    </repository>  
  </repositories>
 <!--­­ end repositories ­­ -->


 <!-- dependencies ­­ -->

 <!-- end dependencies ­­ -->


 <build>
  <sourceDirectory>src</sourceDirectory>
  <plugins>
   <plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.3</version>
    <configuration>
     <source>1.8</source>
     <target>1.8</target>
    </configuration>
   </plugin>
  </plugins>
 </build>
 <dependencies>
  <dependency>
   <groupId>org.jsweet.candies</groupId>
   <artifactId>jsweet-core</artifactId>
   <version>1.1.0-SNAPSHOT</version>
  </dependency>
  <dependency>
    <groupId>org.jsweet.candies</groupId>
    <artifactId>is-my-json-valid</artifactId>
    <version>0.0.0-1.1.0-20160525</version>
  </dependency>
 </dependencies>
</project>
```

**Comment by renaudpawlak** [comment]
First things first. Try to update your JSweet plugin to version 0.9.4.x and see if it solves the errors:

```
Description Resource    Path    Location    Type
';' expected.   jsweet-test-01      Unknown JSweet Problem
';' expected.   jsweet-test-01      Unknown JSweet Problem
```

**Comment by ustegrew** [comment]
Suggested step done, and it's already helped towards a solution! Thank you! The only remaining issue is this one. With the test code below I now get these transpiler errors:

```
Description Resource    Path    Location    Type
'=' expected    Is_My_Json_Valid_Test_01.java   /jsweet-test-01/src/json_valid/is_my_json_valid_test_01 line 78 JSweet Problem
'=' expected    Is_My_Json_Valid_Test_01.java   /jsweet-test-01/src/json_valid/is_my_json_valid_test_01 line 79 JSweet Problem
'=' expected    Is_My_Json_Valid_Test_01.java   /jsweet-test-01/src/json_valid/is_my_json_valid_test_01 line 80 JSweet Problem
```


The test code at the moment:

    /**
    * This file is part of jsweet-test-01.
    * 
    * jsweet-test-01 is free software: you can redistribute it and/or modify
    * it under the terms of the GNU General Public License as published by
    * the Free Software Foundation, either version 3 of the License, or
    * (at your option) any later version.
    * 
    * jsweet-test-01 is distributed in the hope that it will be useful,
    * but WITHOUT ANY WARRANTY; without even the implied warranty of
    * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    * GNU General Public License for more details.
    * 
    * You should have received a copy of the GNU General Public License
    * along with jsweet-test-01.  If not, see <http://www.gnu.org/licenses/>.
    */

    package json_valid.is_my_json_valid_test_01;

    import static def.is_my_json_valid.Globals.is_my_json_valid;

    import def.is_my_json_valid.is_my_json_valid.ValidateFunction;
    import def.is_my_json_valid.is_my_json_valid.ValidationError;
    import jsweet.lang.Error;
    import jsweet.lang.JSON;

    /**
    * @author Peter Hoppe
    */
    public class Is_My_Json_Valid_Test_01
    {
        public static void main (String[] args)
        {
            String              sSchema;
            String              sTestFail;
            String              sTestPass;
            
            sSchema     =
                "{\n"
                + "  \"required\": true,\n"
                + "  \"type\": \"object\",\n"
                + "  \"properties\": {\n"
                + "    \"hello\": {\n"
                + "      \"required\": true,\n"
                + "      \"type\": \"string\"\n"
                + "    }\n"
                + "  }\n"
                + "}\n";
            sTestFail       = "{\"a\": \"b\"}";
            sTestPass       = "{\"hello\": \"world\"}";
            _AssertConforms (sTestPass, sSchema);   /* Ok - expect nothing printed to console  */
            _AssertConforms (sTestFail, sSchema);   /* AiaOw - expect error message on console */
        }
        
        private static void _AssertConforms (String jsonData, String jsonSchema)
        {
            Object              oSchema;
            Object              oTested;
            boolean             result;
            String              specifics;
            String              message;
            ValidateFunction    vf;
            ValidationError[]   vee;
            int                 i;
            ValidationError     ve;
            
            oTested = JSON.parse (jsonData);
            oSchema = JSON.parse (jsonSchema);
            vf      = is_my_json_valid (oSchema);
            result  = vf.apply (oTested);
            if (! result)
            {
                specifics = "";
                vee       = vf.errors;
                if (vee.length >= 1)
                {
                    for (i = 0; i < vee.length; i++)
                    {
                        ve         = vee [i];
                        specifics += ve.field + " --> " + ve.message + "\n";
                    }
                }
                    
                message   = "Validation failed. Error specifics:\n" + specifics;
                throw new Error (message);
            }
        }
    }

Thank you for your help!

**Comment by renaudpawlak** [comment]
Could you post the generated TypeScript code please? You should find it in the default generation directory (probably .jsweet/ts if you did not change it).

**Comment by ustegrew** [comment]
With pleasure! Here goeth:

    "Generated from Java with JSweet 1.1.0 - http://www.jsweet.org"; namespace json_valid.is_my_json_valid_test_01 {     

        

        
        
        
        




    /**
    * @author Peter Hoppe
    */
    export class Is_My_Json_Valid_Test_01 {         

    public static main(args : string[]) {             

    var sSchema : string;             
    var sTestFail : string;             
    var sTestPass : string;             

    sSchema = 

    "{\n  \"required\": true,\n  \"type\": \"object\",\n  \"properties\": {\n    \"hello\": {\n      \"required\": true,\n      \"type\": \"string\"\n    }\n  }\n}\n";             








    sTestFail = "{\"a\": \"b\"}";             
    sTestPass = "{\"hello\": \"world\"}";             
    Is_My_Json_Valid_Test_01._AssertConforms(sTestPass, sSchema);             
    Is_My_Json_Valid_Test_01._AssertConforms(sTestFail, sSchema);         }          


    private static _AssertConforms(jsonData : string, jsonSchema : string) {             

    var oSchema : any;             
    var oTested : any;             
    var result : boolean;             
    var specifics : string;             
    var message : string;             
    var vf : is-my-json-valid.ValidateFunction;             
    var vee : is-my-json-valid.ValidationError[];             
    var i : number;             
    var ve : is-my-json-valid.ValidationError;             

    oTested = JSON.parse(jsonData);             
    oSchema = JSON.parse(jsonSchema);             
    vf = is_my_json_valid(oSchema);             
    result = vf(oTested);             
    if(!result) 
    {                 
    specifics = "";                 
    vee = vf.errors;                 
    if(vee.length >= 1) 
    {                     
    for(i = 0; i < vee.length; i++) 
    {                         
    ve = vee[i];                         
    specifics += ve.field + " --> " + ve.message + "\n";                     }                 }                 



    message = "Validation failed. Error specifics:\n" + specifics;                 
    throw new Error(message);             }         }     } } 

    json_valid.is_my_json_valid_test_01.Is_My_Json_Valid_Test_01.main(null);

**Comment by renaudpawlak** [comment]
Ok. I have bad news.

I took a closer look to is-my-json-valid, and it seems that it is only provided as a node module. That wouldn't be an issue and in theory, you would just need to compile with the "module" option. However, it seems that the way the module is defined is not supported yet by JSweet. It looks like JSweet cannot require properly the module, as it is specified here: https://github.com/mafintosh/is-my-json-valid.

In general, before using a module, it is good to know if it can be used from the browser, because node modules are still only partially supported in JSweet.

The good news is that is-my-json-valid seems to be the perfect use case that I was looking for to improve JSweet's requires, as already discussed in #129. So I will be working on it ASAP.

**Comment by renaudpawlak** [comment]
Note: if you find a way to use is-my-json-valid in a browser (without modules), you should be able to access it through ``$get`` function.

**Comment by ustegrew** [comment]
Excellent! It looks like is-my-json-valid was intended to be used as a node.js module - I'll have a look what I can do to use it. Once I found a way I'll post it here. Thank you so much for your help and the hint to use the $get method!

Keep up the good work!

**Comment by ustegrew** [comment]
Your suggestion from issue https://github.com/cincheo/jsweet/issues/129 got me on the right path. I thought I share my solution for the benefit of others.

To make it work I needed to make a standalone javascript module (browserify) and import it into my test html document.

# Creating standalone is-my-json-valid

Prerequesites:
```
node.js
npm
browserify
```    
    
when browserify-ing it, is-my-json-valid needs a few more npm modules (see below on installing):
```
jsonpointer
generate-object-property
generate-function
xtend
```
    
Create a work directory and cd into it:
```
~$ mkdir /home/peter/dev/is-my-json-valid
~$ cd /home/peter/dev/is-my-json-valid 
```

Clone the git repository of is-my-json-valid
```
~/dev/is-my-json-valid$ git clone https://github.com/mafintosh/is-my-json-valid.git
Cloning into 'is-my-json-valid'...
remote: Counting objects: 615, done.
remote: Total 615 (delta 0), reused 0 (delta 0), pack-reused 615
Receiving objects: 100% (615/615), 125.43 KiB | 0 bytes/s, done.
Resolving deltas: 100% (354/354), done.
Checking connectivity... done.
```
    
This creates a directory `/home/peter/dev/is-my-json-valid/is-my-json-valid` with the contents of the cloned repo. CD into it
```
~/dev/is-my-json-valid$ cd is-my-json-valid/
```

Now we invoke browserify build the standalone javascript module (Note the --standalone switch):
```
~/dev/is-my-json-valid/is-my-json-valid$ browserify ./index.js --standalone is-my-json-valid > ./is-my-json-valid_standalone.js
Error: Cannot find module 'jsonpointer' from '/home/peter/dev/is-my-json-valid/is-my-json-valid'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

Whoopsidaisy - we are missing a dependency (jsonpointer). Let's install it locally
```
~/dev/is-my-json-valid/is-my-json-valid$ npm install jsonpointer
npm http GET https://registry.npmjs.org/jsonpointer/2.0.0
npm http 304 https://registry.npmjs.org/jsonpointer/2.0.0
jsonpointer@2.0.0 node_modules/jsonpointer
```
    
To make a long story short - we need a few more dependencies. 
```
~/dev/is-my-json-valid/is-my-json-valid$ npm install generate-object-property
~/dev/is-my-json-valid/is-my-json-valid$ npm install generate-function       
~/dev/is-my-json-valid/is-my-json-valid$ npm install xtend            
```
    
_Note that all dependencies will be installed locally, i.e. inside `~/dev/is-my-json-valid/is-my-json-valid/node_modules`. I could have installed them globally (`npm -g <package>`), but I just decided to choose the local way._

Now let's re-issue the build
```
~/dev/is-my-json-valid/is-my-json-valid$ browserify ./index.js --standalone is-my-json-valid > ./is-my-json-valid_standalone.js
```

This creates a new file `~/dev/is-my-json-valid/is-my-json-valid/is-my-json-valid_standalone.js`. That's the module we need, and we can use it as-is. When the script loads into the web browser the validator function can be accessed as global variable `window.isMyJsonValid`. That's why I used the `--standalone` option; otherwise I'd have ended up having to edit the browserify-ed js file. To use the module:



#Running the validator in the browser#

##The JSweet test class##

I created bundle.js from this jsweet test class:

```java
package json_valid.is_my_json_valid_test_01;

import static jsweet.dom.Globals.console;
import static jsweet.dom.Globals.window;
import static jsweet.util.Globals.$apply;
import static jsweet.util.Globals.$get;

import jsweet.lang.JSON;

/**
 * @author Peter Hoppe
 */
public class Is_My_Json_Valid_Test_01
{
    private static jsweet.lang.Object gValidator = null;
    
    public static void main (String[] args)
    {
        window.onload = (e) ->
        {
            _CreateValidator ();
            _AssertConforms("{\"hello\":\"world\"}");
            _AssertConforms("{\"a\":\"b\"}");
            _AssertConforms("{\"hello\":true}");
            _AssertConforms("{\"hullo\":\"this shouldn t work\"}");
            
            return true;
        };
    }
    
    private static void _AssertConforms (String jsonChunk)
    {
        Object                  oJsonChunk;
        boolean                 result;
        int                     i;
        jsweet.lang.Object[]    err;
        jsweet.lang.Object      erx;
        String                  msg;
        
        oJsonChunk = JSON.parse (jsonChunk);
        
        console.log ("Testing: ", oJsonChunk);
        result  = $apply(gValidator, oJsonChunk);
        if (result)
        {
            console.log ("    Validation PASSED");
        }
        else
        {
            msg = "JSON chunk failed validation. Specifics:";
            err = (jsweet.lang.Object[]) gValidator.$get("errors");
            for (i = 0; i < err.length; i++)
            {
                erx  = err [i];
                msg += "\n    " + erx.$get ("field") + " => " + erx.$get("message");
            }
            console.error (msg);
        }
    }
    
    private static void _CreateValidator ()
    {
        String                  schema;
        Object                  oSchema;
        
        schema =
        "    {\n" +
        "            \"required\": true,\n" +
        "            \"type\": \"object\",\n" +
        "            \"properties\": {\n" +
        "              \"hello\": {\n" +
        "                \"required\": true,\n" +
        "                \"type\": \"string\"\n" +
        "              }\n" +
        "            }\n" +
        "    }";
        
        oSchema     = JSON.parse(schema);
        gValidator  = $apply($get(window,"isMyJsonValid"), oSchema);
    }
}
```

I'm sure, I can improve this - for example, I could have my bundle.js module load the browserified is-my-json-valid module by itself instead of using a script tag in `index.html`.


JSweet trans-piles the java class into this javascript module (`bundle.js`):
```javascript
"Generated from Java with JSweet 1.1.0 - http://www.jsweet.org";
var json_valid;
(function (json_valid) {
    var is_my_json_valid_test_01;
    (function (is_my_json_valid_test_01) {
        /**
         * @author Peter Hoppe
         */
        var Is_My_Json_Valid_Test_01 = (function () {
            function Is_My_Json_Valid_Test_01() {
            }
            Is_My_Json_Valid_Test_01.main = function (args) {
                window.onload = function (e) {
                    Is_My_Json_Valid_Test_01._CreateValidator();
                    Is_My_Json_Valid_Test_01._AssertConforms("{\"hello\":\"world\"}");
                    Is_My_Json_Valid_Test_01._AssertConforms("{\"a\":\"b\"}");
                    Is_My_Json_Valid_Test_01._AssertConforms("{\"hello\":true}");
                    Is_My_Json_Valid_Test_01._AssertConforms("{\"hullo\":\"this shouldn t work\"}");
                    return true;
                };
            };
            Is_My_Json_Valid_Test_01._AssertConforms = function (jsonChunk) {
                var oJsonChunk;
                var result;
                var i;
                var err;
                var erx;
                var msg;
                oJsonChunk = JSON.parse(jsonChunk);
                console.log("Testing: ", oJsonChunk);
                result = Is_My_Json_Valid_Test_01.gValidator(oJsonChunk);
                if (result) {
                    console.log("    Validation PASSED");
                }
                else {
                    msg = "JSON chunk failed validation. Specifics:";
                    err = Is_My_Json_Valid_Test_01.gValidator["errors"];
                    for (i = 0; i < err.length; i++) {
                        erx = err[i];
                        msg += "\n    " + erx["field"] + " => " + erx["message"];
                    }
                    console.error(msg);
                }
            };
            Is_My_Json_Valid_Test_01._CreateValidator = function () {
                var schema;
                var oSchema;
                schema = "    {\n            \"required\": true,\n            \"type\": \"object\",\n            \"properties\": {\n              \"hello\": {\n                \"required\": true,\n                \"type\": \"string\"\n              }\n            }\n    }";
                oSchema = JSON.parse(schema);
                Is_My_Json_Valid_Test_01.gValidator = window["isMyJsonValid"](oSchema);
            };
            Is_My_Json_Valid_Test_01.gValidator = null;
            return Is_My_Json_Valid_Test_01;
        }());
        is_my_json_valid_test_01.Is_My_Json_Valid_Test_01 = Is_My_Json_Valid_Test_01;
    })(is_my_json_valid_test_01 = json_valid.is_my_json_valid_test_01 || (json_valid.is_my_json_valid_test_01 = {}));
})(json_valid || (json_valid = {}));
json_valid.is_my_json_valid_test_01.Is_My_Json_Valid_Test_01.main(null);
```

_Note that in Eclipse, in my project properties I switched the "Create browser bundle" option on: Right click project, then in the dialog click JSweet, tick "Create browser bundle". This made JSweet package the project into one single file `bundle.js`_

##Running the thing##

Now we create a test html page (`index.html`) which includes the `is-my-json-valid_standalone.js` file and after that my jsweet generated module (for now as separate script tags): 
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="US-ASCII">
<title>JSON validator test</title>
<script src="path_to_is-my-json-valid_standalone.js"></script>
<script src="path_to_my_jsweet-generated/bundle.js"></script>
</head>
<body>

</body>
</html>
```

Once I load this page into my web browser (Chromium), the web console gives me the desired output with all the error specifics:

```
Testing:  Object {hello: "world"}
bundle.js:33     Validation PASSED
bundle.js:30 Testing:  Object {a: "b"}
bundle.js:42 JSON chunk failed validation. Specifics:
    data.hello => is requiredIs_My_Json_Valid_Test_01._AssertConforms @ bundle.js:42window.onload @ bundle.js:16
bundle.js:30 Testing:  Object {hello: true}
bundle.js:42 JSON chunk failed validation. Specifics:
    data.hello => is the wrong typeIs_My_Json_Valid_Test_01._AssertConforms @ bundle.js:42window.onload @ bundle.js:17
bundle.js:30 Testing:  Object {hullo: "this shouldn t work"}
bundle.js:42 JSON chunk failed validation. Specifics:
    data.hello => is requiredIs_My_Json_Valid_Test_01._AssertConforms @ bundle.js:42window.onload @ bundle.js:18
```

And my heart was thoroughly gladdened!


Thank you so much again for your ideas and input!

Attached:

[test_is-my-json-valid.zip](https://github.com/cincheo/jsweet/files/351826/test_is-my-json-valid.zip)

**Comment by renaudpawlak** [comment]
That's a very nice explanation. It looks like you had to untype a little bit your original code, which is unfortunate. It should get better in the future. Thanks!

**Comment by ustegrew** [comment]
Thank you! No worries about the untyping - I've got some working code which is the main thing. I'll be encapsulating the Validator in it's own class which means all the untyping will be hidden. 

I understand that JSweet is a relatively new project, and implementing a good framework is very hard. Having gone through the difficulties working with a large Javascript codebase myself I'm enjoying working with JSweet as I now have all the type safety of Java and good tooling support of Eclipse!

Many many thanks for all your work!
