### ISSUE TITLE
candy jsweet-core:1.1.0-SNAPSHOT was generated for a different version of the transpiler (current:1.0.0, candy:1.1.0)

### ISSUE THREAD

**Issue by ustegrew** [cincheo/jsweet#145]
I am working on a Javascript project and am using the JSweet framework. I am developing on Eclipse using the JSweet plugin. Whenever I build my project I get the following warning:

`candy jsweet-core:1.1.0-SNAPSHOT was generated for a different version of the transpiler (current:1.0.0, candy:1.1.0)`

I suspect I have to update my project to use jsweet, version 1.1.0. Are there any instructions on how to do this? If not - how do I make my project use the jsweet transpiler, version 1.1.0, or any other release/snapshot version?

(I suspect, this may be related to issue https://github.com/cincheo/jsweet/issues/144 )

Thank you very much!

My pom.xml file is:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>jsweet-test-01</groupId>
    <artifactId>jsweet-test-01</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    
    
    
    <repositories>
        <repository>
        <id>jsweet-central</id>
        <name>libs-release</name>
        <url>http://repository.jsweet.org/artifactory/libs-release-local</url>
        </repository>
        <repository>  
        <snapshots />  
        <id>jsweet-­snapshots</id>  
        <name>libs-­snapshot</name>  
        <url>http://repository.jsweet.org/artifactory/libs­-snapshot-­local</url>  
        </repository>  
    </repositories>
    

    
    
    

    <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
    <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
        <configuration>
        <source>1.8</source>
        <target>1.8</target>
        </configuration>
    </plugin>
    </plugins>
    </build>
    <dependencies>
    <dependency>
    <groupId>org.jsweet.candies</groupId>
    <artifactId>jsweet-core</artifactId>
    <version>1.1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>org.jsweet.candies</groupId>
        <artifactId>is-my-json-valid</artifactId>
        <version>0.0.0-1.1.0-20160525</version>
    </dependency>
    </dependencies>
    </project>

Eclipse JSweet plugin:
      JSweet	0.9.3.201602051118	org.jsweet.feature.feature.group	JSweet

Eclipse version:
    Version: Mars.1 Release (4.5.1) Build id: 20150924-1200

**Comment by renaudpawlak** [comment]
You need to update your JSweet Eclipse plugin and use 0.9.4.x, which embeds JSweet version 1.1.x. Note that with JSweet version 1.1.x, you can also use the j4ts candy (which allows you to use Java collections). Normally ``Help > Check for update`` should prompt you to update JSweet... If it does not, please tell me because it might be a bug in the update site. You can then try to uninstall the plugin and install it again.

We will check issue #144 once your version is up-to-date.

**Comment by ustegrew** [comment]
Many thanks for the fast reply! I wish, I'd be that fast answering mails! I managed to do the JSweet update, and now the warning is gone! I'm on version:  `JSweet 0.9.4.201605260823`. Issue https://github.com/cincheo/jsweet/issues/144 still persists, but has better error feedback now.  However, this particular issue looks solved now!

Thanks so much again!
