### ISSUE TITLE
Transpilation issue

### ISSUE THREAD

**Issue by GegeFR** [cincheo/jsweet#147]
Hi,

I'm trying to develop kind of a framework based on jsweet. I'm trying to do kind of a fluent API (only kind of because I'm meeting issues with jsweet when doing complicated inheritence and generic typing).

Instead of trying to workaround those issues I'll try to report them.

Right now I'm having the following transpilation issue (with 1.1.1 as well as with 1.2.0-SNAPSHOT) :

```
ERROR: 'super' must be followed by an argument list or member access at /home/osadmin/Developpement/projets/MonTestJsweet/src/main/java/com/mycompany/montestjsweet/builder/bootstrap/BSPanel.java(45)
 transpilation failed
 org.apache.maven.plugin.MojoFailureException: transpilation failed with 1 error(s) and 0 warning(s)
 	at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:304)
 	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

```
Also, the generated JS contains the following erroneous line :

```
(this['__jswref_0'] = _super.prototype.).bs_classes.apply(this['__jswref_0'], ["panel"].concat(styles));
```
The incriminated code looks quite normal so maybe the cause of the error is somewhere else ...

```
 public class BSPanel extends HTMLNode {
 
         BasicNode header = null;
         BasicNode body = null;
         BasicNode footer = null;
 
         protected BSPanel(HTMLElement e) {
             super(e);
         }
         ...
}
```

You'll find attached the maven project "as is".

FYI I'm trying to build some classes that would build the DOM through jsweet fluent API basic HTML or custom components (targeting bootstrap)... That, and also to be isomorphic with the help of jsdom + nodejs (pre-render the dom through the same jsweet code server-side and "hook" the "controlers" part of the web page back into the pre-rendered DOM).

It's going quite smoothly, but I'm frequently having issues with the transpilation that I don't understand.

[project.zip](https://github.com/cincheo/jsweet/files/355512/project.zip)

**Comment by GegeFR** [comment]
OK; I tracked it down just after writing this ticket ...

The cause of the issue was cause by the following java line :
super.someMethodOfTheSuperClass();

When replaced by the following, it's OK :
someMethodOfTheSuperClass();

**Comment by lgrignon** [comment]
Nice, what a quick fix! :)

Thanks.

**Comment by GegeFR** [comment]
I tried to reproduce the issue on another test project with minimalistic classes but I could not, it transpiled correctly.

So there might be multiple factors to that transpilation issue.

**Comment by renaudpawlak** [comment]
I cannot be sure 100% but I think that I fixed this issue (or a very similar one?) in the latest snapshot. Tell me if it happens again.

**Comment by myaskevich** [comment]
I'm getting the same error while trying to transpile a third-party java library:

```
2018-06-12 23:00:28.028 INFO  TypeScript2JavaScriptWithTscTranspiler:90 - com/prowidesoftware/swift/model/mt/mt8xx/MT802.ts(230,51): error 
TS1034: 'super' must be followed by an argument list or member access.                                                                     
2018-06-12 23:00:28.028 ERROR output:55 - 'super' must be followed by an argument list or member access at /Users/maximyaskevich/Projects/g
ithub/jsweet-quickstart/src/main/java/com/prowidesoftware/swift/model/mt/mt8xx/MT802.java(319)
```

```java
@Override
public MT802 append(final Field ... fields) {
        super.append(fields);
        return this;
}
```

Since this is a valid Java code, why would jsweet choke on that one?

**Comment by lgrignon** [comment]
Hello. Which version of jsweet are you using please?

**Comment by myaskevich** [comment]
Is there anything I can do to help resolve the issue @lgrignon ?

**Comment by lgrignon** [comment]
Hello, Unfortunately I won't have time this week to take a look.
The best when you try to transpile a big library is to try step by step, adding small part.

Even if the JSweet's Java API support is pretty good, some bugs may remain (I think you hit one transpilation bug in some syntactic case).

You could help by trying to reduce the case to a minimal example and file a specific issue for it. You could also try to run the transpiler in debug mode, if you feel you can do it.

When I asked the JSweet version, I wasn't talking about the jsweet-core version (which is the Core API - dom definitions, core JS classes etc) but rather the JSweet version (if you are on maven, this would be the jsweet maven plugin version).

Thanks for reporting anyway

**Comment by myaskevich** [comment]
I noticed the error likely happens during the ts -> js transpilation stage, not, java -> ts.
Since I'm only interested in ts sources, is there a way to only run java -> ts process without generating js code?

**Comment by myaskevich** [comment]
Solved by adding `<tsOnly>true</tsOnly>`. Thanks @lgrignon

**Comment by lgrignon** [comment]
Okay, nice
