### ISSUE TITLE
Generics <? super K> not being transpiled

### ISSUE THREAD

**Issue by sadevelopment** [cincheo/jsweet#149]
Hi,

I am seeing some issues whilst I am seeing what the capabilities (i.e. what existing java libraries i can transpile) JSweet has. Currently my latest library I am trying to convert (or see if I can) to TS & JS is Guava. I get the following: 

ERROR: method emptyMultiset in class com.google.common.collect.ImmutableSortedMultiset<E> cannot be applied to given types;
  required: java.util.Comparator<? super E>
  found: com.google.common.collect.Ordering<capture#1 of ? super E>
  reason: cannot infer type-variable(s) E,S
    (argument mismatch; com.google.common.collect.Ordering<capture#2 of ? super E> cannot be converted to java.util.Comparator<? super capture#2 of ? super E>)

Ordering is in impl of Comparator.

Any help would be most appreciated. Additionally I am seeing a lot of 

Possible heap pollution from parameterized vararg type E

throughout the process.

Regards

**Comment by renaudpawlak** [comment]
Do you think you can isolate the problem by writing a single test file containing the issue and posting the code here? If you can, then it will be easy to write a test and fix the problem.

**Comment by renaudpawlak** [comment]
Too old... to be tested with version 2.
