### ISSUE TITLE
Method references

### ISSUE THREAD

**Issue by mb720** [cincheo/jsweet#151]
This works fine:
    
    HTMLButtonElement myButton = new HTMLButtonElement();

    onClick(myButton, evt -> console.log("Button clicked"));

    void onClick(HTMLButtonElement button, java.util.function.Consumer<Event> onClick) {
        button.addEventListener("click", evt -> onClick.accept(evt));
    }

Yet, when I use a method reference, which is shorter, like this

    button.addEventListener("click", onClick::accept);

I get this compilation error:

> property 'accept' does not exist on type '(p1: Event) => void'

When I click on the button, I get this runtime error:

> TypeError: onClick.accept is not a function

I know about [this closed issue](https://github.com/cincheo/jsweet/issues/65), but this problem seems quite different to me.

Thanks in advance!

**Comment by renaudpawlak** [comment]
You are right... this way of passing a function is not supported yet in JSweet. It should be supported if we can (I think we can).

Meanwhile, I would have done it this way:

```java
	void onClick(HTMLButtonElement button, EventListener onClick) {
		button.addEventListener("click", onClick);		
	}	
```

It works well and it follows better the DOM API which defines the ``jsweet.dom.EventListener`` functional interface.

Thanks for reporting!
