### ISSUE TITLE
Field and method with same name

### ISSUE THREAD

**Issue by mb720** [cincheo/jsweet#155]
Hi!

I have this class with a field `content` and a getter method with the same name:

```
public class Article {

  private final String content = "empty";

  public String content() {
    return content;
  }
```

I get `TypeError: article.content is not a function` after executing the transpiled version of the following code in the browser:

```
Article article = new Article();
console.log(article.content());
```

When I change `content()` to `getContent()` it works fine.

It would have been nice if I got a warning that JSweet doesn't support fields and methods with the same name.

Keep up the great work!

**Comment by renaudpawlak** [comment]
It looks like a bug.
JSweet supports name clashes for private fields. Also it raises an error when the clash is not possible to resolve. So it looks like you hit a special case but I am quite surprised because your use case look quite simple.
I'll check when possible. Thanks!

**Comment by mb720** [comment]
Thanks for your quick response, Renaud!

Here are some hopefully useful parts from my `build.gradle`:

```
  classpath('org.jsweet:jsweet-gradle-plugin:1.2.0-SNAPSHOT') { transitive = true }

  // The version is overridden by the one in the JSweet Gradle plugin
  compile "org.jsweet:jsweet-transpiler:1.2.0-SNAPSHOT"
  compile "org.jsweet.candies:jsweet-core:1.1.1"
  compile "org.jsweet.candies:j4ts:0.2.0-SNAPSHOT"
  compile "org.jsweet.candies:marked:0.0.0-SNAPSHOT"
  compile "org.jsweet.candies:jquery:1.10.0-SNAPSHOT"

```

**Comment by ooxi** [comment]
I Cannot reproduce your example, the following code

```java
public class Article {

  private final String content = "empty";

  public String content() {
    return content;
  }
	
	public static void main(String[] args) {
		Article article = new Article();
		article.content();
	}
}
```

will be transpiled to

```typescript
"Generated from Java with JSweet 1.1.0 - http://www.jsweet.org";
class Article {
    private __content : string = "empty";

    public content() : string {
        return this.__content;
    }

    public static main(args : string[]) {
        var article : Article = new Article();
        article.content();
    }
}



Article.main(null);
```

Could you provide a minimal example showing your problem?

**Comment by mb720** [comment]
It seems that the bug was fixed in the latest Snapshot version of JSweet core, so I can't reproduce it either, ooxi.
