### ISSUE TITLE
Angular2 Candy documentation not displaying properly

### ISSUE THREAD

**Issue by kito99** [cincheo/jsweet#159]
When I try to view any of the Angular2 docs, I get output of a command rather than the actual docs. Try any of the links here: http://www.jsweet.org/candies-snapshots/.

**Comment by renaudpawlak** [comment]
Indeed, as mentioned in #43, because of the lack of decorator support, the Angular 2 candy is generated, but it is empty :( Javadoc is also empty I would think. We will try to handle #43 ASAP.

**Comment by renaudpawlak** [comment]
Go to https://github.com/jsweet-candies to find the Angular 2 candy and manually modify/update. I will remove it from the other list asap.

**Comment by renaudpawlak** [comment]
JSweet provides a basis of automatically generated candies. It is now very easy to anyone to write his own candies as explained at https://github.com/jsweet-candies. We encourage JSweet users to contribute to existing candies.
