### ISSUE TITLE
Is there a pure JS version of this?

### ISSUE THREAD

**Issue by Pomax** [cincheo/jsweet#162]
I'm working in a pure JS environment and need a java-to-JS conversion solution, so having to rely on maven or gradle, etc. is out - is there a pure JS solution as well that can be loaded through Node.js's `require`?

**Comment by renaudpawlak** [comment]
Short answer is no. JSweet is implemented with the Javac API, which is only available in Java.

Longer answer is that an objective of JSweet is to support most Java APIs (see the cincheo/j4ts project), so, in theory, it should be soon possible to compile the Javac API with JSweet and have it running in a pure JS environnement. Basically, we will use JSweet to compile JSweet to JavaScript. This seemed like science fiction scenario 6 months ago, but we are getting closer... 

JSweet version 1.2 should be available by december and will be able to compile more Java APIs. It will probably be the right time to think again about it.
