### ISSUE TITLE
Mixin support for maven-based projects with IDEs others than Eclipse

### ISSUE THREAD

**Issue by GegeFR** [cincheo/jsweet#163]
I like to use netbeans + maven. With that combination it is currently not possible to use candies that extend a framework, such as bootstrap or jquery plugins (candies that use @Mixin annotation).

The IDE cannot see the plugins' functions added to the framwork's class because they're merged into .class files at transpilation time. In Eclipse it is possible to manually add those .class to the build path, therefore autocompletion works and the IDE can validate the code. However this is not a maven standard behaviour. Netbeans (and maybe other IDEs) don't allow to arbitrary add a folder of .class files to the build path because it strictly relies on the POM and standard maven behaviour.

One solution, to be more maven-friendly, would be to generate mixins as sources files in "target/generated-sources/jsweet-mixins" instead of bytecode (.class files). That way it would also be possible to embed the javadoc in the mixins and that would work perfectly with any IDE with proper maven support, without any trick.

PS : Renaud I know you're fully aware of that topic, we talked a lot about it some month ago. I thought it was worth a ticket here so that it's not forgotten :-)

**Comment by renaudpawlak** [comment]
Thanks @GegeFR. You are right, that would be a real improvement (although, as you know, there are workarounds by using the ``jsweet.util.Globals`` API to access the mixins in an untyped way).

**Comment by renaudpawlak** [comment]
@GegeFR : I am curious to have your feedback about cancelling the current mixin approach in favor of a simpler and more standard one. It is explained (quickly) here: https://github.com/cincheo/jsweet/wiki.

**Comment by GegeFR** [comment]
Hi,

That seems to be quite a smart way to do it ! Does it allows you to drop all the bytecode manipulations ? 

Questions I have would be in the case of using multiple (2 or more) JQuery (or other) plugins : 
- Naming of classes and packages : would we have to use the FQN each time ? (There are actually multiple "JQuery" classes nad only one import)
- Would the $mixin() method result only hold the api to one plugin at a given time (have to do a different call to $mixin for each plugin we might use) ?

Those are not really issues, but points I could think of (there might be solutions), your idea is already a very good improvement :-)

**Comment by lgrignon** [comment]
Hello GegeFR,

quick answers to your questions:

- The JQuery "main" declaration class and the mixins won't be in the same candy, hence not the same root package, but with the same simple name, like you said. Therefore it would be necessary to get the mixin using de FQN, resulting in a pretty verbose code.
We could try to generate a more expressive / contextual class name, but experience suggests that those kind of automatically generated names aren't that appropriate. I can't see any better option for now.
-  The $mixin() method "returns" an instance of the requested plugin which class is given so yes, one call to $mixin() for each plugin developer wants to use. Anyway the call will transpile to nothing since in TypeScript, the .d.ts merge is automatic (`$("#pouet").$mixin(def.jqueryui.JQuery.class).accordion()` will transpile to `$("#pouet").accordion()`). Do you think of anything different?
- **Additional question** : @renaudpawlak how are we going to handle StringTypes? Which still requires class merging.

Thanks for your feedbacks ;)

**Comment by GegeFR** [comment]
Seems good.
Think it would be possible to do something like thi ?
```
T api = base.$mixin(Class<T>);
api.apiMethod();
```

**Comment by lgrignon** [comment]
Indeed, we could even have a no arg method, with induced typing, good idea, thanks! 

```java
T mixin = base.$mixin();
mixin.addedMethod();
```
with
```java
<T extends jsweet.lang.Object> T $mixin();
```

**Comment by renaudpawlak** [comment]
About the name of the mixin classes, nothing will prevent the API developer to name the mixin with a different name. Actually, that would be my first choice for a manually developed API. For example:

``($("#pouet").$mixin(JQueryUI.class).accordion()``

However, as Louis says, it might not be that simple to find a good naming convention for automatically generated APIs, and we might want to rely on FQN...

It is of course possible to store the mixin in a temporary variable for better code readability.

With the ``$mixin(class)`` API, you will be able to access one mixin at a time. However, it should be possible to call the ``$mixin(class)`` method again, even on a mixin. For example:

``($("#pouet").$mixin(JQueryUI.class).$mixin(JQueryDataTable.class)``

It could be useful to allow this when mixins use the "fluent interface" idiom.

Not sure about the ``<T extends jsweet.lang.Object> T $mixin();`` prototype. It is too much "black magic" and could be misunderstood by programmers.

**Comment by renaudpawlak** [comment]
@lgrignon about string types: we have to stop relying on class merging too. It is already possible to declare string types anywhere with JSweet (see #36). I am not sure yet about how to organize these. Most probably, one ``StringTypes`` class per candy...

**Comment by lgrignon** [comment]
Yes, with this simpler mixin model, we could indeed have a StringTypes class in the def.candyname package! It will be pretty straightforward.

Nice improvement incoming :)
