### ISSUE TITLE
JAXB support

### ISSUE THREAD

**Issue by stiv-yakovenko** [cincheo/jsweet#164]
import javax.xml.bind.JAXBContext;

gives ERROR: cannot find name 'javax' at C:\Users\steve\Dropbox\Projects\jsweet\jsweet-quickstart\src\main\java\com\mkyong\core\JAXBExample.java(4)

how can i fix it? 
Thanx

**Comment by renaudpawlak** [comment]
Hi @stiv-yakovenko.

JSweet currently supports a subset for Java APIs. It is work in progress. Currently the supported APIs are in the J4TS project, but I am about to split it in many sub-projects in the J4TS organization (https://github.com/j4ts).

JAXB is not part of the supported APIs right now. The only way to fix your problem would be to add support for it. Two possibilities:

1. You take an existing Java implementation of JAXB and you transpile it with JSweet.
2. You implement the JAXB API with JSweet (using existing JavaScript libs).
