### ISSUE TITLE
super() call in TS is misplaced error

### ISSUE THREAD

**Issue by ostryhub** [cincheo/jsweet#166]
Hi, first of all thanks for JSweet, its really nice!
Also I'am getting the error described below when transpiling my code.
I distilled the code to the minimal possible case, hope it helps !
Removing the variadic args constructor is what helped me to get rid of this error as a quick workaround.

2016-10-03 20:36:43.043 INFO  JSweetTranspiler:1047 - bundle.ts(6654,9): error TS2376: A 'super' call must be the first statement in the constructor when a class contains initialized properties or has parameter properties.
ERROR: a 'super' call must be the first statement in the constructor when a class contains initialized properties or has parameter properties at bundle.ts(6654)

`import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class URGroup extends UndoRedo 
{
    private final List<UndoRedo> _urs = new ArrayList<>();

    public URGroup(List<UndoRedo> urs)
    {
        this._urs.addAll(urs);
    }

	public URGroup(UndoRedo... urs)
	{
	   this._urs.addAll(Arrays.asList(urs));
	}

    @Override
    public void undo() 
    {
        for (int i = _urs.size() - 1; i >= 0; --i) 
        {
            UndoRedo ur = _urs.get(i);
            ur.undo();
        }
    }

    @Override
    public void redo() 
    {
        for (UndoRedo ur : _urs) 
        {
            ur.redo();
        }
    }

    @Override
    public void destroy()
    {
    }
}
abstract class UndoRedo 
{
	public abstract void redo();
	public abstract void undo();
	public abstract void destroy();
}`

TS output for this class:

`namespace com.igrek.jetty.scenes.undoredo {
    export class URGroup extends com.igrek.jetty.scenes.undoredo.UndoRedo {
        private _urs : java.util.List<com.igrek.jetty.scenes.undoredo.UndoRedo> = new java.util.ArrayList<any>();

        public constructor(urs? : any) {
            if(((urs != null && urs["__interfaces"] != null && urs["__interfaces"].indexOf("java.util.List") >= 0) || urs === null)) {
                super();
                (() => {
                    this._urs.addAll(urs);
                })();
            } else if(((urs != null && urs instanceof Array) || urs === null)) {
                super();
                (() => {
                    this._urs.addAll(java.util.Arrays.asList<any>(urs));
                })();
            } else throw new Error('invalid overload');
        }

        public undo() {
            for(var i : number = this._urs.size() - 1; i >= 0; --i) {
                var ur : com.igrek.jetty.scenes.undoredo.UndoRedo = this._urs.get(i);
                ur.undo();
            }
        }

        public redo() {
            for(var index223=this._urs.iterator();index223.hasNext();) {
                var ur = index223.next();
                {
                    ur.redo();
                }
            }
        }

        public destroy() {
        }
    }
    URGroup["__classname"] = "com.igrek.jetty.scenes.undoredo.URGroup";
}`

**Comment by renaudpawlak** [comment]
Thanks @ostryhub. I know this bug indeed. The constraint is the following: when you have constructor overloading, you cannot have field initializers in the class. The fix is quite easy and I will do it ASAP.

In your case, I am afraid that this bug hides another problem: I remember also that constructor overloading with varargs does not work properly. So, you will have issue with this too. In general, overloading has limitations in JSweet, because JSweet is not exactly Java. So it is a matter of choices about what is worth being supported and what is not. When we decide that some case is not supported, then JSweet should raise a sound error at compile time.
