### ISSUE TITLE
Variables with same names but different scopes collision when method overload is present.

### ISSUE THREAD

**Issue by ostryhub** [cincheo/jsweet#167]
Hi, one more bug I found during my use of jsweet.

The issue: Two variables with same names collides when there is a foo method overload present. Remove public void foo() and everything works ok.

2016-10-03 21:13:59.059 INFO  JSweetTranspiler:1047 - bundle.ts(407,25): error TS2403: Subsequent variable declarations must have the same type.  Variable 'item' must be of type 'any', but here has type 'Item'.
ERROR: subsequent variable declarations must have the same type.  Variable 'item' must be of type 'any', but here has type 'Item' at /Users/Rafal/Projects/jetjsgamestudio/JETGraphicsJS/src/main/java/com/igrek/jetty/graphics/Paint.java(6)

Also location of the error in java code is totally missed:
(the /Users/Rafal/Projects/jetjsgamestudio/JETGraphicsJS/src/main/java/com/igrek/jetty/graphics/Paint.java(6))

```java
import java.util.List;

public class LocalVariablesNameCollision
{
    public void foo()
    {
    }

    public void foo(List<Item> items)
    {
        for (Item item : items)
        {
        }

        Item item = items.get(0);
    }
}

class Item {}
```

TS generated code:
```TypeScript
/* Generated from Java with JSweet 1.2.0-SNAPSHOT - http://www.jsweet.org */
namespace com.igrek.jetty.graphics {
    export class LocalVariablesNameCollision {
        public foo$() {
        }

        public foo(items? : any) : any {
            if(((items != null && items["__interfaces"] != null && items["__interfaces"].indexOf("java.util.List") >= 0) || items === null)) {
                return <any>(() => {
                    for(var index121=items.iterator();index121.hasNext();) {
                        var item = index121.next();
                        {
                        }
                    }
                    var item : com.igrek.jetty.graphics.Item = items.get(0);
                })();
            } else if(items === undefined) {
                return <any>this.foo$();
            } else throw new Error('invalid overload');
        }
    }
    LocalVariablesNameCollision["__classname"] = "com.igrek.jetty.graphics.LocalVariablesNameCollision";


    export class Item {    }
    Item["__classname"] = "com.igrek.jetty.graphics.Item";

}
```

**Comment by renaudpawlak** [comment]
Looks like a tricky one (did not know it). I have to test it first.

**Comment by renaudpawlak** [comment]
Fixed thanks to using `let` over `var`.
