### ISSUE TITLE
IntelliJ plugin?

### ISSUE THREAD

**Issue by mokross** [cincheo/jsweet#17]
Is a plugin for IntelliJ on the roadmap? Would be great!

**Comment by renaudpawlak** [comment]
Check out the wiki: https://github.com/cincheo/jsweet/wiki
It is part of the potential subprojects for now, but it is actually a must. So I will create a more specific roadmap. Contributions are welcome.

**Comment by renaudpawlak** [comment]
The maven plugin now has a 'watch' option that makes it quite convenient and it is IDE independent. Plus, the mixin system will be changed soon, also making the need of a plugin less crucial. That said, contributions are still welcome ;)
