### ISSUE TITLE
generate let over var

### ISSUE THREAD

**Issue by nbransby** [cincheo/jsweet#171]
Is there a way to get the compiler to generate let declarations for local variables instead of var? 

I believe let declarations behave more like java variables?

**Comment by renaudpawlak** [comment]
@nbransby thank you for this excellent suggestion. You are right. The scope of variables declared with ``let`` is similar to Java (on contrary to ``var``). It would solve #167. As a consequence, ``let`` will become the default in JSweet... 

We could add a ``@Var`` annotation to force a variable to be declared with the ``var`` keyword but actually I am not even sure it would be useful...
