### ISSUE TITLE
Could not find artifact org.jsweet:jsweet-maven-plugin:jar:1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/jsweet#18]
_From @tdebroc on December 22, 2015 9:4_

I have a maven Build Failure:
`
[ERROR] Plugin org.jsweet:jsweet-maven-plugin:1.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.jsweet:jsweet-maven-plugin:jar:1.0.0-SNAPSHOT
`

_Copied from original issue: cincheo/jsweet-examples#12_

**Comment by renaudpawlak** [comment]
Was it when building the jsweet-quickstart project or when building the jsweet-examples? There was a problem in the pom.xml of the jsweet-quickstart project that would have led to this error. It is fixed now though.

**Comment by tdebroc** [comment]
Hey Renaud, Thanks for quick answer !
Works like a charm now :-)
