### ISSUE TITLE
Using a variable name different from "args" in the method "main" of a class, causes an error.

### ISSUE THREAD

**Issue by negora** [cincheo/jsweet#184]
I like using full words for the names of my variables, instead of acronyms. If, in the method "main" of a class, I use the variable name "arguments" instead of "args", the transpilation fails. I'm referring to the variable of type String[] that contains all the arguments passed to the method. In Java, we are free to use any name for that variable. In my opinion, this shouldn't cause an error.

I'm starting to explore the possibilities of JSweet and, so far, I'm loving it. Thank you for creating this project ;) .

**Comment by renaudpawlak** [comment]
I have just fix it. Believe it or not, but ``arguments`` is a reserved name in TypeScript, so it cannot be used as a local variable name (you can try any other name and it will work in a main method). I have added ``arguments`` to the list of names that JSweet automatically rewrite to avoid keyword issues. Thanks for reporting!

**Comment by negora** [comment]
Oh, I had no idea. Thank you for your fast reaction ;) .
