### ISSUE TITLE
Combining switch + enum + amd modules may cause errors.

### ISSUE THREAD

**Issue by negora** [cincheo/jsweet#186]
I've seen that writing a `switch` block with `enums` in the `case` branches, causes errors if these 2 conditions are met:

1. We compile the modules with the `amd` format.

2. The `enum` is in the same package/module that the class that uses it.

To reproduce the error, you only have to clone the "JSweet quick start" project and follow these steps:

1. Configure the plug-in `jsweet-maven-plugin` so that it compiles to `amd` modules:

````xml
  <configuration>
    ...
    <module>amd</module>
  </configuration>
````

2. Add an `enum` like this one to the package `quickstart`:

````java
package quickstart;

public enum Color {
  RED,
  GREEN,
  BLUE;
}
````

3. In the method `main` of the class `quickstart.QuickStart`, write the following block:

````java
Color color = Color.RED;
switch (color) {
  case RED:
    break;
  case GREEN:
    break;
  case BLUE:
    break;
}
````

When building the project, it will throw the following error:

> 2016-11-14 12:08:53.053 DEBUG ProcessUtil:178 - run command: /home/negora/.jsweet-node_modules/bin/tsc --target ES3 --module amd --rootDir /home/negora/Projects/jsweet-quickstart/target/ts --outDir /home/negora/Projects/jsweet-quickstart/target/js .tsc-rootfile.ts quickstart/module.ts module.ts ../../.jsweet/candies/typings/src/typings/jquery/jquery.d.ts ../../.jsweet/candies/typings/src/typings/sprintf-js/sprintf-js.d.ts ../../.jsweet/candies/typings/src/typings/j4ts/0.2.0-SNAPSHOT/bundle.d.ts ../../.jsweet/candies/typings/src/typings/j4ts/0.2.0-SNAPSHOT/.tsc-rootfile.d.ts
> 2016-11-14 12:08:54.054 INFO  JSweetTranspiler:1081 - quickstart/module.ts(26,14): error TS2304: Cannot find name 'quickstart'.
> ERROR: cannot find name 'quickstart' at /home/negora/Projects/jsweet-quickstart/src/main/java/quickstart/QuickStart.java(31)
> 2016-11-14 12:08:54.054 INFO  JSweetTranspiler:1081 - quickstart/module.ts(28,14): error TS2304: Cannot find name 'quickstart'.
> ERROR: cannot find name 'quickstart' at /home/negora/Projects/jsweet-quickstart/src/main/java/quickstart/QuickStart.java(33)
> 2016-11-14 12:08:54.054 INFO  JSweetTranspiler:1081 - quickstart/module.ts(30,14): error TS2304: Cannot find name 'quickstart'.
> ERROR: cannot find name 'quickstart' at quickstart/module.ts(30)

I've inspected the generated `.ts` file and I have seen this block:

````typescript
switch((color)) {
  case quickstart.Color.RED:
  break;
  case quickstart.Color.GREEN:
  break;
  case quickstart.Color.BLUE:
  break;
}
````

I've replaced it with this one:

````typescript
switch((color)) {
  case Color.RED:
  break;
  case Color.GREEN:
  break;
  case Color.BLUE:
  break;
}
````

And then, I've run the TypeScript compiler by hand, in the directory where the `.ts` files are generated. It has compiled fine.

So I guess that, for this specific case, JSweet would have to generate `case` branches that don't use the fully qualified name of the `enum`, but the short one instead.

**Comment by renaudpawlak** [comment]
Thanks for this very complete bug report. It is somehow related to #173 and how JSweet deals with fully qualified names. Your input will help when tackling this problem in a general way.

**Comment by negora** [comment]
Thanks for your fast reaction!
