### ISSUE TITLE
Inner classes get transpiled to namespaces without declare

### ISSUE THREAD

**Issue by Parakoopa** [cincheo/jsweet#187]
Version: 1.2.0 Snapshot from October

Hi,
I have the following class (auto-converted from the web tool):
```java
/** This is an automatically generated object type (see the source definition). */
public class CONTROLLER_STRUCTURES extends jsweet.lang.Object {
    native public static $get $getStatic(String structure);
    /** This is an automatically generated object type (see the source definition). */
    @jsweet.lang.ObjectType
    public static class $get extends jsweet.lang.Object {
        native public java.lang.Double $get(double level);
    }
}
```
This get's converted like this:
```javascript
/* Generated from Java with JSweet 1.2.0-SNAPSHOT - http://www.jsweet.org */
/**
 * This is an automatically generated object type (see the source definition).
 */
declare class CONTROLLER_STRUCTURES {
    public static $getStatic(structure : string) : any;
}

namespace CONTROLLER_STRUCTURES {

    
}
```

And then during the transpiling the following error get's shown:
```
ERROR: a 'declare' modifier is required for a top level declaration in a .d.ts file at ...
```

As far as I know, the namespace has to be prefixed with a "declare". Why does this happen and does that affect anybody else?

**Comment by Parakoopa** [comment]
This is compiled via "definitions": true with the official maven plugin.

**Comment by renaudpawlak** [comment]
Ok. I see the problem. It should be easy to fix. As a temporary workaround, you may want to try to remove the ``$get`` object type and return an ``Object`` instead...

**Comment by Parakoopa** [comment]
I would do that, sadly I just picked an easy example from the API, there are much more complicated cases with inner classes. Is there an other way of fixing this without breaking the API (eg. moving the inner classes somewhere else)?

 But good to hear you already know a fix :)

**Comment by renaudpawlak** [comment]
Please let me know if it works (you might find other issues with definitions generations because this feature is relatively new). Thanks for your help!

**Comment by Parakoopa** [comment]
This works, thanks!
