### ISSUE TITLE
Can't run JSweet in Eclipse 4.6.1

### ISSUE THREAD

**Issue by rickgittest** [cincheo/jsweet#189]
I am using Eclipse 4.6.1 on Linux Mint 18 with the JSweet 0.9.4.201611040322 Eclipse plugin installed.

I created a Java test project to check out JSweet, created a simple Java source file that I would like translated, and enabled the JSweet Builder for the project. I get the following error:

`cannot find Node.js: install first and make sure that the 'node' command is in your execution path`

I have node 6.9.0 installed and it is on my system PATH as:

`/home/rick/.nvm/versions/node/v6.9.0/bin`

Am I missing something or is this a bug akin to what was reported for OSX last year in[ this post](https://github.com/cincheo/jsweet/issues/19).

Thanks in advance.

Rick

**Comment by renaudpawlak** [comment]
With some OS and Eclipse installations, it seems that the system PATH variable is not accessible to Eclipse. You might want to check this SO thread: http://stackoverflow.com/questions/7048216/environment-variables-in-eclipse

**Comment by rickgittest** [comment]
@renaudpawlak Thank you! I was able to get it to work by adding the path, which in my case is "/home/rick/.nvm/versions/node/v6.9.0/bin", to the PATH variable in /etc/environment. I did have to reboot for eclipse to pick it up.
