### ISSUE TITLE
Eclipse Plugin + OSX :  cannot find Node.js

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/jsweet#19]
_From @tdebroc on December 22, 2015 9:2_

I have node js in my path in my terminal but Eclipse can't find it:
`
cannot find Node.js: install first and make sure that the 'node' command is in your execution path	jsweet-examples		Unknown	JSweet Problem
`

_Copied from original issue: cincheo/jsweet-examples#11_

**Comment by renaudpawlak** [comment]
Make sure that:
1. even when you close the terminal and restart it, node and npm are still in your path
2. you restart Eclipse too so that the path is up-to-date for Eclipse
Keep me posted

**Comment by tdebroc** [comment]
I had verified 1 and 2, they were ok.
It seems Eclipse doesn't find my environnement path, don't know why ...

**Comment by renaudpawlak** [comment]
Would you mind checking the content of "Window > Show view > Error log" and send me the content of it after a clean project?

I will try to reproduce the issue. Is it happening on the jsweet-examples project? Which version of Eclipse are you using?

**Comment by renaudpawlak** [comment]
I forgot to ask: on what OS are you running Eclipse?

**Comment by tdebroc** [comment]
Yes It's in jsweet-examples example,
Eclipse Mars 4.5.1 on OSX 10.10.4

Here it's logs as you asked (filtered for classpath and paths):

!MESSAGE Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
!MESSAGE JSweet: full build...
!MESSAGE source dirs: [/jsweet-examples/src/test/java, /jsweet-examples/src/main/java]
!MESSAGE compiling with classpath: {{MY CLASSPATH}}
!MESSAGE compiling [{{MY PATH}}/git/jsweet-quickstart/src/main/java/quickstart/QuickStart.java]
jsweet.lang.Globals.*;jsweet.util.Globals.*;jsweet.dom.Globals.*;def.jquery.Globals.*;def.underscore.Globals.*
!MESSAGE Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!

**Comment by renaudpawlak** [comment]
There is a trick to get access to the actual path variable under Mac OSX...
http://superuser.com/questions/28344/path-env-variable-on-mac-os-x-and-or-eclipse

**Comment by renaudpawlak** [comment]
Note that this is more or less a bug because the plugin should be able to work without have the users to perform complex conf to make it work. I plan to get a Mac to make all this smoother for Mac users in future developments.

**Comment by renaudpawlak** [comment]
It should be fixed now. (I had to get a Mac to fix it ;))
Just update the Eclipse plugin and it should work...

**Comment by tdebroc** [comment]
Indeed, I just tried, works perfectly thanks !
