### ISSUE TITLE
Making a bundle breaks the dependencies order.

### ISSUE THREAD

**Issue by negora** [cincheo/jsweet#190]
I believe that it didn't happen before. Yesterday, my builds started to fail at runtime. I checked the generated JavaScript and it turned out that the classes weren't in the right order. There was a class that was creating an instance of another class that still hadn't been declared. I'm not sure, but, Could it be related to the resolution of the bugs #173 and #186? Just a guess.

To reproduce the error, create these classes:

```
a.Car
b.Wheel
```

`a` and `b` are the names of the packages. The code of the classes is this:

```java
package a;
import b.Wheel;

public class Car {

	public static void main (String[] args) {
		Wheel wheel = new Wheel ();
	}

}
```

```java
package b;

public class Wheel {
}
```

This will transpile the classes in the right order: `b.Wheel` first, `a.Car` after. However, if we switch the packages of the classes like this:

```
a.Wheel
b.Car
```

This will transpile the classes in the **wrong order**: `b.Car` first, `a.Wheel` after. And this will make the browser (Firefox in this case) throw this error: `TypeError: a is undefined`.

I don't know how JSweet works internally, but it seems that the alphabetical order of the package has some influence in the order in which the classes are transpiled. At least, after certain update of JSweet. I believe that it didn't fail before.

By the way, I'm referring to the option `bundle`. I'm using Maven and editing that option from the `pom.xml` file.

Thanks.

**Comment by renaudpawlak** [comment]
Well, JSweet's bundle option do some reference analysis on the Java code and applies a partial order sort so that classes are always declared in the right order (except for some rare cases when the classes belong to the same file, but that's not the case here). So it might be a regression due to latest commit (although so far I am quite surprise it could have happened).

I will try to reproduce and analyse ASAP (by Monday).

Thanks for reporting!

**Comment by renaudpawlak** [comment]
Ok. It seems that this commit is to blame: https://github.com/cincheo/jsweet/commit/3f46fb5cf18190b8cea8309f2380a27eddbfb775

It is a bad regression in the bundle mode. I will fix tomorrow (and add some tests to make sure that it does not happen again).
