### ISSUE TITLE
No slashes in mapping file

### ISSUE THREAD

**Issue by KramerTech** [cincheo/jsweet#191]
I'm using the eclipse plugin and whenever it builds the javascript files, map files get generated missing slashes. For example: "....srcmainjava/" instead of "../../src/main/java/" and so chrome can't find the file and I can't do anything to easily debug. Why's it doing this? What am I doing wrong?

**Comment by renaudpawlak** [comment]
I have tried to reproduce your problem with the Eclipse plugin but I had no success so far :( Works fine with me.

Could you please:
1. tell me if you are using the Eclipse plugin, or if you are running JSweet with the Maven ``generate-sources`` goal
2. if you are using the Eclipse plugin, check for updates in Eclipse, just to make sure that you have the latest version
3. give me your configuration (it might have to do with how you declare your input and output directories... or something else in your conf)... BTW, under what OS are you running Eclipse?
4. (optional) maybe try with Maven ``generate-source`` and see if you have the same issue

NOTE: the current source map generation process is limited and is currently being deprecated to be replaced with a more generic process that should work much better. So in the meantime, if you are not able to fix your issue, you might want to disable source maps and debug with the generated TypeScript source code, which is quite readable and understandable for a Java developer (that's of course a temporary solution).

**Comment by renaudpawlak** [comment]
should be ok with version 2...
