### ISSUE TITLE
Problem with overloading methods with Comparator argument

### ISSUE THREAD

**Issue by alievrenkut** [cincheo/jsweet#193]
Hi,

I started get a new issue after fixes done this week. Any method with same name but different arguments fails in production if one of the arguments is Comparator object.

You can easily test it using java.util.Arrays.sort() method. If I call it with an comparator object it gives 'invalid overload' error because Javascript version of comparator object does not have '__interfaces' property. If I looked inside the object. I can see '__interfaces' member in constructor member of object. Basically:
            object["__interfaces"] returns undefined.
            object.constructor["__interfaces"] returns correct value.

I am using bundle option.

Thanks,

**Comment by renaudpawlak** [comment]
Hi and thank you for reporting. There was indeed a change on this part lately....
I suspect in that case that it is just J4TS that is not up-to-date (my fault). I have re-deployed J4TS on Maven (and updated the dist bundle). So, you should be able to fix your issue just by building with Maven again (assuming that the J4TS artifact is updated AND that you use the latest snapshot - 0.3.0-SNAPSHOT).

In case if wouldn't work, it would help a lot to show me an example of code that fails...

Thanks!

**Comment by alievrenkut** [comment]
Thank you very much. Latest J4TS 0.3.0-SNAPSHOT fixed the issue.
