### ISSUE TITLE
Object.equals/hashCode

### ISSUE THREAD

**Issue by nbransby** [cincheo/jsweet#199]
I've noticed AbstractMap compares keys using Objects.equals which in turn uses === meaning classes implementing equals/hashCode won't have that logic respected.

What is the official status for java style equality support?

**Comment by lgrignon** [comment]
Last comments on this subject ties this question more to the j4ts project than the JSweet project:
https://github.com/cincheo/jsweet/issues/196#issuecomment-265930372

However, JSweet version 2 is in preparation and it could be something to discuss.

IMHO, JSweet should only bring the Java syntax to Javascript and J4TS should emulate the Java expected runtime behavior and bring it to JSweet. 
@renaudpawlak what do you think? JSweet already transpiles '==' to '===' and '==' to something like 'equals' (as far as I remember), this could be the next step!

**Comment by renaudpawlak** [comment]
So far, ``hashCode`` and ``equals`` functions are simply ignored by JSweet. It will be improved along the way with the new version (probably version 2.0). ASAP :) Let's keep this thread open for discussion just in case...

**Comment by renaudpawlak** [comment]
FI, this has been improved... to be tested again in the upcoming v2.

**Comment by lgrignon** [comment]
https://github.com/cincheo/jsweet/issues/555
