### ISSUE TITLE
A minor but annoying issue

### ISSUE THREAD

**Issue by lancemao** [cincheo/jsweet#208]
Imagine we have a Java class which contains static variable:
```
public class JSweet {
    public static boolean isAwesome = true; 
}
```
everything works awesome when qualified programmer writes the right code to access:
`JSweet.isAwesome;`

However, when junior programmer, say a young, hot, brainless girl who ignores compiler warning, writes:
`(new JSweee()).isAwesome;`

things fall into pieces as JSweet didn't define 'isAwesome' prototype for class 'JSweet'.
We suggest add prototype to make things work. If you think this is redundant, could you please provide a switch so that we can turn it on or off?

the fix should be simple, just add a prototype which in turns calls the static method JSweet already defined.

thanks in advance

**Comment by renaudpawlak** [comment]
But JSweet (1.2.0) raises a compilation error and refuses to generate any JavaScript when accessing the static field from an instance. So ``(new JSweeet()).isAwesome`` won't compile, which is safe. Personally, I always thought that Java was wrong to allow such expressions.

To avoid misuse, couldn't you just set up the IDE to prevent such access? In Eclipse, it is the first compilation option to appear: http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fpreferences%2Fjava%2Fcompiler%2Fref-preferences-errors-warnings.htm. So if you set "Non-static access to a static member" to "Error", no one will be able to make such mistake. You can also configure your compilation process by using the compilation options described here: http://stackoverflow.com/questions/11121885/java-checkstyle-rule-for-non-static-variable-access-to-static-variables.

Java being more permissive than JSweet, using a tool such as Checkstyle or PMD could also help enforcing rules that could prevent JSweet to break.

**Comment by lancemao** [comment]
sounds great, thanks

**Comment by renaudpawlak** [comment]
Ok. I am closing it then because JSweet does not require a change here (it would be out of scope). Thanks.
