### ISSUE TITLE
myClass is not a constructor

### ISSUE THREAD

**Issue by liaotianr** [cincheo/jsweet#210]
I have the following two Java classes:
     
       public class MyClass {
	
	public MyClass() {
		
	}
	
	public String getServerTime() {
		
		return "server time";
		
	}
	
    }

My quickstart class: 
    
       public class QuickStart {
	

	public static void main(String[] args) {
		
		MyClass myClass = new MyClass();

		$("#target").text(myClass.getServerTime());
		
	}
      } 

When I run the app I'm getting

Uncaught Exception:
TypeError: quickstart.MyClass is not a constructor
    at Function.QuickStart.main

**Comment by renaudpawlak** [comment]
I think you just need to add the JavaScript of your new class to your HTML page. The quickstart only adds the ``QuickStart.js`` file: https://github.com/cincheo/jsweet-quickstart/blob/master/webapp/index.html#L17. You need need to do a similar include for the generated ``MyClass.js``. Be aware that class order may be important.

If you want JSweet to take care of new classes and class ordering automatically, you should just enable the bundle option in the pom.xml (add ``<bundle>true</bundle>`` in the [configuration section](https://github.com/cincheo/jsweet-quickstart/blob/master/pom.xml#L64)). Then you only have one file to include (the generate bundle.js).

**Comment by liaotianr** [comment]
Thanks for your reply. I included the files in the wrong order. I should have included `MyClass.js` before `QuickStart.js`.

**Comment by renaudpawlak** [comment]
Yes. The bundle feature is very handy because you don't have to think about the order anymore :)
