### ISSUE TITLE
subsequent variable declarations must have the same type

### ISSUE THREAD

**Issue by liaotianr** [cincheo/jsweet#211]
The following java code will not compile because `myVal` is only visible within the for loops. That's normal behaviour.

		ArrayList<String> stringList = new ArrayList<String>();
		stringList.add("hi");
		
		for (String myVal:stringList) {
			// System.out.println(myVal);
		}
		
		ArrayList<Double> numberList = new ArrayList<Double>();
		numberList.add(1.00);
		
		for (Double myVal:numberList) {
			// System.out.println(car);
		}
		
		System.out.println(myVal); // Compiler doesn't like that

The following java code will compile but not transpile with JSweet, even it is valid java (but a bit dirty).

		ArrayList<String> stringList = new ArrayList<String>();
		stringList.add("hi");
		
		for (String myVal:stringList) {
			// System.out.println(myVal);
		}
		
		ArrayList<Double> numberList = new ArrayList<Double>();
		numberList.add(1.00);
		
		for (Double myVal:numberList) {
			// System.out.println(car);
		}

JSweet will throw this error message:
`ERROR: subsequent variable declarations must have the same type.  Variable 'myVal' must be of type 'string', but here has type 'number' at /Users/user/Documents/Code/jsweet-quickstart/src/main/java/quickstart/QuickStart.java(34)`

I'm not sure if this is really a bug or the error msg is thrown intentionally for my specific code.

**Comment by renaudpawlak** [comment]
Which version of JSweet are you using? This is supposed to be fixed in 1.2.0.

**Comment by liaotianr** [comment]
My jsweet-core candy is version 1.2.0.

**Comment by renaudpawlak** [comment]
Ok. But what counts here is the version of the transpiler, which is given by the version of the JSweet Maven plugin. You can easily make sure which one you are using by looking at the comment at the beginning of the generated code.
I have just updated the transpiler version in the sweet-quickstart project because it was still at version 1.1.1 (although the core was okay). Could you update too and  check again please?

**Comment by liaotianr** [comment]
My bundle.js says:
`"Generated from Java with JSweet 1.1.1 - http://www.jsweet.org";`

My other js files say:
`/* Generated from Java with JSweet 1.2.0 - http://www.jsweet.org */`

After updating jsweet-maven-plugin from 1.1.1 to 1.2.0 the error message does not occur anymore and everything works fine. :thumbsup:
