### ISSUE TITLE
jsweet maven plugin error : Reason: ERROR: Cannot override read-only parameter: candiesJsOut

### ISSUE THREAD

**Issue by totoweb69** [cincheo/jsweet#213]
I am trying to test the quickstart tutorial. But when running the command
mvn generate-sources 
to build the project as described in the tutorial page, I'm getting the following
error  
Error configuring: org.jsweet:jsweet-maven-plugin. Reason: ERROR: Cannot override read-only parameter: candiesJsOut in goal: jsweet:jsweet.
After looking to the maven plugin source code, it seems that this parameter, with a lot of others, has the
annotation @Readonly.
So, how can I get the quickstart example build using maven ?

**Comment by renaudpawlak** [comment]
Sorry for the delay. I don't have the issue. It's possible that with some configurations/versions of Maven, the @Readonly annotations have different behaviors... Would it be possible for you to:
- clone the jsweet-maven-plugin
- remove the annotations
- mvn install (jsweet-maven-plugin)
- try again and tell us if it works :)

Thanks in advance!

**Comment by totoweb69** [comment]
I was using maven 2 version. I removed the @Readonly annotation and then all things goes right. 
Switching to maven 3 version makes the plugin work well even with the @Readonly annotation.

**Comment by renaudpawlak** [comment]
Thank you for your help. Not sure if we should remove the @Readonly annotations or have a test on the Maven version then... any opinions?

**Comment by lgrignon** [comment]
AFAIK Maven 3 is out for at least 5 years and I don't think Maven 2 should be used anymore in any projects. We can close this issue without fear.
