### ISSUE TITLE
Extends declaration not generated as expected with the commonjs module setting

### ISSUE THREAD

**Issue by ZachBray** [cincheo/jsweet#214]
**Version: JSweet 2.0.0-SNAPSHOT**

To demonstrate, here is the code that is generated for `Timestamp` when using `commonjs` module setting to build `j4ts`:

```
/* Generated from Java with JSweet 2.0.0-SNAPSHOT - http://www.jsweet.org */
import { Date } from './Date'; 
import { Time } from './Time'; 
/**
 * An implementation of java.sql.Timestame. Derived from
 * http://java.sun.com/j2se/1.5.0/docs/api/java/sql/Timestamp.html. This is
 * basically just regular Date decorated with a nanoseconds field.
 */
export class Timestamp extends java.util.Date {
```

The key part being `extends java.util.Date` whereas I'd expect `extends Date`

Here are the settings provided to the mojo:

```
      <plugin>
        <groupId>org.jsweet</groupId>
        <artifactId>jsweet-maven-plugin</artifactId>
        <version>${jsweet.transpiler.version}</version>
        <configuration>
          <verbose>true</verbose>
          <declaration>true</declaration>
          <outDir>src/main/resources/META-INF/resources/webjars/${project.artifactId}/${project.version}</outDir>
          <module>commonjs</module>
        </configuration>
        <executions>
          <execution>
            <id>generate-js</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>jsweet</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

```

**Comment by ZachBray** [comment]
Sorry, I didn't provide much context above! 

We're building a library to share common bits of messaging behaviour in JS and Java. The library will eventually be consumed by projects that use Webpack for bundling.

We have a dependency on J4TS, as we use some of the Java collections like HashMap. We only depend on a fraction of the library though.

Typically in a Webpack build you supply an entrypoint or entrypoints and it will walk the dependency tree in order to determine what to bundle. If J4TS was exposed via commonjs modules (rather than as a bundle), Webpack would ignore the parts of it that are not (transitively) required by any of the entrypoints. The final application would then benefit from smaller bundles.

Of course it is possible to do some dead code elimination using Google's Closure compiler etc.; however, in our experience this doesn't integrate well with our tool-chain and can be a bit flakey.

> you are extending a JDK class expecting that everything will go fine

Actually, I was experimenting to see if I could build J4TS with commonjs modules enabled.

We don't intend to use 2.0.0-SNAPSHOT, I did the same experiment with 1.2.0 first but had neglected to collect information on the failure.

> JSweet expects the J4TS runtime and may not substitute supertypes (it expects the java.util.Date class to exist)

So the transpiler assumes that J4TS will be transpiled as a bundle?

**Comment by renaudpawlak** [comment]
Ok. Thanks for clarification.

I believe that J4TS should be packaged with various options, at least for classical WEB bundles, and commonjs modules. My fault, I have never tried to bundle J4TS with commonjs but maybe it would be the first problem to solve in your case... 

BTW, you might be interested in a new option with JSweet 2. It will allow to use simple JDK APIs without needing the J4TS runtime. For example it will transpile java.util.List as JS arrays and java.util.Map as regular JavaScript objects (would only work for string keys). Of course, you probably want to continue using J4TS if you want a more complete Java emulation. It depends on your use case. If you want to try it, I can tell you how to switch it on.

In any case, I don't have much time to work on J4TS and your issue these days. Maybe if you come with a specific issue when transpiling J4TS with modules?

**Comment by ZachBray** [comment]
BTW, I should have said at the very start, thank you for the fantastic library!

> I have never tried to bundle J4TS with commonjs but maybe it would be the first problem to solve in your case...

I'll see if I can get the time to get it working and raise a PR. For now we'll stick with old-school bundles.

> you might be interested in a new option with JSweet 2

This sounds interesting; however, I think we have object keys in our Maps etc. so we need the Java-like compatibility.

Thanks for your help.
