### ISSUE TITLE
NodeJS generation issue

### ISSUE THREAD

**Issue by PhilBon** [cincheo/jsweet#218]
JSweet is so sweet I decided to use it to transpile my Java code into NodeJS code. Thank for your huge work on that platform !!
Hence, my objective is to execute with node a simple test I write based on my transpiled code and J4TS. Unfortunatly, the execution leads to the following error:

```
var ArrayList = java.util.ArrayList;
ReferenceError: java is not defined
```

My pom is set with the following section dedicated to sweet:

  ```
    <artifactId>jsweet-maven-plugin</artifactId>
  		<version>1.2.0-SNAPSHOT</version>
        <configuration>
           <sourceMap>true</sourceMap>
           <module>commonjs</module>
           <bundle>false</bundle>
           <tsOnly>false</tsOnly>
           <verbose>false</verbose>
           <includes>
             <include>**/*.java</include>
           </includes>
           <excludes>
             <exclude>**/exclude/*.java</exclude>         
           </excludes>
           <outDir>target/js</outDir>
           <tsOut>target/ts</tsOut>
           <candiesJsOut>target/js</candiesJsOut>
           <targetVersion>ES5</targetVersion>
           <bundlesDirectory>target/js/</bundlesDirectory>
        </configuration>
...
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>j4ts</artifactId>
			<version>0.3.0-SNAPSHOT</version>
		</dependency>
```

As far as I can understand it, the issue seems to come from the importation section of the TS sources where the link to java-J4SJ module is incomplete. The TS generated by sweet is like:

```
import { JavaAbstractTest } from './JavaAbstractTest'; 
import { JavaAsserter } from './JavaAsserter'; 
import HashMap = java.util.HashMap;

import Map = java.util.Map;
```

Could please indicate how to fix the issue?

Thanks a lot.

**Comment by lgrignon** [comment]
Hello, I am working on porting the JSweet node example to version 2:
https://github.com/lgrignon/jsweet-node-example/milestone/1

This example will be included in the official JSweet repository at the end, but I will keep you informed about the evolution on this issue.

So far, I have regenerated successfully the node candy, but not tried it in a real program, that's my next step, along with generating successfully the express candy :)

**Comment by lgrignon** [comment]
My bad, I thought your issue was about node.js and recent candies version but it is more about using j4ts with modules.

Anyway, Node.js examples with JSweet 2 are now available:
https://github.com/lgrignon/jsweet-node-example-simple-http
https://github.com/lgrignon/jsweet-node-example-fs
https://github.com/lgrignon/jsweet-node-example

Maybe you should open this issue on the https://github.com/j4ts/j4ts repository?

**Comment by PhilBon** [comment]
Hello Louis,

Thanks for your support of this issue. As I was in a hurry to provide a
prototype around JSweet, I found a temporary solution as to embed j4ts and
my code as a single library, omitting the importation instructions. As soon
as I will have to improve the prototype, I will have a look on your new
node.js example around JSweet 2.



2017-02-16 8:52 GMT+01:00 Louis Grignon <notifications@github.com>:
