### ISSUE TITLE
Java do-while statement without braces fails to generate

### ISSUE THREAD

**Issue by Displee** [cincheo/jsweet#221]
Examine the following piece of plain Java code:

```
package org.jsweet;
public class HelloWorld {
	public static void main(String[] args) {
		int[] is = new int[10];
		int i = 0;
		do is[i++] = is[i] + 1;
		while (i < 10);
	}
	
}

```

It fails to generate the typescript and javascript for this code.

But if I use braces in the while-do statement, like this:

```
do {
is[i++] = is[i] + 1;
} while (i < 10);
```

it works.

However javascript supports it without braces.

**Comment by renaudpawlak** [comment]
That's a good one! Thanks! To be fixed ASAP as usual :)
