### ISSUE TITLE
Java character comparison with integer error

### ISSUE THREAD

**Issue by Displee** [cincheo/jsweet#222]
Examine the following piece of plain Java code:

```
package test;

import static jsweet.dom.Globals.console;

public class TestMain {

	public static void main(String[] args) {
		char test = "<test>".charAt(0);
		if (test == 60) {
			console.log("Matched!");
		} else {
			console.log("Did not match, char=" + test + ".");
		}
	}

}

```

In Java, we can compare characters with integers. When I try to generate this piece of code, I get the following error:
```
error TS2365: Operator '===' cannot be applied to types 'string' and 'number'.
ERROR: operator '===' cannot be applied to types 'string' and 'number' at TestMain.java(10)
```

This error occurs because the Java code that is being generated to Typescript recognizes the character variable as a string:

```
/* Generated from Java with JSweet 1.2.0 - http://www.jsweet.org */
namespace test {
    export class TestMain {
        public static main(args : string[]) {
            let test : string = "<test>".charAt(0);
            if(test === 60) {
                console.log("Matched!");
            } else {
                console.log("Did not match, char=" + test + ".");
            }
        }
    }
    TestMain["__class"] = "test.TestMain";

}
```

When I cast the character to an int in the if statement, like this:
`if ((int) test == 60) {`
It works, the generated Typescript code for this is:
```
/* Generated from Java with JSweet 1.2.0 - http://www.jsweet.org */
namespace test {
    export class TestMain {
        public static main(args : string[]) {
            let test : string = "<test>".charAt(0);
            if((test).charCodeAt(0) === 60) {
                console.log("Matched!");
            } else {
                console.log("Did not match, char=" + test + ".");
            }
        }
    }
    TestMain["__class"] = "test.TestMain";

}
```

Now this is interesting because when I cast it to an int, it will use Javascript's charCodeAt function.

Can you make it possible to support integer comparison with characters? So it will use the charCodeAt function when comparing a character with an integer instead of throwing the error?

Btw, I love jsweet.

**Comment by lgrignon** [comment]
Thanks for reporting. Which version of JSweet are you running? Using version 2.0.0-SNAPSHOT, trying to transpile the following code
```
char c = 'a';
		if (c == 60) {
			System.out.println("success");
		}
```
gives the following TypeScript, which is valid:
```
 let c : string = 'a';
            if((c => c.charCodeAt==null?<any>c:c.charCodeAt(0))(c) == 60) {
                console.info("success");
            }
```

But indeed, using version 1.2.1, I get the same error. 

Version 2 should be released in the near future, so I think it is not necessary to fix it i, 1.2.x branch. 
Could you please confirm and close?

Thanks again.

**Comment by Displee** [comment]
Well, maven doesn't recognize's snapshot 2.0.0 for me:

![0a27a006dac64ff588ae1ad5676c3c0c](https://cloud.githubusercontent.com/assets/12080880/22864578/42f0846a-f154-11e6-9d92-ea51b3f223a0.png)


But I guess it is alright, I hope I can use 2.0 ASAP.

**Comment by lgrignon** [comment]
OK. Check out the `pom.xml` of the following example, updated for JSweet 2. It uses some of the most popular candies:
https://github.com/lgrignon/jsweet-node-example
Well, at least core & jquery that you use apparently.

About j4ts, I think you can stick with the previous version, it should not be a problem.

Hope this will help you.
