### ISSUE TITLE
JSweet 1.2.1 generates unused imports

### ISSUE THREAD

**Issue by raiju** [cincheo/jsweet#228]
Imports seem to be generated without considering what is actually written to TS, creating unused imports. This can be problematic when the import is of a class that isn't available on the TS side (for example, hit this with jackson dependencies). The two situations that would systematically cause it to happen:

1. `throws` will import the exception, but the TS won't necessarily contain the exception itself
2. Usage in `@Erased` methods

Although there probably are more cases.

Repro: https://gist.github.com/raiju/b2342c727e876e7ebaa9f3f39acd5961

For now, working around this problem by running a tslint autofix over it after generating.

This was using the jsweet gradle plugin, with jsweet-transpiler v1.2.1.

If you think it's reasonably bounded I'd be happy to take a stab at fixing this, but would appreciate being pointed in the right direction.

**Comment by renaudpawlak** [comment]
This could be quite complicated too :)

It probably requires a global scan of the compilation units to know what imports are actually useful and which ones are not. The usual what to do it is to use the ``GlobalBeforeTranslationScanner`` class to analyse each compilation unit and store the useful information in the context (``JSweetContext``). Then, the ``Java2TypeScriptTranslator`` can use that information to avoid printing unused imports.

You can look at the ``Java2TypeScriptTranslator.visitImport(JCImport importDecl)`` method. It upcalls the adapter's ``needsImport`` method that is good to understand too. If this method returns null, it will not print the import. The default adapter is ``Java2TypeScriptAdapter``. 

I believe that you should have much less problems using JSweet v2. So I advise to switch to version 2 and write the tests that would show the bugs (follow the process explained in #227). Again, if you only contribute the test, that would already be useful.

**Comment by renaudpawlak** [comment]
Note that I think that this issue should not arise when using the ``bundle`` option or the ``module`` option because they deal with imports differently. Maybe the idea would be to deal with imports like the ``bundle`` option does...

**Comment by raiju** [comment]
Sorry for the late reply, just got back from vacation. Thanks for the very complete reply. We have however migrated away from using JSweet (we now use scala.js for the problem), so I'm afraid I won't be able to put in the time this would need.

**Comment by renaudpawlak** [comment]
Fixed :)
