### ISSUE TITLE
Generate typescript code with out namespace

### ISSUE THREAD

**Issue by preetham1290** [cincheo/jsweet#230]
Hi I was trying to generate typescript from dto. Every thing works fine but the package name is converted to  namespace which is not supported in angular 2. So i was thinking if i can omit generating name space as all of my dto is going to be in same package.
Eg- Input class is 
package com.spaneos.domain;
public class User {
	private String id;
	private String name;
	private String email;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
}
Generated output - 
namespace com.spaneos.domain {
    export class User {
        private id : string;
        private name : string;
        private email : string;
        public getId() : string {
            return this.id;
        }
        public setId(id : string) {
            this.id = id;
        }
        public getName() : string {
            return this.name;
        }
        public setName(name : string) {
            this.name = name;
        }
        public getEmail() : string {
            return this.email;
        }
        public setEmail(email : string) {
            this.email = email;
        }
        constructor() {
        }
    }
    User["__class"] = "com.spaneos.domain.User";
}
But required is - 
export class User {
        private id : string;
        private name : string;
        private email : string;
        public getId() : string {
            return this.id;
        }
        public setId(id : string) {
            this.id = id;
        }
        public getName() : string {
            return this.name;
        }
        public setName(name : string) {
            this.name = name;
        }
        public getEmail() : string {
            return this.email;
        }
        public setEmail(email : string) {
            this.email = email;
        }
        constructor() {
        }
    }

Is there some option or hack so that i can generate like above.

**Comment by renaudpawlak** [comment]
To remove the namespace, just annotate the package ``com.spaneos.domain`` with ``@Root``. Just create a ``package-info.java`` file in the package with the following content:

```java
@jsweet.lang.Root
package com.spaneos.domain;
```

If you have issues, you may want to switch to JSweet v2 because some bugs with ``@Root`` packages are fixed. Note that it is explained in the language specifications document you can find on the web site.

All that being said, I suspect that if you are working with Angular 2, you may just want to activate the ``module`` option, with the ``commonjs`` value. You don't need the ``@Root`` annotation in that case because each file becomes a module.

**Comment by renaudpawlak** [comment]
Can we close this issue?

**Comment by fredzqm** [comment]
I am having the same issue with Angular2. The namespace does not work well with angular2.
What do you mean by "you may just want to activate the module option, with the commonjs value. You don't need the @Root annotation in that case because each file becomes a module."?
Thanks!

**Comment by lgrignon** [comment]
@fredzqm do you use the maven plugin? If so, this configuration value resides in the `pom.xml` file, in the jsweet-maven-plugin configuration part.
Example:
```
<plugin>
				<groupId>org.jsweet</groupId>
				<artifactId>jsweet-maven-plugin</artifactId>
				<version>2.0.0-SNAPSHOT</version>
				<configuration>
					<verbose>true</verbose>
					<outDir>target/js</outDir>
					<targetVersion>ES3</targetVersion>
<module>commonjs</module>
				</configuration>
				<executions>
					<execution>
						<id>generate-js</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>jsweet</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

**Comment by fredzqm** [comment]
Thanks. That helps a lot!
