### ISSUE TITLE
Function Overload Issue

### ISSUE THREAD

**Issue by lancemao** [cincheo/jsweet#231]
Hey, 
It's been a long time, how is everything going?
We are doing great with JSweet. recently, we noticed one issue (could be our in-comprehensive understanding of JSweet tough)
Let's take an example in j4ts.js provided by JSweet:
````
var java;
(function (java) {
    var beans;
    (function (beans) {
        /**
         * General-purpose beans control methods. GWT only supports a limited subset of these methods. Only
         * the documented methods are available.
         */
        var Beans = (function () {
            function Beans() {
            }
            /**
             * @return <code>true</code> if we are running in the design time mode.
             */
            Beans.isDesignTime = function () {
                return false;
            };
            return Beans;
        }());
        beans.Beans = Beans;
        Beans["__class"] = "java.beans.Beans";
    })(beans = java.beans || (java.beans = {}));
})(java || (java = {}));
````

when this class is used in function overload, parameter will be checked like this
```
function f(param){
    if (param['__class'] === "java.beans.Beans") {doSomething}
}
```

however, param is an instance, not class, so param['__class'] is undefined.

currently, we fix this issue by adding a line in Bean constructor, like this:
`function Beans() {
    this.__class = "java.beans.Beans";
}`

We are wondering if there is a better way to handle this problem? 
thanks in advance

**Comment by renaudpawlak** [comment]
Hi! I am happy that you are doing fine with JSweet. JSweet 2 is in preparation and will bring many improvements, which I hope you will like.

What you report looks like a terrible bug! Everything happens like if param was of the type ``Class<Beans>`` and not ``Beans``... From what I understand, it does not happen with other classes? Are you sure that your param is well-typed with ``Bean``?

**Comment by lancemao** [comment]
It is Beans. 
We are looking forward to JSweet 2.

**Comment by lgrignon** [comment]
This is odd because in JSweet 1.2, overload parameters are differentiated using 
```
param instanceof com.package.Class
```
for class parameters and 
```
param["__interfaces"] != null && param["__interfaces"].indexOf("com.package.Interface") >= 0
```
for interface parameters.

It seems that the Beans code have been generated with a former version of JSweet.

j4ts will no longer be actively maintained with JSweet 2, so I suggest you try to regenerate j4ts using JSweet 1.2.0-SNAPSHOT.

If I find time this week, I will try myself to generate j4ts for version 2.0.0-SNAPHSOT

**Comment by lancemao** [comment]
Ah, thanks for this information.
Yes, class and interfaces are different.
I was trying to use Beans as an example (obviously, not a good one, sorry), we actually encountered this issue on HashMap, HashSet, well, all java.util interfaces and classes

Currently, we have fixed it by adding 
```
this.__class = "java.util.HashSet";
this.__interfaces = ["java.lang.Cloneable", "java.util.Collection", "java.util.Set", "java.lang.Iterable", "java.io.Serializable"];
```
in HashSet constructor

Let's see how j4ts.js works in JSweet 2

**Comment by renaudpawlak** [comment]
Ok. Now it really sounds like a mismatch between your release of J4TS and your release of JSweet. Are you sure you use JSweet 1.2? ``__class`` and ``__interface`` are defined on the constructors (not on the instances). If you are using the latest version, there is no need to define them in the instances... In any case, I have checked (and will check again) on JSweet 2, and I don't see any problem of that kind.

**Comment by lgrignon** [comment]
@lancemao any news on this issue?
