### ISSUE TITLE
java.lang.Math

### ISSUE THREAD

**Issue by norzak** [cincheo/jsweet#235]
It would be just fine for now to implement it using the jsweet supplied Math class, and for the methods which are hard to implement, you can just throw a "not implemented" exception. This is necessary to at least compile available code out there.

**Comment by renaudpawlak** [comment]
I am not sure about what is reported here, but FI, JSweet implements ``java.lang.Math`` with a set of compile-time macros (i.e. it substitutes the Java invocations to ``java.lang.Math`` with inlined JS code). You can check out the implementation here: https://github.com/cincheo/jsweet/blob/master/transpiler/src/main/java/org/jsweet/transpiler/extension/Java2TypeScriptAdapter.java#L930
Note that J4TS also provides a JSweet implementation of ``java.lang.Math`` which can be compiled to JS, but this implementation is not actually used by JSweet (in the default behavior).

**Comment by norzak** [comment]
java.lang.Math is missing in the J4TS sub directory. I was referring to that. I am not keen into hacking business before reading. Thank you for the information.

**Comment by renaudpawlak** [comment]
You are right. It was removed because JSweet supports it natively, but actually, it should not be removed and JSweet should use it when possible... That would be more consistent with J4TS.

**Comment by lgrignon** [comment]
@renaudpawlak Shouldn't it be a https://github.com/cincheo/j4ts issue?

**Comment by renaudpawlak** [comment]
@lgrignon It is both. J4TS should have an implementation of Math, and the Java2TypeScriptAdapter should use if when J4TS is in the classpath. This is a very minor issue for JSweet though.

**Comment by renaudpawlak** [comment]
Actually, looking at it closer, what happens is that the Math class is moved to https://github.com/j4ts/j4ts/blob/master/src/main/java/javaemul/internal/MathHelper.java. It is some sort of hack to make the mapping easier, but I don't think it is a good idea... Will try to fix in the next release.

**Comment by renaudpawlak** [comment]
Actually, we delegate to MathHelper because Math is in the java.lang package and would conflict with the JavaScript Math when omitting the package. So, even if it could probably be possible to do it differently, it would require to change the way JSweet generate code for accessing Math, which is quite out of scope of what we need to do currently. I will keep it open but will not resolve for the coming release.

**Comment by renaudpawlak** [comment]
Math support has been improved (again) in v2. Another more specific issue should be opened if necessary.
