### ISSUE TITLE
Interface not correctly set at instantiation of anonymous inner classes 

### ISSUE THREAD

**Issue by friedlhu** [cincheo/jsweet#239]
I  have the following Java code:
```
interface MyInterface {
	public void f();
}
public class Test {
	public void test() {
		MyInterface iface = new MyInterface() {
			@Override
			public void f() {
			}
		};
		if (iface instanceof MyInterface) {
			alert("Success");  // not called 
		}
	}
}

```
Problem: Though object ``iface`` is of type ``MyInterface``, expression ``iface instanceof MyInterface`` evaluates to ``False``. 
The corresponding transpiled JavaScript code is:
```
var Test = (function () {
    function Test() {
    }
    Test.prototype.test = function () {
        var iface = new Test.Test$0(this);
        if (iface != null && (iface["__interfaces"] != null && iface["__interfaces"].indexOf("MyInterface") >= 0 || iface.constructor != null && iface.constructor["__interfaces"] != null && iface.constructor["__interfaces"].indexOf("MyInterface") >= 0)) {
            alert("Success");
        }
    };
    return Test;
}());
Test["__class"] = "Test";
var Test;
(function (Test) {
    var Test$0 = (function () {
        function Test$0(__parent) {
            this.__parent = __parent;
        }
        Test$0.prototype.f = function () {
        };
        return Test$0;
    }());
    Test.Test$0 = Test$0;
})(Test || (Test = {}));
```
The problem is that interface ``MyInterface`` is never set in ``iface["__interfaces"]``. What is missing is a line  ```Test$0.prototype["__interfaces"] = ["MyInterface"]``` (or similar).

Current Workaround: Wrap interface by an abstract class and instantiate the abstract class (the interface is set correctly when instantiating abstract classes).

Observed in:
jsweet-core: version 6-SNAPSHOP
j4ts: version 0.4.0-SNAPSHOT

**Comment by lgrignon** [comment]
Which version of the transpiler (or maven plugin) are you using?

**Comment by friedlhu** [comment]
Problem observed with ``jsweet-maven-plugin`` version ``1.2.0``.

After some more tests:
- observed also with ``jsweet-maven-plugin`` version ``2.2.0-SNAPSHOT``.
- but not observed (i.e. working) with ``tjsweet-maven-plugin`` version ``1.1.0``.

Another observation: If interface is annotated by ``@Interface`` (sweet.lang.Interface) -> working as expected with all versions.

**Comment by lgrignon** [comment]
Sounds like a bug indeed, thanks!
I will take a look at it.

**Comment by lgrignon** [comment]
I added the missing unit tests to validate instanceof on interfaces, under several cases and did not notice any problem with the last JSweet 2.0.0-SNAPSHOT version. Please take a look at this commit:
https://github.com/cincheo/jsweet/commit/059b7c0cb5a7acc711290d24d51f91e1b1df7df4

The interesting part of the generated JavaScript is the following:
```javascript
var i1 = Object.defineProperty({}, '__interfaces', { configurable: true, value: ["source.structural.Interface1"] });
                var i2 = Object.defineProperty({}, '__interfaces', { configurable: true, value: ["source.structural.Interface1", "source.structural.Interface2"] });
                var i3 = Object.defineProperty({}, '__interfaces', { configurable: true, value: ["source.structural.Interface3"] });
                var i4 = Object.defineProperty({}, '__interfaces', { configurable: true, value: ["source.structural.Interface3", "source.structural.Interface4"] });

//....

if (!((i1 != null && (i1["__interfaces"] != null && i1["__interfaces"].indexOf("source.structural.Interface1") >= 0 || i1.constructor != null && i1.constructor["__interfaces"] != null && i1.constructor["__interfaces"].indexOf("source.structural.Interface1") >= 0))))
                    throw new Error("Assertion error line 37: assert i1 instanceof Interface1;");
                ;
                if (!((i2 != null && (i2["__interfaces"] != null && i2["__interfaces"].indexOf("source.structural.Interface2") >= 0 || i2.constructor != null && i2.constructor["__interfaces"] != null && i2.constructor["__interfaces"].indexOf("source.structural.Interface2") >= 0))))
                    throw new Error("Assertion error line 38: assert i2 instanceof Interface2;");
                ;
                if (!((i3 != null && (i3["__interfaces"] != null && i3["__interfaces"].indexOf("source.structural.Interface3") >= 0 || i3.constructor != null && i3.constructor["__interfaces"] != null && i3.constructor["__interfaces"].indexOf("source.structural.Interface3") >= 0))))
                    throw new Error("Assertion error line 39: assert i3 instanceof Interface3;");
                ;
                if (!((i4 != null && (i4["__interfaces"] != null && i4["__interfaces"].indexOf("source.structural.Interface4") >= 0 || i4.constructor != null && i4.constructor["__interfaces"] != null && i4.constructor["__interfaces"].indexOf("source.structural.Interface4") >= 0))))
                    throw new Error("Assertion error line 40: assert i4 instanceof Interface4;");
```

I don't understand why you do not get the same result but this bug might have been fix since this issue's creation.
Could you please try again, confirm that it works for you and close the issue if so.

**Comment by friedlhu** [comment]
Thank you for your analysis and the unit test which is working. 

However, not working when an interface gets instantiated that declares at least one method (except the interface is annotated explicitly by ``@Interface``). Can you extend the unit test to instantiate a non-empty interface?

**Comment by lgrignon** [comment]
Of course, I will, tonight if possible. Thanks for your feedback.
