### ISSUE TITLE
Latest development code output multiple class xxxx {} for each ts file

### ISSUE THREAD

**Issue by sadevelopment** [cincheo/jsweet#241]
We thought we'd try your latest code from as master to see if there was a fix for another issue we have found. The outputted ts file contain multiple class xxxx {} statements at the top of each ts file ...

**Comment by lgrignon** [comment]
Which version of JSweet are you running?
Could you please provide the original JSweet code leading to the bug you noticed and the unexpected js output.
Thank you.

**Comment by sadevelopment** [comment]
I am running the latest from master of JSweet, hocked up to the jsweet-gradle-plugin via command line. I have just switched to your 2.0.0-alpha1 version to see if that makes a difference. The outputted typescript is of the form:

`
class LoadCancelledEvent {}

class LoadCancelledEvent {}

class LoadCancelledEvent {}

class LoadCancelledEvent {}

class LoadCancelledEvent {}

class LoadCancelledEvent {}

class LoadCancelledEvent {}

namespace com.hambroperks.event {
    export class LoadCancelledEvent extends LoadEndedEvent {    }
    LoadCancelledEvent["__class"] = "com.hambroperks.event.LoadCancelledEvent";

}
`

**Comment by lgrignon** [comment]
Ok, thanks, and what is the original JSweet source please?

**Comment by renaudpawlak** [comment]
Yes, I am very curious of the code that could lead to such erratic behaviour (never seen before).
