### ISSUE TITLE
Comparison of byte and char results in error

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#243]
Doing something like this:

    byte[] data;
    ...
    if (data[2] == '\n') ...

results in the error:

    ERROR: operator '===' cannot be applied to types 'number' and 'string'

The fix appears to be to cast the right-hand side to `byte`. Is this something that jsweet could do so that no changes to the code are required?

Thanks again for your work on jsweet.

**Comment by renaudpawlak** [comment]
Could you double-check that it works on 2.0.0-SNAPSHOT?
Since you are translating existing Java code, you should really use the master only because many bugs were fixed since 1.2.1.

Thanks for all you feedback. This is really useful.

**Comment by renaudpawlak** [comment]
Umm. Actually, after further testing, it seems that the following is not valid any way: ``byte[] data = { 'a', '\n'};``. I have to fix it.

**Comment by chrismiddleton** [comment]
I am incredibly impressed with how quick you fixed all these related issues. You are awesome. Thank you!
