### ISSUE TITLE
Static property ends up on instance if no default value provided in Java

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#244]
It appears that in some situations, a static property ends up on instance if no default value provided in Java. Ex:

    class Foo {
        static boolean bar;
    }

It ended up generating an ERROR like this:

    ERROR: property 'bar' does not exist on type 'Foo'

and the generated JS was putting an instance declaration in the `constructor` function.

I verified that in my code when I added a default value of `= false` to that `bar` declaration, it stopped making it into an instance variable. However, I was unable to get a minimum working example in the live sandbox.

**Comment by renaudpawlak** [comment]
It could be related to #240. Make sure that you try it on version 2.0.0-SNAPSHOT (master) before reporting. 
Thanks for you help!!

**Comment by chrismiddleton** [comment]
This issue is fixed in the current 2.0.0-SNAPSHOT. Thank you! :)

**Comment by renaudpawlak** [comment]
Great! Thanks.
