### ISSUE TITLE
Support for other String constructors

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#250]
I have some code that tries to use the `String(byte[] ascii, int hibyte)` constructor.  Right now it gives this error:

    error TS2346: Supplied parameters do not match any signature of call target.

Would it be possible to support this constructor (and maybe the other String constructors)? This particular one is deprecated and a bit weird, so I get it if you think it's better to leave it out. I'm only filing this issue as it's another issue of compatibility of existing code, and the fewer of those that there are, the better the jsweet experience will be for everyone. (This is a low priority issue.)

For now I will be just removing this call and doing something else instead.

Thanks again for all your hard work.

**Comment by dasa** [comment]
I'd be nice to fix this error caused by `new String()`:

```console
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at com.sun.tools.javac.util.List.get(List.java:476)
at org.jsweet.transpiler.model.support.NewClassElementSupport.getArgument(NewClassElementSupport.java:65)
at org.jsweet.transpiler.extension.RemoveJavaDependenciesAdapter.substituteNewClass(RemoveJavaDependenciesAdapter.java:1393)
```

**Comment by renaudpawlak** [comment]
Empty constructor is now supported. Some other constructors are supported too (see the [tests](https://github.com/cincheo/jsweet/blob/master/transpiler/src/test/java/source/nativestructures/Strings.java)). Please re-open for requesting specific constructor support or report issues with current implementation.
