### ISSUE TITLE
Bitwise and on char results in wrong TS

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#251]
Thanks again for all your work on the char as number and string issue. I believe most of your changes have fixed things - I just do a `mvn install` to get the newest code from 2.0.0-SNAPSHOT right? - but I'm seeing a slightly different issue.

This code:

    c &= 0x7F;

where `c` is a `char` causes this TS:

    c = String.fromCharCode(c.charCodeAt(0) & 127.charCodeAt(0))

The `127` should not have a `.charCodeAt(0)` next to it. Seems like it is being treated as a `char` by the compiler since it is on the RHS of this `char`-modifying operation, but it should be left as a number in this context.

The TS error that results is this:

    INFO JSweetTranspiler:1262 - bundle.ts(6647,67): error TS1005: ',' expected

I've got my build down from 59 errors to 3 errors (yay!) and all three of them are this problem. The second involves a logical OR (`|`).

Interestingly, when I changed all three from a `x &= y` form to a `x = x & y` form, I got this error instead:

    ERROR: incompatible types: possible lossy conversion from int to char

Putting a `(char)` in front does not make that error go away. I think it's OK in Java. Running this sample through `javac` gives no error:

    class Test {
        public static void main (String[] args) {
            char x = 'a';
            x &= 0x20;
            System.out.println("Char: " + x);
        }
    }

**Comment by renaudpawlak** [comment]
Okay. 3 errors... Cool. I'll work on this new problem ASAP. Might be a regression or was always here.

**Comment by chrismiddleton** [comment]
I found a workaround for now. I replace this:

    x &= 0x20;

with this:

    x = (char) ((int) x & 0x20)
