### ISSUE TITLE
Same name in different packages causes type error in certain case

### ISSUE THREAD

**Issue by chrismiddleton** [cincheo/jsweet#255]
I have this code:

	package java.awt.event;

	import java.util.function.Function;
	import jsweet.dom.Event;
	import jsweet.dom.EventListener;

	public class BrowserEventListener {
		public String eventType;
		public EventListener func;
		public BrowserEventListener (String eventType, Function<Event,Boolean> theFunc) {
			this.eventType = eventType;
			this.func = new EventListener () {
				public void apply (Event e) {
					theFunc.apply(e);
				}
			};
		}
	}

which results in this error:

    ERROR output:48 - type '(e: Event) => void' is not assignable to type 'EventListener'
    - Types of parameters 'e' and 'evt' are incompatible.
    -   Type  'Event' is not assignable to type 'java.awt.Event'
    -      Property 'arg' is missing in type 'Event'

Unless I'm missing something, it looks like it's confusing java.awt.Event with jsweet.dom.Event. The TS output does not include package prefixes on those types. I also tried it by fully specifying the types instead of importing, but that didn't change the result.

I have an Event.java class in my java.awt package and an EventListener interface in my java.util package if that makes any difference.

**Comment by renaudpawlak** [comment]
This looks fixed in v2 (note: use the v2 API that uses `$apply()` for functional objects).
