### ISSUE TITLE
Add support for java.lang.String.length()

### ISSUE THREAD

**Issue by dasa** [cincheo/jsweet#26]
The Java String's `length` method should be transpiled to the JS `length` property.

**Comment by renaudpawlak** [comment]
Yes, I agree on this one for convenience... I was annoyed by this behavior lately.
Right now the workaround is:

import static jsweet.util.Globals.string;
[...]
string(myString).length;

Not very nice for sure, so I will add the support for version 1 RC1.

**Comment by renaudpawlak** [comment]
This should now work with the new jsweet-transpiler SNAPSHOT.

**Comment by renaudpawlak** [comment]
I am closing the issue. Tell me if it does not work.

**Comment by dasa** [comment]
It's working good! Thanks :+1:
