### ISSUE TITLE
on-the-fly js generation using servlet/embedded jetty?

### ISSUE THREAD

**Issue by jjYBdx4IL** [cincheo/jsweet#271]
Is this possible? I'd like to use that for development: browser refresh -> servlet checks if js needs to be re-created. Maybe even in production. I'm currently thinking about dropping GWT because it is too restrictive and makes too many problems whenever one wants to leave a trodden path.

**Comment by renaudpawlak** [comment]
Hi. We may want to make it more "mainstream" one day but currently, we just have a simple [HTTP/REST server](https://github.com/cincheo/jsweet-http-server) which is developed with [NanoHTTPD](https://github.com/NanoHttpd/nanohttpd). It is used to power the [JSweet sandbox](http://www.jsweet.org/jsweet-live-sandbox/).

**Comment by jjYBdx4IL** [comment]
I can probably code the server/servlet part on my own. The critical question is how fast is the transpile, ie. is it as fast/faster than GWT's development mode incremental compilation?

**Comment by jjYBdx4IL** [comment]
btw., I don't know your exact reasons for using NanoHTTPD, but here is an example how easy you can use embedded jetty:

https://github.com/jjYBdx4IL/java-evaluation/blob/master/src/test/java/twitter4j/GetUserPermissions.java

It's basically just setting a handler and implementing the handle method. I use it in unit tests all the time. It even auto-selects a free port if you give it a 0 port.

**Comment by renaudpawlak** [comment]
Yes, adapting the current NanoHTTPD implementation should be easy. We use NanoHTTPD for no specific reasons... I guess the fun of using a new thing was part of it, but the idea was also to keep it extremely light. I have been using this implementation for a long time in production and I have never hit any issues.

Regarding the perfs, I don't know the perfs of GWT's incremental compilation, so I cannot compare (I know a full build can be extremely slow, as I have already seen on a big project). In general JSweet by itself is fast enough to not bother with incremental compilation (see for example the jsweet:watch option of the Maven that implements hot transpilation). Actually, the current performance bottleneck of the JSweet transpilation process is having to run a Node.js process to run the TypeScript compiler (tsc). It is not extremely slow so I have not made this issue a priority so far, but it would be quite easy to use J2V8 to avoid starting a new process each time and I expect a big win. In the meantime I am pretty sure that the prefs should be enough for most use cases...

There is another potential issue (just in case). This implementation has been created for the sandbox, i.e. to compile just one piece of code (one file). So if you have several files in your project, you may need to adapt the implementation.
