### ISSUE TITLE
release version 1.2.1 references various jsweet snapshots

### ISSUE THREAD

**Issue by StormeHawke** [cincheo/jsweet#272]
My company uses a maven mirror to regulate dependencies and doesn't want to mirror the snapshot version of the jsweet repo for stability reasons.

Any chance of releasing a version that doesn't reference any snapshot versions?

**Comment by StormeHawke** [comment]
```
                <dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>jsweet-core</artifactId>
			<version>1.2.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>es6-promise</artifactId>
			<version>0.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>body-parser</artifactId>
			<version>0.0.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>

```
plus test dependencies which may or may not be a problem:
```

                <dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>node</artifactId>
			<version>4.0.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>errorhandler</artifactId>
			<version>0.0.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>socket.io</artifactId>
			<version>1.4.4-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>jquery</artifactId>
			<version>1.10.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>jqueryui</artifactId>
			<version>1.9.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>angular</artifactId>
			<version>1.4.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>angular-route</artifactId>
			<version>1.3.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>backbone</artifactId>
			<version>1.0.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>threejs--three</artifactId>
			<version>0.0.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>babylonjs--babylon</artifactId>
			<version>2.3.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>react-global</artifactId>
			<version>0.14.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
```

**Comment by renaudpawlak** [comment]
Hi @StormeHawke. Unless I am missing something, all the "test" dependencies are only used when testing/building the project and are not deployed when using the Maven artefact. So you can use JSweet and none of the snapshots will be deployed in you Maven repo. 

On the other hand,  I see that the "es6-promise" candy is not set as a test dependency, which is a mistake on our side. It should of course be like other test dependencies:

```xml
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>es6-promise</artifactId>
			<version>0.0.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
```

We need to fix the ``pom.xml`` and deploy it again (we should not do any release for just fixing the ``pom.xml``).  We'll do it ASAP.

**Comment by StormeHawke** [comment]
Note above the <test> scoped dependencies were a couple of other SNAPSHOT dependencies, including 

```
 <dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>jsweet-core</artifactId>
			<version>1.2.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>
```

and 


```
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>body-parser</artifactId>
			<version>0.0.0-SNAPSHOT</version>
			<scope>test</scope>
			<optional>true</optional>
		</dependency>

```
Note also that something, somewhere, is also trying to pull down org.jsweet:jsweet-core:5-SNAPSHOT.  This appears to only exist in the snapshots repository:

> [INFO] JSweet transpiler version 1.2.1 (build date: 2017-02-05 17:55:47)
> Downloading: http://purecloud.artifactoryonline.com/purecloud/inin-maven-mirror/org/jsweet/jsweet-core/5-SNAPSHOT/maven-metadata.xml
> Downloading: http://purecloud.artifactoryonline.com/purecloud/inin-maven-mirror/org/jsweet/jsweet-core/5-SNAPSHOT/jsweet-core-5-SNAPSHOT.pom
> [WARNING] Missing POM for org.jsweet:jsweet-core:jar:5-SNAPSHOT

I guess an easy way to reproduce/debug would be to set up a pom that only references the releases repo and try to transpile some stuff using the maven plugin (what I'm trying to do)

**Comment by StormeHawke** [comment]
There we go, figured out where `org.jsweet:jsweet-core:5-SNAPSHOT` is coming from.  Filed a related issue on j4ts: https://github.com/j4ts/j4ts/issues/15

This is blocking some development work for us since my company doesn't want to mirror the snapshot repo.  I'm not terribly familiar with overwriting non-snapshot releases - is it possible to re-release under 1.2.1 with the corrected poms or do you have to do a full release with a version bump to fix the problem?

**Comment by renaudpawlak** [comment]
You should now be able to use version 1.2.2 that fixes the problem of es6-promise dependency.

**Comment by StormeHawke** [comment]
Thank you!
