### ISSUE TITLE
Where do I find java.util.Properties?

### ISSUE THREAD

**Issue by coderextreme** [cincheo/jsweet#296]
X3DJSAIL.3.3.js:11476 installing applet onload hook
X3DJSAIL.3.3.js:30509 Uncaught TypeError: java.util.Properties is not a constructor
    at Function.BrowserFactory.__static_initializer_0 (X3DJSAIL.3.3.js:30509)
    at Function.BrowserFactory.__static_initialize (X3DJSAIL.3.3.js:30501)
    at Function.BrowserFactory.vrml_properties_$LI$ (X3DJSAIL.3.3.js:30506)
    at X3DJSAIL.3.3.js:420505
X3DJSAIL.3.3.js:11478 applet onload hook

https://raw.githubusercontent.com/coderextreme/JavaSceneAuthoringInterfaceLibrary/master/webapp/bundle.ts

https://raw.githubusercontent.com/coderextreme/JavaSceneAuthoringInterfaceLibrary/master/webapp/X3DJSAIL.3.3.js

https://github.com/coderextreme/JavaSceneAuthoringInterfaceLibrary/blob/master/webapp/index.html

Thanks!

John

**Comment by renaudpawlak** [comment]
Apparently ``java.util.Property`` is not supported yet.

- Solution 1. If you use J4TS (not recommended with JSweet v2), you should provide your own implementation (see the [java.util](https://github.com/j4ts/j4ts/tree/master/src/main/java/java/util) source code).
- Solution 2. Or with JSweet v2, you should extend the [RemoveJavaDependenciesAdapter](https://github.com/cincheo/jsweet/blob/master/transpiler/src/main/java/org/jsweet/transpiler/extension/RemoveJavaDependenciesAdapter.java), which substitutes Java API calls with JavaScript API.

I think that @lgrignon volunteered to give solution 2 a try :)

**Comment by lgrignon** [comment]
@coderextreme  java.util.Properties is now supported in JSweet 2 (via 5ea07b9e6e42d0c89ede045db473204c81742a0e), altough I think it won't be enough for you because I noticed you are using streams, which are not yet supported. 
@renaudpawlak should we provide something for stream API, I think it's beyond the transpiler's scope
