### ISSUE TITLE
Ionic integration

### ISSUE THREAD

**Issue by malaki12003** [cincheo/jsweet#297]
It makes jsweet a great  tool for mobile developer if  you incorporate it into ionic so that developers resale their app on ISO, Android and Windows Mobile. What is your plan about ionic?

**Comment by lgrignon** [comment]
Yes, you are perfectly right, JSweet pairs nicely with Ionic / Cordova. It's been a long time we use both together.
If you are looking for an example on how to do this, you could try the following:
1) The Ionic Client
https://github.com/lgrignon/jsweet-cordova-ionic-example
2) The Jax-rs server (you could just implement this part with any technology you like, such as node.js)
https://github.com/lgrignon/jsweet-jaxrs-server-example

We added those examples a long time ago so please tell me if something goes wrong, I will help you fix it.
