### ISSUE TITLE
@Module and definitions

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/jsweet#313]
Check if there is a bug [there](http://www.jsweet.org/forums/topic/what-should-i-expect-from-the-jsweet-lang-module-annotation/) and fix it.

**Comment by negora** [comment]
As I've mentioned in that thread of the forum, it seems to work fine with the 2.0.0-SNAPSHOT version of the plug-in :) . In the 1.2.2-SNAPSHOT version, however, the result isn't right. It doesn't create the necessary piece of code:

```typescript
declare module "mymodule" {
    export = mymodule;
}
```

Thank you!

**Comment by renaudpawlak** [comment]
Great! Thank you for your feedback. I have not started working on it, so everything is fine :)
I will not fix for 1.x version.
