### ISSUE TITLE
Import error when namespace contains a function with the same name

### ISSUE THREAD

**Issue by negora** [cincheo/jsweet#319]
I've found a problem similar to the one described at #318. But it's a little different. I'm using the 2.0.0-SNAPSHOT version of the Maven plug-in. And the consumer project is configured to generate AMD modules.

It happens with this structure:

```
def
  -> foo
    -> package-info.java
    -> foo
      -> Globals.java
      -> package-info.java
```

The file `def/foo/package-info.java` contains this:

```java
@jsweet.lang.Root
package def.foo;
```

The file `def/foo/foo/package-info.java` contains this:
```java
@jsweet.lang.Name (value = "foo")
@jsweet.lang.Module (value = "foo")
package def.foo.foo;
```

The `Globals.java` file contains this code:

```java
public final class Globals {
	public static native boolean foo ();
}
```

As you can see, it declares a method whose name, `foo`, matches the name of the package/namespace. The generated `bundle.d.ts` is this one, which is right:

```typescript
declare namespace foo {
    export function foo(): boolean;

}

declare namespace foo {}

declare module "foo" {
    export = foo;
}
```

But the result in the project that consumes this candy is wrong: the module is imported, but not the function:

```typescript
import foo = require("foo");
...
foo ();
```

In this case, `tsc` throws an error because it doesn't recognise the signature of the method. It's OK, because `foo` is not the function, but an alias of the module. The function is `foo.foo`.

I've done a test using the `@jsweet.lang.Name` and `@jsweet.lang.Module` annotations to change the name of the namespace and the module. I've renamed them from `foo` to `Foo`. But the result has been the same.

Later, I've tried the opposite: I've modified the name of the packages from `foo` to `foo_js`, and used the annotations to leave the real name `foo`:

```
def
  -> foo_js
    -> package-info.java
    -> foo_js
      -> Globals.java
      -> package-info.java
```

And it has worked. The code in the consumer project now is this, which is right:

```typescript
import foo_js = require("foo");
import foo = foo_js.foo;
```

Here I see two issues:

1. The transpiler seems to get confused when you use the same name for a namespace (a package, really) and a function that are exported in the same module.

2. The transpiler seems to use the Java package name when creating the namespace for the module import, regardless of the namespace that I've set with the `@jsweet.lang.Name` annotation at the package level.

I don't know how the code of the transpiler does all this. But maybe a simple change in the generation of the namespace for the import could help to avoid these name conflicts. For example, it could be generated using this strategy:

```java
namespace + "_" + random_string
```

So that the transpiler generates this TS code:

```typescript
import foo_3hf795 = require("foo");
import foo = foo_3hf795.foo;
```

It's just an idea. Thank you!

**Comment by negora** [comment]
I've spent some time checking the code of the transpiler. This is one of the few times that I've tried to take part in an open-source project, so it has taken me some time to understand the code. So, apologizes for doing it in a non-standard way.

Anyway, I think that I've came to a solution. I've ruled out the option of the "_ns" suffix, because it required to change more things than I expected. I've tried to be as less invasive as possible. I've attached a "diff" file to this message, so you can see what I've done and check if it's OK.

In short, I've made 2 changes:

	1. In the translator: to create the import alias used with "require()", I've used the value of the `@jsweet.lang.Name` annotation declared in the Java package that represents the module (the one with the `@jsweet.lang.Module` annotation). If `@Name` isn't used, the translator uses the name of the Java package, as it does nowadays.
	
	2. In the adapter: when creating the name relative to the root, I've indicated not to use the Java names. This way, the name of the TypeScript namespace is used, instead of the Java package's.
	
These changes seem to fix both errors from issues #318 and #319. But please, check if what I'm doing is right and modify it as appropriate.

Thank you.

[fix.diff.txt](https://github.com/cincheo/jsweet/files/1132920/fix.diff.txt)

**Comment by renaudpawlak** [comment]
Hey. Thank you for this contribution! Could you just create a Pull Request with it? I'll be able to test it more easily and merge it if it looks right. Thanks!

**Comment by negora** [comment]
I'm sorry for my lack of knowledge about GitHub, but I've never collaborated with a public repository. Should I fork the original repository at GitHub and then make a pull request to yours? Or can I make a pull request directly from my local repository? I've tried to push a feature branch from my local repository to yours, but obviously, I've no permission to do that.

Thank you.
