### ISSUE TITLE
Eclipse plugin, custom Include Filter, "Project > Clean" deletes project on disk

### ISSUE THREAD

**Issue by acristu** [cincheo/jsweet#322]
Eclipse IDE for Java Developers
Version: Neon.3 Release (4.6.3)

Steps:

- Configure > Enable JSweet builder
- Properties > JSweet > Enable project specific settings
- Include Filter `.*/subfolder/.*`
- Answer Yes: ![image](https://user-images.githubusercontent.com/6796822/28024217-b9671eac-6598-11e7-9337-b8b96fe02f03.png)
- Project > Clean
- Project is deleted from disk: ![image](https://user-images.githubusercontent.com/6796822/28024051-4bac4dec-6598-11e7-94d2-8c0cd7a3635e.png)
- Restore from git :)

**Comment by renaudpawlak** [comment]
Wow. It looks like a huge bug of the Eclipse plugin... (should probably be reported in the plugin's project).

**Comment by acristu** [comment]
Note that with the default settings the issue does not appear.

**Comment by acristu** [comment]
This issue was moved to cincheo/jsweet-eclipse-plugin#13

**Comment by acristu** [comment]
sorry about the wrong repo...moved the issue
