### ISSUE TITLE
Non snapshot maven artifact?

### ISSUE THREAD

**Issue by cluelessjoe** [cincheo/jsweet#326]
Hi 

I would like to include jsweet in our build but I just see -SNAPSHOT version, for example on the release repo, http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/candies/jsweet-core/1.2.0-20161222/ : 
jsweet-core-1.2.0-20161222-javadoc.jar       
jsweet-core-1.2.0-20161222-javadoc.jar.md5
jsweet-core-1.2.0-20161222-javadoc.jar.sha
jsweet-core-1.2.0-20161222-sources.jar       
jsweet-core-1.2.0-20161222-sources.jar.md5
jsweet-core-1.2.0-20161222-sources.jar.sha
jsweet-core-1.2.0-20161222.jar               
jsweet-core-1.2.0-20161222.jar.md5        
jsweet-core-1.2.0-20161222.jar.sha1       
jsweet-core-1.2.0-20161222.pom               
jsweet-core-1.2.0-20161222.pom.md5        
jsweet-core-1.2.0-20161222.pom.sha1       

Is there a reason for it? Is it possible to have non snapshot versions? 

Thanks in advance

**Comment by renaudpawlak** [comment]
Hey. These are not snapshots, they are actual versions, but all candy versions are tagged with the date. FI, in Maven, snapshots are *only* the ones with the -SNAPSHOT suffix, nothing else.

**Comment by cluelessjoe** [comment]
Indeed now that I look twice at them they lack the end of snapshots version, like jsweet-core-1.2.0-20161218.011632-32.pom for example.

To provide a bit more of context I looked first at the quickstart's pom, https://github.com/cincheo/jsweet-quickstart/blob/master/pom.xml, which uses:
<dependencies>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>jsweet-core</artifactId>
			<version>1.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>j4ts</artifactId>
			<version>0.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>jquery</artifactId>
			<version>1.10.0-SNAPSHOT</version>
		</dependency>
</dependencies>

BTW, why tagging jsweet-core like this too? 

Anyway, thanks a lot for your help and quick answer :)

**Comment by renaudpawlak** [comment]
Good question. We wanted jsweet-core to be bound to the transpiler version, but have the possibility to change with the candies (without having to release a transpiler)... This was the best way we found... in practice, we don't use this feature that much be we never know what will happen in the future :D
