### ISSUE TITLE
Using jsweet for dto ?

### ISSUE THREAD

**Issue by cluelessjoe** [cincheo/jsweet#327]
Hi

I'm currently investigating in jsweet to be able to write in java the objects I would like to use on the rest services, and then generate the corresponding Typescript to make sure the front uses the same definitions.

Would you advice using jsweet this way? 

When doing so I encounter these issues:
- I would like types like ZonedDateTime to be string in Typescript (but to keep its type in Java)
- I would like some java specific annotations not to be transpiled, for example @Data from lombok or some Jackson's ones like  @JsonFormat

Am I missing something? 

Thanks again

**Comment by renaudpawlak** [comment]
Hi. Yes, in theory JSweet is the right tool for your use case (and even more). With JSweet v2 you can write an extension (adapter) that will tune the generated code for what you want to do: typically you can specify in your adapter that ZonedDateTime translates to a string.

As for annotations, they are by default erased by JSweet, so they should not appear in the generated code (unless they are decorators). On the other hand you can write another adapter to use the annotations and tune the generation accordingly.

All the document about writing a JSweet extension is explained [here](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#extending-the-transpiler).

In any case, you must use JSweet v2 for doing this. I am in the process of releasing it, so don't be afraid of using the SNAPSHOT, it won't change anymore.

**Comment by renaudpawlak** [comment]
Please not that the documentation is WIP. I will improve it along the way to make it more accessible... feedback is welcome :D

**Comment by cluelessjoe** [comment]
I had missed this documentation, I'll looking into it, thx :)

**Comment by renaudpawlak** [comment]
It's new ;) Preparing v2. Months of work! I am all excited...

**Comment by renaudpawlak** [comment]
FI, I have just added a HelloWorld example so that you can get started easily. It is similar to your use case.
https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#hello-world-adapter

Also, note this [JAX-RS client sub generation example](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#example-5-an-adapter-to-generate-javascript-jax-rs-proxiesstubs), which could give you some ideas ;)

**Comment by cluelessjoe** [comment]
Thanks a lot :)
