### ISSUE TITLE
if then else bug

### ISSUE THREAD

**Issue by ssatguru** [cincheo/jsweet#33]
following
```java
package org.ssatguru.babylonjs;
import static jsweet.dom.Globals.console;
public class CodeSnippet {
	public static void main(String args[]){
		int i =1;
		if (i==1)console.log("is true");
		else console.log("is false");
	}
}
```
gives following error during TS compile
```
[INFO] JSweet transpiler version 1.0.0-SNAPSHOT (build date: 2016-01-16 10:30:13)
ERROR: ';' expected. at org\ssatguru\babylonjs\CodeSnippet.ts(6)
[ERROR] transpilation failed
```

**Comment by renaudpawlak** [comment]
Thank you for this one (good one). There is a lack of support for statements with optional blocks.

Temporary workaround: use blocks.

        if (i==1) { console.log("is true"); }
        else { console.log("is false"); }

I should be committing a fix very soon though.

**Comment by renaudpawlak** [comment]
It should be fixed with some variations (see https://github.com/cincheo/jsweet/blob/master/src/test/java/source/syntax/StatementsWithNoBlocks.java)

**Comment by ssatguru** [comment]
Great,
Thanks
