### ISSUE TITLE
StringBuilder issue

### ISSUE THREAD

**Issue by isakovarseniy** [cincheo/jsweet#340]
Hi 
Try this test class

```
package com.octo.sql.exp;

public class TestClass {

	  protected final StringBuilder result = new StringBuilder();

	  public void append(){
	      final String variableName = "qqqq";
	      result.append(":").append(variableName);
	  }
	
}

```

Generated code is 

```
namespace com.octo.sql.exp {
    export class TestClass {
        result : { str: string } = { str: "", toString: function() { return this.str; } };

        public append() {
            let variableName : string = "qqqq";
            /* append */(sb => sb.str = sb.str.concat(<any>variableName))(/* append */(sb => sb.str = sb.str.concat(<any>":"))(this.result));
            this.result.insert(0, "999");
        }
    }
    TestClass["__class"] = "com.octo.sql.exp.TestClass";

}
```

Error:(770, 47) TS2322:Type '{ str: string; toString: () => any; }' is not assignable to type '{ str: string; }'.
  Object literal may only specify known properties, and 'toString' does not exist in type '{ str: string; }'.
Error:(774, 35) TS2339:Property 'str' does not exist on type 'string'.
Error:(775, 25) TS2339:Property 'insert' does not exist on type '{ str: string; }'.

Probably you should generate something like this

```
namespace com.octo.sql.exp {
    export class TestClass {
        result : { str: string ,toString : Function } = { str: "", toString: function() { return this.str; } };

        public append() {
            let variableName : string = "qqqq";
            /* append */(sb => sb.str = sb.str.concat(<any>variableName)) ((sb => {sb.str = sb.str.concat(<any>":");return sb;})(this.result));
            this.result.insert(0, "999");
        }
    }
    TestClass["__class"] = "com.octo.sql.exp.TestClass";

}
```
Insert method for StringBuilder are not implemented

Thanks
Arseniy Isakov

**Comment by isakovarseniy** [comment]
logic for insert method 

```
insert = function insert(main_string, ins_string, pos) {
   return main_string.slice(0, pos) + ins_string + main_string.slice(pos);
    }

```

**Comment by renaudpawlak** [comment]
Well, support for JDK APIs is partial, but easy to extend and fix in JSweet v2. I have provided a fix in the ``RemoveJavaDependenciesAdapter``, but don't hesitate to improve JSweet using your own adapters (see the [documentation](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#extending-the-transpiler)).

**Comment by isakovarseniy** [comment]
Thank you very much for your  affords.

A little bit strange my WebsStorm still shows error on 

```
        result : { str: string } = { str: "", toString: function() { return this.str; } };

```
Error:(930, 52) TS2322:Type '{ str: string; toString: () => any; }' is not assignable to type '{ str: string; }'.
  Object literal may only specify known properties, and 'toString' does not exist in type '{ str: string; }'.

But no issue during compilation of code from JSweet.
Not sure if you need to fix it.

Thanks
Arseniy Isakov

**Comment by thw0rted** [comment]
I don't think the above commit fixed this issue, and I'm still seeing it.  I came here to blame JSweet (because `toString` isn't declared on the generated code's type) but really it's [this TS bug](https://github.com/Microsoft/TypeScript/issues/18537) where interfaces don't inherit the methods of `Object.prototype` and they should.  In the short term, maybe JSweet should just not declare the type explicitly at all, and let the compiler infer the type?  That's what I'm doing: hand-editing the relevant generated code to e.g. `let sb = { str: "", toString: function(): string { return this.str; } };`.

I'd submit a PR for this but I'm not sure where the above line is being generated...
