### ISSUE TITLE
Small code improvement

### ISSUE THREAD

**Issue by isakovarseniy** [cincheo/jsweet#341]
Hi
You can use this instead of uploading tools.jar to your local maven repository
```
				<dependency>
					<groupId>com.sun</groupId>
					<artifactId>tools</artifactId>
					<scope>system</scope>
					<systemPath>${java.home}/../lib/tools.jar</systemPath>
					<version>8</version>
				</dependency>
```

**Comment by renaudpawlak** [comment]
I think I tried this one before but I am unsure why I did now keep this solution. I think it was not working well for all environments/systems... I wanted a safe solution for all cases...
