### ISSUE TITLE
Import modules issue

### ISSUE THREAD

**Issue by isakovarseniy** [cincheo/jsweet#343]
Hi

I have following folder structure
```
src/main/java/
                       t.b
                            C1.java
 
src/test/java
                     t
                          T1.java
```

```
package t.b;

public class C1 {

}

```

```
package t;

import t.b.C1;

public class T1 {
	
	public void test(){
		
		new C1();
	}
}
```
module id "amd"
source folder is "src"

After conversion T1 is looks like this :
```
/* Generated from Java with JSweet 2.0.0-SNAPSHOT - http://www.jsweet.org */
import { C1 } from '../../../main/java/t/b/C1'; 
export class T1 {
    public test() {
        new C1();
    }
}
T1["__class"] = "t.T1";
var __Function = Function;
```

Thanks
Arseniy Isakov

**Comment by renaudpawlak** [comment]
That's a tricky one. You actually have 2 source folders in src... Obviously I forgot to take this case into account. I guess that the import should be something like:

```
import { C1 } from './b/C1'; 
```

Right?

**Comment by isakovarseniy** [comment]
Yes . Because we are merging everything under one package hierarchy.

**Comment by isakovarseniy** [comment]
Can you use your @Root annotation  to identify root of package tree?

**Comment by renaudpawlak** [comment]
I think it should be fixed, but it is not that easy to test. Could you please tell me if it works for you? Thanks.

**Comment by isakovarseniy** [comment]
Yes this issue is gone.
Thank you

**Comment by renaudpawlak** [comment]
Great! Thank you for your precious help. I hope it was the last bug for your case :)

**Comment by isakovarseniy** [comment]
:)
