### ISSUE TITLE
Methods aren't inherited when extending def.js.Error

### ISSUE THREAD

**Issue by negora** [cincheo/jsweet#346]
Hello:

I've extended the `def.js.Error` class to create my own exception. The instance of this child class, in JavaScript, seems to adopt the parameters/fields right. I've confirmed it with the debugger of Firefox.

However, the instance seems to lack the methods that I've set in Java. For example, I've written something as simple as this:

```java
  public final class MyError extends def.js.Error {

    private final boolean valid;


    public MyError (boolean valid) {
      this.valid = valid;
    }


    public boolean isValid () {
      return valid;
    }

  }
```

In another place, I've written this piece of code, which fails at runtime because the `isValid()` method doesn't exist:

```java
  try {
    if (true) {
      throw new MyError (true);
    }
  } catch (MyError ex) {
    logger.log ("valid=%s", ex.isValid ());
  }
```

I guess that this problem has to do with the changes introduced in TypeScript 2.1, which broke the feature of extending the `Error` class. In the article [Custom Errors in TypeScript 2.1](https://www.metachris.com/2017/01/custom-errors-in-typescript-2.1/) there are some comments about it and a probable solution. 

In the [Release notes of TypeScript 2.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html) they seem to have a solution for that too. Check the section *Support for new.target*.

Thank you.

**Comment by negora** [comment]
I've seen that the constructor generated for `MyError` is this:

```javascript
	function MyError(__parent, valid) {
		var _this = _super.call(this) || this;
		_this.__parent = __parent;
		_this.valid = false;
		_this.valid = valid;
		return _this;
	}
```

This means that I'm getting an instance of `Error` instead of `MyError`, Right? Is there any reason not to do it this other way?:

```javascript
	function MyError(__parent, valid) {
		_super.call(this);
		this.__parent = __parent;
		this.valid = false;
		this.valid = valid;
	}
```

I'm sorry in advance if I'm ignoring something important.

**Comment by renaudpawlak** [comment]
Well, that's indeed more a TypeScript issue. The constructor code you mention is generated by TypeScript and I don't have any control on it. Short term, I can generate the workaround explained [here](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work). Working on it.

**Comment by negora** [comment]
Hello Renaud:

Some minutes after publishing this bug report, I've realized about what you comment, that you haven't direct control over the output of `tsc`. I'm sorry, but some times I inspect so many things that I forget that details, he he he.

I've seen that you've committed the solution. Thank you for such a fast response! :)

**Comment by renaudpawlak** [comment]
Yep! Tell me if you hit issues but it should work. However, according to the doc, it will not work with IE 10 and lower :(
Eventually, a new version of TypeScript will fix it and the workaround will not be needed anymore.
