### ISSUE TITLE
Some mess during import stain method

### ISSUE THREAD

**Issue by isakovarseniy** [cincheo/jsweet#348]
Hi

First class
```
package t.k;

public class A1 {
	
	public static void m1(){
		
	}

}

```
Second class

```
package t;
import static  t.k.A1.m1;

public class B1 {
	
	public void f(){
		m1();
	}

}

```

After transformation

```
/* Generated from Java with JSweet 2.0.0-SNAPSHOT - http://www.jsweet.org */
import { m1 } from './k/A1'; 
import { A1 } from './k/A1'; 
let m1: any = t.k.A1.m1;
export class B1 {
    public f() {
        A1.m1();
    }
}
B1["__class"] = "t.B1";


var __Function = Function;

```
You shouldn't import method m1 as long as you have
```
let m1: any = t.k.A1.m1;
```

in method body you should call m1 directly
so 

generated code should looks like this
```
/* Generated from Java with JSweet 2.0.0-SNAPSHOT - http://www.jsweet.org */
import { A1 } from './k/A1'; 
let m1: any = A1.m1;
export class B1 {
    public f() {
        m1();
    }
}
B1["__class"] = "t.B1";


var __Function = Function;
```

**Comment by renaudpawlak** [comment]
Grrr. That's most probably a regression due to latest improvements in imports... Well, that's a perfect time to improve the unit tests.

**Comment by isakovarseniy** [comment]
You still have an issue

```
import { A1 } from './k/A1'; 
let m1: any = A1.m1;
export class B1 {
    public f() {
        A1.m1();
    }
}
B1["__class"] = "t.B1";



var __Function = Function;

```
code calling A1.m1(); instead of m1();

**Comment by isakovarseniy** [comment]
Actually you unit tests is pretty heavy. I tried to build your project on my computer. It takes time. I have Mac Pro 2011. You probably need to have something as antlr   to analyze generated code

**Comment by renaudpawlak** [comment]
``A1.m1()`` is suboptimal, but it works right?

The problem with unit tests is that there start an instance of tsc through the command line. So they require a lot of resources. There is a plan to avoid launching tsc through a new process: https://github.com/cincheo/jsweet/issues/5. I know it will work but I never had time to complete the development.

**Comment by isakovarseniy** [comment]
Yes it works
