### ISSUE TITLE
Comparison of Enums with equals() operator fails

### ISSUE THREAD

**Issue by negora** [cincheo/jsweet#351]
Hello:

I've a simple `enum` like this:

```java
public enum MyEnum {
  A,
  B,
  C;
}
```

And I'm doing this comparison:

```java
MyEnum e = MyEnum.A;
boolean result = (e.equals (MyEnum.B));
```

It compiles fine, but fails at runtime with the following error:

> TypeError: MyEnum_1.MyEnum._$wrappers is undefined

The TS generated where the comparison is done is this:

```typescript
let e : MyEnum = MyEnum.A;
let result : boolean = (MyEnum["_$wrappers"][e].equals(MyEnum.B));
```

I guess that `_$wrappers` is a parameter added by JSweet to be able to compare `enums` that have parameters in addition to their internal ordinals. However, the `_$wrappers` parameter isn't created if the `enum` doesn't contain any parameter. This is the resulting TypeScript code indeed:

```typescript
export enum MyEnum {
    A, B, C
}
```

If I add a parameter called `x` of type `int` to the `enum`, the `_$wrappers` parameter is created correctly:

```typescript
export enum MyEnum {
    A, B, C
}

/** @ignore */
export class MyEnum_$WRAPPER {
    /*private*/ x;

    constructor(protected _$ordinal : number, protected _$name : string, x) {
        this.x = 0;
        this.x = x;
    }
    public name() : string { return this._$name; }
    public ordinal() : number { return this._$ordinal; }
}
MyEnum["__class"] = "com.canalsoria.el.web.client.site.nonmod.MyEnum";
MyEnum["__interfaces"] = ["java.lang.Comparable","java.io.Serializable"];

MyEnum["_$wrappers"] = [new MyEnum_$WRAPPER(0, "A", 1), new MyEnum_$WRAPPER(1, "B", 2), new MyEnum_$WRAPPER(2, "C", 3)];
```

However, it also fails at runtime, but this time with this error:

> TypeError: MyEnum_1.MyEnum._$wrappers[e].equals is not a function

If I check the TypeScript code where the comparison is made:

```typescript
 let result : boolean = MyEnum["_$wrappers"][e].equals(MyEnum.B);
```

Taking into account that the `equals` method of `Enum` is `final` in Java (it can't be overridden), I think that it would be safe to replace `equals()` with `===`, Right? What do you opine?

Thank you!

**Comment by renaudpawlak** [comment]
Right. I missed this one because I never use equals on enums :(
Clearly, since it is final, using === is fine.
Thank you!

**Comment by negora** [comment]
Perfect :) . Thank you!
