### ISSUE TITLE
Core annotations not working in jsweetconfig.json

### ISSUE THREAD

**Issue by dasa** [cincheo/jsweet#364]
I'm trying to use the following `jsweetconfig.json` file in the `jsweet-quickstart` project following the example at: https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#centralizing-annotations-in-jsweetconfigjson

```json
{
  "@Root": {
    "include": [
      "quickstart"
    ]
  }  
}
```

The error is `unsupported option: @Root`:

```
2017-09-08 12:35:30.030 INFO  JSweetTranspiler:364 - configuration file found
2017-09-08 12:35:30.030 DEBUG JSweetTranspiler:368 - configuration: {@Root={include=[quickstart]}}
2017-09-08 12:35:30.030 ERROR JSweetTranspiler:300 - unsupported option: @Root
2017-09-08 12:35:30.030 INFO  JSweetTranspiler:419 - creating transpiler version 2.0.0 (build date: 2017-08-31 10:04:10)
```

p.s. - Should the sample be using `@Erased` instead of `@Erase`?

**Comment by renaudpawlak** [comment]
You are absolutely right (twice).

- Reporting an error is a bug here. However, it is an indication and it does not prevent the transpiler to do the right thing and take the ``@Root`` annotation into account. So please just ignore this error for now.
- Yes, it should be ``@Replaced`` and not ``@Replace``.

That's a good reason to release a 2.0.1 ASAP.

Thanks!

**Comment by renaudpawlak** [comment]
Fixed in https://github.com/cincheo/jsweet/commit/79bb475048b6b2875ce814cb2900a755efb142c5. Please use 2.0.1-SNAPSHOT.
