### ISSUE TITLE
Can not compile project using J4TS

### ISSUE THREAD

**Issue by alievrenkut** [cincheo/jsweet#367]
I can not compile my project with JSweet 2.0. I used j4ts in my project. I tried to compile j4ts with 2.0 but it did not work so I created issue: https://github.com/j4ts/j4ts/issues/21

Is there a plan to fix j4ts for 2.0? I needed it for my project. My project is a large one so it will not be trivial to refactor it to not use j4ts.

**Comment by renaudpawlak** [comment]
I will look at it, but as far as I remember, I have already compiled j4ts with JSweet v2.

**Comment by renaudpawlak** [comment]
Ok. I have updated for JSweet v2 and merged back the development branch into J4TS master... Should be up-to-date now.
