### ISSUE TITLE
allow private constructors

### ISSUE THREAD

**Issue by lgrignon** [cincheo/jsweet#38]
private constructors raise an error with JSweet, I think it would be better to permit it and delete it at transpilation time, so we could enjoy the private constructor feature at least in our IDE.

**Comment by renaudpawlak** [comment]
Private constructors show now be ok. But at this point, be aware that constructor overloading is not allowed (i'll create a new issue for this).

**Comment by lgrignon** [comment]
yes, of course. Thanks.
