### ISSUE TITLE
Double::compareTo undefined

### ISSUE THREAD

**Issue by enricostara** [cincheo/jsweet#383]
Hi,
trying to use a TreeMap<Double, Object> at runtime throws the following error:

**o1.compareTo is not a function. (In 'o1.compareTo(o2)', 'o1.compareTo' is undefined)**

in the 
```
            var NaturalComparator = (function () {
                function NaturalComparator() {
                }
                /**
                 *
                 * @param {*} o1
                 * @param {*} o2
                 * @return {number}
                 */
                NaturalComparator.prototype.compare = function (o1, o2) {
                    javaemul.internal.InternalPreconditions.checkNotNull(o1);
                    javaemul.internal.InternalPreconditions.checkNotNull(o2);
                 >>>   return o1.compareTo(o2);
                };
                return NaturalComparator;
            }());
```
Could you please give me an hint on this?

Enrico

**Comment by renaudpawlak** [comment]
Ouch. So, it means that o1 is not of the right type? Or is it null/undefined? Can you get the runtime value of o1 and introspect it in the debugger? Clearly if hint there is, it is on the callee side...

**Comment by enricostara** [comment]
Hi Renaud,
please try the following snipped (I changed my app, so I'm replicating the case):

```
        SortedSet<Double> sorted = new TreeSet<>();
        sorted.add(1d);
        sorted.add(2d);

```
you should find that both o1 and 02 are javascript numbers (where ::compareTo cannot be in).

Best,
E

**Comment by renaudpawlak** [comment]
Yes, JSweet object are always regular JavaScript objects. However when you use compareTo, an adapter should generate the right code to have it working.
I guess that the root cause of the problem here is that the J4TS implementation of TreeSet uses the compareTo method?

I don't think that it is difficult to fix. Maybe just change the TreeSet implementation in J4TS. Can you confirm that you last code snippet just fails when you are compiling/running it with J4TS (and not failing without it)?

**Comment by enricostara** [comment]
Yes Renaud, it's only with J4TS, since TreeMap implementation is available only using it! 
In fact, this is, at moment, the only reason why I'm using J4TS in my project..

**Comment by schaumb** [comment]
I think this problem could be solve if we handle compareTo() function same as hashCode(). If it is exist, call that, else compares as expected (a < b ? -1 : b < a ? 1 : 0)
If you think the same, then I can make a pull request for that change

**Comment by lgrignon** [comment]
Yes please, that would be perfect.
Just run the UT before PR to be sure ;)
