### ISSUE TITLE
Modify import statements using the adapter

### ISSUE THREAD

**Issue by ADegele** [cincheo/jsweet#384]
Hi,
First, the big picture: the goal is to have the same code performing validation on a data object both on the server (Java) and the client (Typescript with Angular2). The validation code is transpiled to TS with JSweet (obviously). Because the code needs to run on client and server, I can't use empty definition classes, but have to use an adapter to change types and rewrite method calls. One of the biggest challenges here is that our data objects have different names on server (e.g. AdresseTBE) and client (Adresse), because they are generated for the client with a different generator. I managed to adapt the types in variable declarations, but I can't figure out how to modify imports using the adapter. 
I had a look at the examples, since the BigDecimalAdapter from the [language-specification](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md) should deal with a similar scenario. 
I've attached a simple project [jsweet-playground.zip](https://github.com/cincheo/jsweet/files/1358451/jsweet-playground.zip) based on the BigDecimalAdapter.
The BigDecimalAdapter should change every BigDecimal to the Big.js library. Here is my Java Code:
```Java
import java.math.BigDecimal;

public class Main {
	public static void main() {
		final Calculator calculator = new Calculator();
		final BigDecimal result = calculator.foo();
	}
}
```
which is transpiled to TypeScript (using module=commonjs):
```Typescript
import { Calculator } from './Calculator'; 
export class Main {
    public static main() {
        let calculator : Calculator = new Calculator();
        let result : Big = calculator.foo();
    }
}
Main["__class"] = "test.Main";

Main.main();
```
I think in the TypeScript there should be an import for `Big`, but there is none. How does this compile? Or am I missing something?

**Comment by isakovarseniy** [comment]
Look at issue "#345".  It is status "Closed".

**Comment by ADegele** [comment]
Thanks for the answer. 
If I stay at the BigDecimalAdapter Example, I have now something like this: 
```Java
public BigDecimalAdapter(final PrinterAdapter parent) {
	super(parent);
	// all BigDecimal types are mapped to Big
	// addTypeMapping(BigDecimal.class.getName(), "Big");
	addTypeMapping((element, name) -> {
		if (BigDecimal.class.getName().equals(element.getTypeAsElement().toString())) {
			addHeader("import.big.js", "import Big from './path/to/big.js';");
			return "Big";
		} else {
			return null;
		}
	});
}
```
When I run this Adapter with JSweet, it indeed emits an import statement, but fails to resolve the type, since the path is obviously wrong. I don't understand, why TSC knows about Big without the import. But this is not the topic.
I applied something similar to my real project and since I'm only outputting TS with JSweet and running TSC externally, it actually works.
