### ISSUE TITLE
Trying to transpile dynamodb-transactions

### ISSUE THREAD

**Issue by aaaristo** [cincheo/jsweet#388]
Reference repo:
https://github.com/awslabs/dynamodb-transactions

Example transpilation repo:
https://github.com/aaaristo/dynamodb-transactions-jsweet

Fails with:
JSweetTranspiler:1477 - com/amazonaws/services/dynamodbv2/transactions/Transaction.ts(561,25): error TS1005: ';' expected.

com/amazonaws/services/dynamodbv2/transactions/Transaction.ts(561,25):
let delete : com.amazonaws.services.dynamodbv2.model.DeleteItemRequest = new com.amazonaws.services.dynamodbv2.model.DeleteItemRequest().withTableName(request.getTableName()).withKey(request.getKey(this.txManager)).withExpected(expected);

Any idea?

**Comment by renaudpawlak** [comment]
Just a guess but ``delete`` is a keyword in JavaScript. So the local variable cannot be called ``delete``. I'll fix it automatically when possible but in the meantime, you can try to rename ``delete``.
