### ISSUE TITLE
Slow transpilation with generic interfaces

### ISSUE THREAD

**Issue by Smiche** [cincheo/jsweet#393]
When using generic interfaces the transpilation time gets exponentially slower with the count of implementing classes increasing. In our project it got up to 40 minutes.

Here's a repository reproducing the issue:
https://github.com/Smiche/jsweet-issue-example
(generate-sources with profile jsweet)

The generated typescript implementing classes import all other implementing classes, which is my guess why transpilation gets slower with more implementations. I've tried debugging the compiler but am still not that familiar with the project so I couldn't hunt it down.

**Comment by Smiche** [comment]
The way we go around it currently is to use @Erased on the interface and then cast to another interface with the same methods. Not optimal but works for now.

**Comment by renaudpawlak** [comment]
Really good report thanks. I am working on it right now. Hope I will find the issue today.

**Comment by renaudpawlak** [comment]
Update: this only happens when using modules (which explains why I missed that). I will try to use VisualVM to understand...

**Comment by renaudpawlak** [comment]
Linked to #342 fix. To be thought over again...
