### ISSUE TITLE
Iterator and Iterable

### ISSUE THREAD

**Issue by glooms** [cincheo/jsweet#394]
Hi! I am trying to use classes that implement the interfaces [java.lang.Iterable](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html) and [java.lang.Iterator.](https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html)
If I transpile without j4ts, the transpilation works, but the javascript object I get out is not iterable... I can call the objects iterator method but I cannot iterate over what I expected to be an iterable object.

If however, I transpile it with j4ts candy, I instead get complaints that the classes are not correctly implemented, e.g. the message:
`ERROR: class 'Range' incorrectly implements interface 'Iterable<number>'`
`INFO: Property 'forEach' is missing in type 'Range'.`

This even though the java code specified fully implements the two java interfaces mentioned above.
How can this problem be solved?

Java source code snippet:

public class Range implements Iterable\<Integer\> {

    private int start;
    private int end;
    private int at;

    public Range(int start, int end) {
        this.start = start;
        this.end = end;
        at = start;
    }

    public Iterator<Integer> iterator() {
        return new RangeIterator();
    }

    private class RangeIterator implements Iterator<Integer> {
        
        public boolean hasNext() {
            return at < end;
        }

        public Integer next() {
            int next = at;
            at += 1;
            return next;
        }

        public void remove() {
        }
    }

**Comment by renaudpawlak** [comment]
Hello!
Could you be more specific about your problem without J4TS? I have tried to run the following program and it works fine:

```java
		Range r = new Range(10, 20);
		Iterator<Integer> it = r.iterator();
		int j = 10;
		while (it.hasNext()) {
			int i = it.next();
			assert i == j++;
		}
		assert j == 20;
```

As you can see I am getting the iterator for your range object, and I am iterating on if fine... So what are you trying to do exactly?

For the issue with J4TS, it looks like a known problem with how JSweet implements default methods... It does not work when using an external interface (from another JSweet candy) that defines ``default`` methods. Maybe a work around would be to implement the ``forEach`` method in your target class. This needs to be fixed at some point so I am flagging this as a bug.

**Comment by renaudpawlak** [comment]
Seems related to #289. (not 100% sure)

**Comment by glooms** [comment]
The problem without J4TS is that the object generated as javascript does not seem to be iterable. I am no expert at Javascript so that might be the issue here. But to my understanding the ´for of´ loop is equivalent to the ´for each´ loop in Java and when I try to use it in browser console it simply returns an error saying that the item is not iterable. The resulting Range object in javascript does not seem to have a forEach method either. Basically, when I try to use the Range object in javascript, it does not have the properties of an iterable object, at least in my view.

**Comment by glooms** [comment]
Turns out that the problem stemmed from the source code using a different version of Java, and thus not implementing the interfaces according to Java 8. After implementing the methods it seems to work perfectly! Sorry for the confusion.

**Comment by renaudpawlak** [comment]
Well, that's good news. So there is "only" the J4TS issue remaining.

**Comment by glooms** [comment]
Well, I don't know if there is any issue remaining, I am transpiling with jsweet using the candy J4TS, no errors and the resulting javascript code is behaving as expected.

**Comment by renaudpawlak** [comment]
Ok, great, let's close it for the moment then.
