### ISSUE TITLE
TypescriptDefParser is on gitignore

### ISSUE THREAD

**Issue by TreffnonX** [cincheo/jsweet#396]
The (essential?) Class "org.jsweet.input.typescriptdef.parser.TypescriptDefParser", and the related Scanner seem to be on gitignore.

As I have no "healthy" version of the project, I cannot assess, whether this is actually a bug, but I cannot currently build. This might be due to my inability to correctly set the project up though.

**Comment by lgrignon** [comment]
The org.jsweet.input.typescriptdef.parser.TypescriptDefParser class is actually part of the candy-tools project:
https://github.com/cincheo/jsweet/tree/master/candy-generator

You shouldn't need it if you want to work on the transpiler only.

Please be sure that you imported in your IDE the maven project from https://github.com/cincheo/jsweet/tree/master/transpiler

Thanks

**Comment by renaudpawlak** [comment]
Besides, the parser and the lexer of the candy generator are automatically generated by JFlex and CUP parser generator (see the cup and lex files), that's why they are on .gitignore. You need to build the candy generator project to generate the files.

**Comment by TreffnonX** [comment]
Yep, I was now able to build the files, after I realized, that eclipsefor some reason did not resolve the compile_classpath when trying to run the ant-build. After specifying absolute paths for both cup and jflex, I was able to build all required java-files.
Thanks for the quick response!
