### ISSUE TITLE
for(T t : iterable) will translate to an array-(list) iteration

### ISSUE THREAD

**Issue by TreffnonX** [cincheo/jsweet#400]
I have written a Class implementing the java interface java.lang.Iterable
While the entire thing works to my great satisfaction, the only thorn in my eye is,
that any for-each loops will be transpiled assuming a JavaScript-Array based type.

```java
DataList<RoomManager> roomsToHandle = getRescanMap().get(sequenceId);
for (RoomManager manager : roomsToHandle) {
	manager.recalculateNeeds();
}
```

The above code will be transpiled into:

```javascript
var roomsToHandle = this.getRescanMap().get(sequenceId);
for (var index123 = 0; index123 < roomsToHandle.length; index123++) {
	var manager_2 = roomsToHandle[index123];
	{
		manager_2.recalculateNeeds();
	}
}
```

While I would have expected something along the lines of:

```javascript
var roomsToHandle = this.getRescanMap().get(sequenceId);
for (var iter123 = roomsToHandle.iterator(); iter123.hasNext();) {
	var manager_2 = iter123.next();
	{
		manager_2.recalculateNeeds();
	}
}
```

The proposed transpilation only works on actual implementations of Iterable, which do implement the method "iterator()" and provide a matching Iterator object, so a fix would mean changing the transpiler to semantically check, if one of the array-iterable types is present to not break existing code.

For clarification:
The current transpilation will result in runtime exceptions, since DataList is not actually a simple javascript list, strictly speaking, so the "[index123]"-accessor will not work. In this instance only the second transpilation can work at runtime.

**Comment by TreffnonX** [comment]
I have found the code (as I would expect it) in the current version of Java2TypeScriptAdapter. I seem to be transpiling with an old version of JSweet, or I am using the wrong Iterator-Interface. Do I need to use some alternate Interface to get it to transpile with "substituteForEachLoop" ?

**Comment by renaudpawlak** [comment]
@TreffnonX could you please provide the implementation of ``DataList``? In theory, implementing iterables works fine with JSweet, as [this test case](https://github.com/cincheo/jsweet/blob/master/transpiler/src/test/java/source/nativestructures/Iterators.java) illustrates. Maybe it is a conflict with iterables and JS lists, but from what I see it is hard to tell (and fix).

**Comment by TreffnonX** [comment]
I don't have the code available at the moment, but DataList implements Iterable and provides an iterator()-method providing a healthy Iterator object, which is accessible and works. It is however not strictly speaking a List, as it does not implement List.

However, my issue is with the for-each loop. The test case you referenced explicitly invokes the iterator()-method. This way, the test case does not garantee the for-each loop. Instead the following test would fail:

```java
public class Iterators {
	public static void main(String[] args) {
		Range r = new Range(10, 20);
		int j = 10;
		for (Integer i : r) {
			assert i == j++;
		}
		assert j == 20;
	}
}
```

This is because the for loop would transpile into an index-based iteration, instead of an iterator-based one.
There is code in the Java2TypeScriptAdapter class, which should cover this case, if the looped object does not contain a length-attribute, however I think the adapter is not active or for some reason is not executed.

**Comment by renaudpawlak** [comment]
Oh. Okay. I see now. Of course. That should be easy to fix.
