### ISSUE TITLE
Cast to (long) transpiles to Math.floor() which does not work for negative numbers

### ISSUE THREAD

**Issue by sebkur** [cincheo/jsweet#402]
As you can see I think in this line:
https://github.com/cincheo/jsweet/blob/c325cc77b061a8d65fcff0bb4a816b302574671f/transpiler/src/main/java/org/jsweet/transpiler/Java2TypeScriptTranslator.java#L4851
casting a number (say a double) to `long` transpiles to `Math.floor()`, which is okay for positive numbers, but fails for negative numbers. For example `Math.floor(1.23) == 1`, but `Math.floor(-1.23) == 2` while the expected result of a cast to long is `1` and `-1`.

**Comment by sebkur** [comment]
Thanks

**Comment by renaudpawlak** [comment]
Well thank you first for spotting such an horrible bug :(
