### ISSUE TITLE
T.class transpiles to simple name, instead of full name.

### ISSUE THREAD

**Issue by TreffnonX** [cincheo/jsweet#405]
The line within MyClass in the package "some.pack":

```java
Class<?> clazz = MyClass.class;
```

transpiles into

```javascript
var clazz = MyClass;
```

instead of the fully qualified name:

```javascript
var clazz = some.pack.MyClass;
```

Which causes the class object to be undefined.

**Comment by TreffnonX** [comment]
This seems to work under normal cercumstances. My bug seems to be in my own code. Sorry for the confusion.

**Comment by renaudpawlak** [comment]
Cool. I was actually quite surprised about this one :D
I'll may add a unit test just for safety...
