### ISSUE TITLE
Browser demo doesn't work

### ISSUE THREAD

**Issue by Daniel-Hug** [cincheo/jsweet#415]
Trying to compile the example program ("Quick Start") [on the website](http://www.jsweet.org/jsweet-live-sandbox/), I get this error:
> \<unknown\>: cannot find Node.js: install first and make sure that the 'node' command is in your execution path

**Comment by renaudpawlak** [comment]
Did you follow the advice and installed Node.js? (and make sure it works by typing "node" in a console?)

**Comment by ck-alpha** [comment]
I have the same issue (didn't before) and node executes fine in a terminal

**Comment by renaudpawlak** [comment]
I would not be surprised if it was a regression because of this: https://github.com/cincheo/jsweet/pull/411

Under what OS?
How do you run? (in IDE such as Eclipse? in a console?)

**Comment by ck-alpha** [comment]
Reading the OP's message again I don't know if we are referring to the same issue...

I'm referring to the non-functional live demo on the website:
http://www.jsweet.org/jsweet-live-sandbox/

Not working on Chrome/Safari/Firefox on OS X

**Comment by Daniel-Hug** [comment]
I also was referring to running the example directly on the website: http://www.jsweet.org/jsweet-live-sandbox/

This should not depend on any software on my computer outside of my browser (Chrome).

**Comment by renaudpawlak** [comment]
Oops. Yes. It was a misunderstanding. It is a problem on our server. Will fix ASAP.
Many thanks for reporting.

**Comment by renaudpawlak** [comment]
It is fixed! :)
