### ISSUE TITLE
Property 'equals' does not exist on type 'V', where 'V' is a type variable of a class

### ISSUE THREAD

**Issue by hnine999** [cincheo/jsweet#424]
I'm trying to transpile a set of java classes.  There's nothing very complicated about them, but I'm having problems with a class that uses generic type parameters.  The class is below.

----------------------------
package com.geometricmethods.stl.support;

public class Pair<K,V> {

	public static<K,V> Pair<K,V> of(K key, V value) {
		return new Pair<>(key, value);
	}

	final public K first;
	public V second;
	
	private Pair(K first, V second)
	{
		this.first = first;
		this.second = second;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((first == null) ? 0 : first.hashCode());
		result = prime * result + ((second == null) ? 0 : second.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pair other = (Pair) obj;
		if (first == null) {
			if (other.first != null)
				return false;
		} else if (!first.equals(other.first))
			return false;
		if (second == null) {
			if (other.second != null)
				return false;
		} else if (!second.equals(other.second))
			return false;
		return true;
	}
}

-----------------------------------------------------
The error I'm getting is:

2018-02-28 17:13:42.042 ERROR output:55 - property 'equals' does not exist on type 'K' at /Users/hnine/Github/SectionFitting/stl/src/main/java/com/geometricmethods/stl/support/Pair.java(39)
2018-02-28 17:13:42.042 INFO  JSweetTranspiler:1403 - com/geometricmethods/stl/support/Pair.ts(46,36): error TS2339: Property 'equals' does not exist on type 'V'.
2018-02-28 17:13:42.042 ERROR output:55 - property 'equals' does not exist on type 'V' at /Users/hnine/Github/SectionFitting/stl/src/main/java/com/geometricmethods/stl/support/Pair.java(44)

-----------------------------------------------------
The problem appears to be with !first.equals(other.first) and !second.equals(other.second).  "first" and "second" are of the generic types K and V, respectively.

Is there some way to handle this maybe make JSweet assume 'equals' is always '==='?

Thanks
-- Harmon

**Comment by lgrignon** [comment]
Thanks for reporting, it's a good one. It seems that some condition isn't matched in https://github.com/cincheo/jsweet/blob/master/transpiler/src/main/java/org/jsweet/transpiler/extension/Java2TypeScriptAdapter.java#L1186

I won't have time to look at it today, but maybe you would like to contribute?

Bye
