### ISSUE TITLE
The links to the language specifications (in the web site) still point to v. 1.2.0

### ISSUE THREAD

**Issue by negora** [cincheo/jsweet#428]
Hello:

I've noticed that the links to the language specifications (in the website) still point to v. 1.2.0 instead of 2.0.0. Specifically:

* Resources -> Language specifications: https://github.com/cincheo/jsweet/blob/v1.2.0/doc/jsweet-language-specifications.md

* Language specifications (download PDF): https://github.com/cincheo/jsweet/raw/v1.2.0/doc/jsweet-language-specifications.pdf

I've found out that there is a page that is more up-to-date here: https://github.com/cincheo/jsweet/blob/v2.0.0/doc/jsweet-language-specifications.md . Shouldn't these links point to this version? Or is it still work in progress?

Thank you.

**Comment by lgrignon** [comment]
@renaudpawlak Could you perform this modification?

**Comment by lgrignon** [comment]
Done

**Comment by negora** [comment]
Thank you.
