### ISSUE TITLE
Question: support or workaround for try-with-resources

### ISSUE THREAD

**Issue by blagae** [cincheo/jsweet#437]
From my build logs:

```
2018-05-16 09:45:38.038 ERROR output:55 - try-with-resource statement is not supported 
2018-05-16 09:45:38.038 ERROR output:55 - try statement must define at least a catch or a finally clause
```

I completely understand this feature of Java 7+ not being supported, what with nor JavaScript nor TypeScript having this construct, as far as I can tell. However, is this planned in the future in some way, and/or do you know of any workarounds ?

**Comment by lgrignon** [comment]
Hello,
The obvious workaround is the former syntax `try {} finally { resource.close() }` :)

Sorry but we do not plan to integrate this feature anytime soon given the low priority but this is a nice idea. It should not be too complicated though if you want to contribute I would be super glad to review your PR!

Thanks anyway for reporting!

**Comment by blagae** [comment]
@lgrignon I have the application code ready, but I'm having some trouble with running the tests.

In theory, the entire `InvalidTryCatchTest` should be obsolete as it stands, but I can't verify that, and I'm not sure how to add new tests. I can add my test cases here (or on the pull request I'll create soon) so you can integrate them in the testing suite, if that's alright with you.

**Comment by lgrignon** [comment]
Yes, it is alright
