### ISSUE TITLE
Candy Generator Doesn't Compile

### ISSUE THREAD

**Issue by mfreeman-xtivia** [cincheo/jsweet#445]
Did a git clone of JSweet

cd into candy-generator

run mvn install and get the following exceptions

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jsweet-candy-generator: Compilation failure: Compilation failure:
[ERROR] /C:/Users/mfreeman/Projects/working/jsweet/candy-generator/src/main/java/org/jsweet/input/typescriptdef/TypescriptDef2Java.java:[42,45] cannot find symbol
[ERROR]   symbol:   class TypescriptDefParser
[ERROR]   location: package org.jsweet.input.typescriptdef.parser
[ERROR] /C:/Users/mfreeman/Projects/working/jsweet/candy-generator/src/main/java/org/jsweet/input/typescriptdef/TypescriptDef2Java.java:[183,17] cannot find symbol
[ERROR]   symbol:   class TypescriptDefParser
[ERROR]   location: class org.jsweet.input.typescriptdef.TypescriptDef2Java
[ERROR] /C:/Users/mfreeman/Projects/working/jsweet/candy-generator/src/main/java/org/jsweet/input/typescriptdef/TypescriptDef2Java.java:[183,46] cannot find symbol
[ERROR]   symbol:   variable TypescriptDefParser
[ERROR]   location: class org.jsweet.input.typescriptdef.TypescriptDef2Java

**Comment by mfreeman-xtivia** [comment]
So I did a RTFM and got through some of my earlier hurdles but no matter what I try I am consistently getting an error

" Source 'templates\candy-project' does not exist"

when i try to use the tool to generate a new candy. I am guessing its mad b/c somehow I am not getting the templates directory from the project folder into the JAR. Can anyone pls help as to what I am missing here in terms of building/using the candy generator?

**Comment by lgrignon** [comment]
Did you build using the following procedure?
## How to build

In the candy-generator's directory, generate TypeScript parser from syntax files (CUP/JFlex):

```bash
$ mvn generate-sources -P genparser
```

Then build the entire project:

```bash
$ mvn clean package
```

Optionally, if you need to re-package the Jar file used to run the tool.

```bash
$ mvn clean compile assembly:single
```

**Comment by lgrignon** [comment]
You must then run from the candy-generator directory something like:
```
java -jar target/candy-tool.jar init-project -o ../../candy-test -a processing -r true -u lgrignon
```

**Comment by mfreeman-xtivia** [comment]
Yeah it took me a while and I didnt read the manual as closely as I should have. Was assuming I could build the JAR and just run it from anywhere, but once I sorted out the preference for a parent ../candies directory, the need for the templates dir etc it all worked as expected.
