### ISSUE TITLE
Filter constructors with extended JSweetFactory

### ISSUE THREAD

**Issue by chfeiler** [cincheo/jsweet#475]
The command line JSweet transpiler allows one to specify an own extension of `JSweetFactory` that should be used during transpilation. In the factory you can create an extended `Java2TypeScriptTranslator`.
If we create this extended translator to be equal to the default `Java2TypeScriptTranslator` except for the fact that not all constructors are translated, the JSweet Translator behaves in a strange way: it doesn't transpile any of the constructors.
 
As an example: let's assume we have a Java class like:
```
public class SomeStuff {
  public SomeStuff() {
    // do stuff
  }
  public SomeStuff(String a) {
    // do other stuff
  }
  public SomeStuff(String a, String b) {
    // do yet some other stuff
  }
}
```

If we now extend the `Java2TypeScriptTranslator` and overwrite the `visitTree` function to skip the translation of the constructor `public SomeStuff(String a, String b)` (which is passed to `visitTree` as a `JCTree.JCMethodDecl`), none of the other constructors is translated.

**Expected behaviour**
JSweet transpiles the constructors `public SomeStuff(String a)` and `public SomeStuff()`. (Of course in the TypeScript they can't appear as separate constructors as this is not possible, however the logic of the two separate Java constructors should be included in a single TypeScript constructor)

**Observed behaviour**
JSweet creates a default TypeScript constructor for `SomeStuff` (ignoring the other two constructors that were not supposed to be skipped)

**Comment by lgrignon** [comment]
First of all: thanks for reporting!
Then, you aren't really supposed to override visitTree, there are plenty of visitor's methods, did you try to override visitMethodDef?

**Comment by chfeiler** [comment]
Thank for the fast response!
I tried it with visitMethodDef and it didn't work either. I had a closer look into the source code and it seems like the constructors are not printed with visitMethodDecl ( [return statement in visitMethodDef if method is a constructor](https://github.com/cincheo/jsweet/blob/master/transpiler/src/main/java/org/jsweet/transpiler/Java2TypeScriptTranslator.java#L2124) ). Is this correct? This would make it hard to filter constructors at all.

**Comment by lgrignon** [comment]
Yeah, actually it all happens in this monster method:
https://github.com/cincheo/jsweet/blob/master/transpiler/src/main/java/org/jsweet/transpiler/Java2TypeScriptTranslator.java#L1348

I suggest we try a different approach: did you try @Erased on the constructor?

**Comment by chfeiler** [comment]
Yeah extending the Translator is not a good idea then.
`@Erased` actually works without problems so far.  So a PrinterAdapter with a custom AnnotationManager does the job now. Thanks!
