### ISSUE TITLE
Lambda expression transpile fails

### ISSUE THREAD

**Issue by tinca** [cincheo/jsweet#487]
I am taking this to here from the forum, because no answer came from there and this is a showstopper for me.

Given the below interface:
```
public interface MyFunct {

    MyFunct SUM2 = new MyFunct() {
        @Override
        public double combine(double a, double b) {
            return a + b;
        }
    };
    MyFunct SUM = (a, b) -> a + b;
    MyFunct MAX = Math::max;

    double combine(double a, double b);
}
```

The SUM2 only version transpiles fine.

Code having only SUM gives:
> Task :jsweet FAILED internal transpiler error at /Users/zkuti/projects-new/jsweet-quickstart/src/main/java/quickstart/MyFunct.java(9) dumping transpiler’s strack trace:
> [JCVariableDecl] MyFunct SUM = (a,b)->a + … (/Users/zkuti/projects-new/jsweet-quickstart/src/main/java/quickstart/MyFunct.java:9)
> [JCClassDecl] public interface MyFunct {… (/Users/zkuti/projects-new/jsweet-quickstart/src/main/java/quickstart/MyFunct.java:6)
>  [JCCompilationUnit] package quickstart;… (/Users/zkuti/projects-new/jsweet-quickstart/src/main/java/quickstart/MyFunct.java:1)
>  java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to com.sun.tools.javac.code.Symbol$MethodSymbol
>  at org.jsweet.transpiler.Java2TypeScriptTranslator.substituteAssignedExpression(Java2TypeScriptTranslator.java:5639)
>  at org.jsweet.transpiler.Java2TypeScriptTranslator.visitVarDef(Java2TypeScriptTranslator.java:3265) 
> 

According to JSweet FAQ lambda is supposed to work. What am I missing here?

> Code having only MAX gives:
> Task :jsweet FAILED
> type ‘(arg0: any, arg1: any) => number’ is not assignable to type ‘MyFunct’ at /Users/zkuti/projects-new/jsweet-quickstart/src/main/java/quickstart/MyFunct.java(8)
> 

How can I get past these problems?
Thanks!

**Comment by lgrignon** [comment]
Hello. What version of JSweet are you running?

**Comment by tinca** [comment]
Hi,
What was given at the [gradle plugin](https://github.com/lgrignon/jsweet-gradle-plugin):
2.0.0-SNAPSHOT

Now, that you asked I checked JSweet's site and have seen that the Maven plugin is at 2.0.0-rc1.
So I tried this version number in gradle too. Now, it gives a different error message, however something is suspicious, because gradle refers to various artifacts with 2.2.0-SNAPSHOT, like
 jsweet-maven-plugin:2.2.0-SNAPSHOT
JSweet transpiler version 2.2.0-SNAPSHOT (build date: 2018-10-06 10:40:12)

This remained after having stopped gradle daemons and clean.

**Comment by lgrignon** [comment]
Hello, yes indeed we didn't properly released recently but the latest version you should be using is 2.2.0-SNAPSHOT. 
I will check your code sample tomorrow anyway, just in case I missed something.
Please tell me if problem is still there with 2.2.0-SNAPSHOT
Thanks for reporting.

**Comment by tinca** [comment]
Hi,
The current build file looks like:

`buildscript {
    repositories {
        mavenCentral()
        maven { url "http://repository.jsweet.org/artifactory/libs-release-local" }
        maven { url "http://repository.jsweet.org/artifactory/libs-snapshot-local" }
        maven { url "http://repository.jsweet.org/artifactory/plugins-release-local" }
        maven { url "http://repository.jsweet.org/artifactory/plugins-snapshot-local" }
        maven { url "http://google-diff-match-patch.googlecode.com/svn/trunk/maven" }
    }
    dependencies {
        classpath('org.jsweet:jsweet-gradle-plugin:2.2.0-SNAPSHOT') {
            transitive = true }
    }
}

apply plugin: 'java'
apply plugin: 'org.jsweet.jsweet-gradle-plugin'

version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url "http://repository.jsweet.org/artifactory/libs-release-local" }
    maven { url "http://repository.jsweet.org/artifactory/libs-snapshot-local" }
}

dependencies {
    compile group: 'org.jsweet', name: 'jsweet-core', version:'6-SNAPSHOT'
    compile group: 'org.jsweet', name: 'jsweet-transpiler', version:'2.2.0-SNAPSHOT'
    compile group: 'org.jsweet.candies.ext', name: 'angular', version:'1.4.0-SNAPSHOT'
    compile group: 'org.jsweet.candies.ext', name: 'angular-route', version:'1.2.0-SNAPSHOT'
    compile group: 'org.jsweet.candies.trusted', name: 'es6-promise', version:'0.0.0-SNAPSHOT'
}`

The QuickStart transpiles fine, my class gives the same error messages.

**Comment by lgrignon** [comment]
Ok, it should definitely work, I will take a look asap

**Comment by lgrignon** [comment]
Please see in attached commit: 
/transpiler/src/test/java/source/syntax/LambdaExpression.java

UT passes when adding @FunctionalInterface annotation

Could you please try this?

**Comment by tinca** [comment]
Hi,
Indeed, with this modification MyFunct transpiles fine.
Thanks for looking into it.

I have follow-up questions, but as this problem is solved this I won't do it here. I open a new one where I explain the details.
Thanks!
