### ISSUE TITLE
Make J4TS work with Gradle / JSweet 3

### ISSUE THREAD

**Issue by tinca** [cincheo/jsweet#491]
Hi,

The next attempt on transpiling JGraphT using j4ts found this:

> > Task :jsweet
> com.sun.tools.javac.jvm.ClassReader$BadClassFile: bad class file: /Users/zkuti/.gradle/caches/modules-2/files-2.1/org.jsweet/j4ts/0.5.0/9ae753cb73f7e61cd18c61037937bc95190bef0e/j4ts-0.5.0.jar(java/util/TreeMap$DescendingEntryIterator.class)
>   undeclared type variable: K
>   Please remove or make sure it appears in the correct subdirectory of the classpath.
> 	at com.sun.tools.javac.jvm.ClassReader.badClassFile(ClassReader.java:357)
> 	at com.sun.tools.javac.jvm.ClassReader.findTypeVar(ClassReader.java:948)
> 	at com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:653)
> 	at com.sun.tools.javac.jvm.ClassReader.sigToTypes(ClassReader.java:862)
> 	at com.sun.tools.javac.jvm.ClassReader.classSigToType(ClassReader.java:778)
> 	at com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:691)
> 	at com.sun.tools.javac.jvm.ClassReader.sigToTypes(ClassReader.java:862)
> 	at com.sun.tools.javac.jvm.ClassReader.classSigToType(ClassReader.java:778)
> 	at com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:691)
> 	at com.sun.tools.javac.jvm.ClassReader.sigToType(ClassReader.java:639)
> 	at com.sun.tools.javac.jvm.ClassReader.readType(ClassReader.java:562)
> 	at com.sun.tools.javac.jvm.ClassReader$13.read(ClassReader.java:1158)
> 	at com.sun.tools.javac.jvm.ClassReader.readAttrs(ClassReader.java:1381)
> 	at com.sun.tools.javac.jvm.ClassReader.readMemberAttrs(ClassReader.java:1371)

What can I do with this?
Thanks!

Ps. I have seen this reported on forum where the suggestion of switching to 2.2.0-SNAPSHOT did not help. I am on that version too.
Ps 2. I have seen that j4ts project's pom.xml uses JSweet and jsweet-maven-plugin 2.0.0 at present. Could this be the cause?

**Comment by lgrignon** [comment]
Hello @tinca 
Are you still using JSweet? Did you find a workaround? JSweet 3 is under preparation. It may help since it supports Java 11+
I may try to release next J4TS version for it so please tell me if you still need it.

**Comment by tinca** [comment]
Hi Louis,
This was as experiment on my behalf, and left unfinished when could not overcome this point. I would like to pick it up again, but no idea when I will have time for that. 
Thx!

**Comment by lgrignon** [comment]
Closing as moved to J4TS:
https://github.com/j4ts/j4ts/issues/56
