### ISSUE TITLE
candy-generator - unable to recover from previous error(s)... giving up!

### ISSUE THREAD

**Issue by marcuskaufmann** [cincheo/jsweet#493]
I try to convert [mithril](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mithril/index.d.ts) according to your [guide](https://github.com/cincheo/jsweet/blob/master/candy-generator/README.md) and get the following error

2018-10-18 22:55:00.000 INFO  TypescriptDef2Java:181 - parsing: node_modules\@types\mithril\index.d.ts
SYNTAX ERROR: '=' is not expected at '=' node_modules\@types\mithril\index.d.ts:66(32)
SYNTAX ERROR: '=' is not expected at '=' node_modules\@types\mithril\index.d.ts:176(24)
SYNTAX ERROR: '}' is not expected at '}' node_modules\@types\mithril\index.d.ts:193(2)
unable to recover from previous error(s)... giving up!

What do I wrong?

**Comment by lgrignon** [comment]
Hello,

Well it seems that you are not doing anything wrong. Apparently the candy generator doesn't support some of the latest TS defs constructs. Referring to your errors' lines, we learn that assignment in generics isn't supported: (from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mithril/index.d.ts)
```
interface RouteResolver<Attrs = {}, State = {}> 
```

I recommend you to fix those tiny issues you have directly in the .d.ts and then try again

**Comment by marcuskaufmann** [comment]
Thank's a bunch for your detailed explanation :+1:
