### ISSUE TITLE
TypeScript delegation performance improvements

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/jsweet#5]
Currently, TypeScript is used through command line processes, which is very inefficient. We can use a Nodejs server to compile with TypeScript and communicate through web services. It will most probably improve performances a lot.

**Comment by ui4j** [comment]
It might be better to use [J2V8](https://github.com/eclipsesource/j2v8) (Java Bindings for V8) instead of native process integration.

**Comment by renaudpawlak** [comment]
Definitely an option to investigate before starting developing...

**Comment by lgrignon** [comment]
Improved with the tsserver mode
