### ISSUE TITLE
Can't use Scanner and Random methods

### ISSUE THREAD

**Issue by PolskiSlimak** [cincheo/jsweet#502]
`package` quickstart;
import jsweet.util.Lang;

import static def.dom.Globals.alert;

import java.util.Random;
import static def.jquery.Globals.$;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import def.js.Array;

public class QuickStart {

	public static void main(String[] args) {
		System.out.println("Wisielec");
        Random generator=new Random();
        String slowo = "Kamil";
        Scanner scaner = new Scanner(System.in);
        char[] literki = slowo.toCharArray();
        char[] Str2 = new char[slowo.length()];      
        int wylosowana =generator.nextInt(slowo.length());
        for(int i = 0; i < slowo.length(); i++){
            
            literki[i] = '*';
            
        }
        System.out.println(literki);
        boolean dziala = true;
        while (dziala){
            System.out.println("Zgaduj!");
            String wybor = scaner.next();

            if(wybor.equals(slowo))
            {
                    System.out.println("gj!");
                    break;
            }

        }
	}

`}`

I don't really know why i can't commit this code it say's that cannot find namespace java even if i've imported nessesery tools.

**Comment by lgrignon** [comment]
Hello, Scanner class isn't supported natively by JSweet 2. If you absolutely need it, you may use https://github.com/j4ts/j4ts which brings a comprehensive Java support for JS.
Otherwise, a simpler solution would be to use a more browser-friendly workaround.

**Comment by lgrignon** [comment]
Hello @PolskiSlimak 
Did you succeed with j4ts?

**Comment by PolskiSlimak** [comment]
@lgrignon 
Actually i've dropped the whole idea of this solution and didnt check it with j4ts overall

**Comment by lgrignon** [comment]
Ok, I am sorry JSweet didn't suit your needs.
Thanks for trying.

I closed this issue then
