### ISSUE TITLE
LeafLet candy

### ISSUE THREAD

**Issue by pascalheraud** [cincheo/jsweet#505]
Hello,

We just made a leaflet candy.
https://github.com/LaRoueVerte/candy-leaflet

We would like to share it with the community.

**Comment by renaudpawlak** [comment]
Great! Thanks.

**Comment by pascalheraud** [comment]
How do we proceed ? :)

**Comment by lgrignon** [comment]
This is cool. If I grant you on the jsweet-candies, you will be able to transfer repository, and then we should mvn deploy it to the JSweet maven repo.

**Comment by renaudpawlak** [comment]
We can fork to jsweet-candies to make it official. But if you prefer to transfer it, then we can give you write access to the organization. As you wish. In any case we will take care deploying the candy to JSweet Maven repo (I don't know a way to allow a user to deploy a single artifact and it sounds too complicated)...

**Comment by renaudpawlak** [comment]
Just sent you an invitation :)

**Comment by lgrignon** [comment]
This now deployed: http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/jsweet/candies/leaflet/1.3.4-SNAPSHOT

Thanks a lot

**Comment by pascalheraud** [comment]
great !
