### ISSUE TITLE
Invalid code generated for new HashMap(initialCapacity)

### ISSUE THREAD

**Issue by octachrome** [cincheo/jsweet#508]
If you pass an initial capacity to the `HashMap` constructor, JSweet interprets the argument as another map where the values should be copied from. E.g., this generates invalid typescript:

    Map<String, Integer> map = new HashMap<>(100);

I will see if I can fix this and submit a PR.

**Comment by lgrignon** [comment]
Hello @octachrome , this is very nice if you can submit a PR.
We are working on a way of maintaining better the JSweet project since all maintainers only have a few time, but in the mean time, any help is welcome ;)

**Comment by lgrignon** [comment]
Hey @octachrome, any news on this?
It should be possible around here 
https://github.com/cincheo/jsweet/blob/develop/transpiler/src/main/java/org/jsweet/transpiler/extension/RemoveJavaDependenciesAdapter.java#L1105

**Comment by octachrome** [comment]
Sorry, the project I was working on with JSweet has been put on hold. I'm unlikely to fix this any time soon.
