### ISSUE TITLE
new Integer(char) interpreted wrongly

### ISSUE THREAD

**Issue by octachrome** [cincheo/jsweet#509]
If you pass a character to the `Integer` constructor, JSweet interprets this as a string instead of a char. E.g., this test passes in Java but fails in the transpiled JavaScript:

    assertEquals(new Integer('x').intValue(), 'x');

Generated JavaScript:

    assertEquals(new Number('x').valueOf() | 0), 'x'.charCodeAt(0));

This is incorrect because `new Number('x')` is `NaN`.

**Comment by lgrignon** [comment]
Good one, thanks!
