### ISSUE TITLE
annotation mapped method overloading

### ISSUE THREAD

**Issue by metrospiegel** [cincheo/jsweet#51]
It would be great for existing implementations/libraries (even though this is not the main purpose of JSweet) which cannot be structurally changed, to have the option of mapping diffrent method overloadings to diffrent method names. I know, it is not so easily implemented. Especially if it is done with some covenience considered. But would greatly benefit migrators.

**Comment by renaudpawlak** [comment]
Could you give an example? That would help me to make sure that I fully understand what you are saying. Is it related to issue #27 ? I would say it is very close.

**Comment by metrospiegel** [comment]
It concerns a same problem of me as #27 (EMF migration). Here my example:

@jsRename({"insertBooleanAt"})
void insertAt(int pos, Boolean val) { ... }
@jsRename({"insertStringAt"})
void insertAt(int pos, String val) { ... }

However, i just also discovered the instanceof limitation, which does not belong here but poses also a problem for what i want to do. So maybe the scope of JSweet is really diffrent than i thought and hoped. Which would make also my other posts obsolete.

**Comment by renaudpawlak** [comment]
Closed as redundant with issue #27

**Comment by lgrignon** [comment]
This discussion could join a bigger discussion which is the @Name annotation support. Even if the EMF  migration case is not the primary JSweet case, the @Name support for user methods is pretty interesting. Indeed, it could provide a powerful workaround for many situations, not only overloads but for instance some unsupported reserved java keywords (in the future).

It seems to me that it would not be complicated to implement but could solve some blocking situations.

What do you think about it?
