### ISSUE TITLE
Support CommonJS modules with ES6

### ISSUE THREAD

**Issue by octachrome** [cincheo/jsweet#510]
I am using JSweet to generate Node.js code. Node.js supports ES6 syntax and I would like to use it because I find it cleaner and easier to read. But Node.js only supports CommonJS modules and JSweet does not allow these two options at the same time:

    WARN  JSweetTranspiler:1404 - cannot use old fashionned modules with ES>5 target

Is it possible?

**Comment by lgrignon** [comment]
Yes, definitely. I don't see any restriction about removing this check.

**Comment by lgrignon** [comment]
Hey, this is now possible, please see
https://github.com/cincheo/jsweet-quickstart/blob/master/pom.xml#L69

**Comment by octachrome** [comment]
Awesome!
