### ISSUE TITLE
How to upload images from a server asynchronously with a Promise in JSweet.

### ISSUE THREAD

**Issue by DanieleCostamagna** [cincheo/jsweet#516]
I saw that using a Promise could be the best solution to upload an image asynchronously. I found a good piece of code in JavaScript to do this, but I didn't succeed in translating it in JSweet. Is there anyone that did something similar? Is there any better soluzion in JSweet?
P.S. Am I out of topic? Should we send here only issues?
```
function asyncImageLoader(url){
    return new Promise( (resolve, reject) => {
        var image = new Image()
        image.src = url
        image.onload = () => resolve(image)
        image.onerror = () => reject(new Error('could not load image'))
    })
}    

// then use it like this

var image = asyncImageLoader(url)


image.then( res => {
    console.log(res)
})
```

**Comment by DanieleCostamagna** [comment]
Thanks very much, Louis. Unfortunately I'm not expert enough to understand where to get def.es6 so I can't compile the example that you gave me. I hoped it was simpler to get an image from a server without using to many technologies. For example I'm not using json in my prototype (I know, it is strange to many people, but I don't use it).

**Comment by lgrignon** [comment]
Oh no, you can definitely do it with JSweet without JSON, it was just an example of how to use Promises with JSweet to easily turn your JS code into Java/JSweet code ;) 

I think maybe you dropped it since your last answer but please tell me if you give a try again.
