### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by DanDare2050** [cincheo/jsweet#519]
Hi I just followed the quickstart instructions for jsweet but my attempt to run "mvn generate-sources" fails. I'm not sure if its something I can fix at my end. I have rerun with -e and -X options and attached the output.

The first problem that arises looks to be this one one line 313: ERROR JSweetConfig:149 - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader

Apache Maven 3.6.0
Java version: 9.0.1
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

[BugReport20190322.txt](https://github.com/cincheo/jsweet/files/2994810/BugReport20190322.txt)

**Comment by lgrignon** [comment]
Hello,
Yes we apologize but recommended configuration for JSweet is Maven 3.5 / JDK 8 for now.

That being said, the jsweet-maven-plugin should work with Maven 3.6, it does not seem like too much trouble (compared to switching from Java 8 to 9 :))

**Comment by lgrignon** [comment]
Ok, I just tried with Maven 3.6, it works.
So, definitely a Java 9 related error.

I will rename your issue accordingly

**Comment by lgrignon** [comment]
Related to https://github.com/cincheo/jsweet/issues/482

**Comment by DanDare2050** [comment]
Cool, glad it wasn't something dumb I was doing. Sorry its a bug. Any ETA on the J9 fix or is it a low priority?

**Comment by lgrignon** [comment]
For now, it is low priority but more solid support may be coming soon for JSweet, letting hope of a possible future Java>8 compatibility!

**Comment by ar-bleiz** [comment]
Hi everyone,
Switched to Debian 10, jdk 8 is not available due to new licensing from oracle.

Thanks to adoptopenjdk website, I installed a JDK8 to compile my project.

Probably priority should be reevaluated as open JDK8 will disappear from Linux distributions.

 Ok to contribute if needed.

**Comment by lgrignon** [comment]
Hello @ar-bleiz 
Thanks for your contribution. I will try to plan this during next weeks

**Comment by izogfif** [comment]
I would suggest to update to at least Java 11 since it's the latest LTS release. It has more deprecated classes / methods removed compared to Java 9. Also, some classes that were previously shipped with Java installation were moved to external dependencies.
I think there is little point to fix build on Java 9 if it fails on Java 11.

**Comment by lgrignon** [comment]
@izogfif  Yes, sure, why not.

**Comment by lgrignon** [comment]
I intended to use `JavaCompiler `, and more specifically `CompilationTask.setProcessors` to replace formerly used Javac from com.sun.* 
https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/tools/JavaCompiler.CompilationTask.html#setProcessors(java.lang.Iterable)

What do you think about it?

**Comment by lucgirardin** [comment]
Hello Louis! Are you making progress on this front or do you need help?!?

**Comment by lgrignon** [comment]
Hello, thanks for asking. 
I found some time to give it a try and created a Java11 branch
https://github.com/cincheo/jsweet/tree/Java11

I will keep you informed here but it will require a lot of work and introduce breaking changes

**Comment by lgrignon** [comment]
That's nice. Project is now compiling, and first unit tests are passing.
I will try to fix all unit tests soon, it may be ready for december :)

**Comment by lucgirardin** [comment]
Getting sweet: Tests run: 354, Failures: 31, Errors: 10, Skipped: 12
You are certainly getting there ;-)

**Comment by lgrignon** [comment]
Yeay \o/

**Comment by lgrignon** [comment]
All unit tests are finally passing!! :) but transpiler is slower than before, I have to take a look.
But first, I will try to make examples pass with this.

**Comment by lucgirardin** [comment]
I gave a shot at the current 3.0.0-SNAPSHOT, which seems to already work pretty well except for the handling of the equals method, at least for generics. I get the following exception while trying to compile the class below:
```
internal transpiler error at /Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(13)
dumping transpiler's strack trace:
   [JCMethodInvocation] var1.equals(value... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(13,29))
   [JCUnary] !var1.equals(value... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(13,28))
   [JCReturn] return !var1.equals(value)... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(13,21))
   [JCBlock] {... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(12,24))
   [JCIf] if (var1 == null) {... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(10,17))
   [JCBlock] {... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(9,42))
   [JCMethodDecl] @Override()... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(8,13))
   [JCClassDecl] class  implements Condition<T>... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(7,57))
   [JCClassDecl] public class Iterables {... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(5,1))
   [JCCompilationUnit] package org.jsweet.examples.it... (/Users/luc/java/jsweet-examples/src/main/java/org/jsweet/examples/iterable/Iterables.java(1,1))
java.lang.ClassCastException: class com.sun.tools.javac.code.Symbol$TypeVariableSymbol cannot be cast to class javax.lang.model.element.TypeElement (com.sun.tools.javac.code.Symbol$TypeVariableSymbol is in module jdk.compiler of loader 'app'; javax.lang.model.element.TypeElement is in module java.compiler of loader 'platform')
        at org.jsweet.transpiler.extension.Java2TypeScriptAdapter.substituteMethodInvocation(Java2TypeScriptAdapter.java:1263)
        at org.jsweet.transpiler.extension.RemoveJavaDependenciesAdapter.substituteMethodInvocation(RemoveJavaDependenciesAdapter.java:490)
        at org.jsweet.transpiler.Java2TypeScriptTranslator.visitMethodInvocation(Java2TypeScriptTranslator.java:3721)
        at org.jsweet.transpiler.Java2TypeScriptTranslator.visitMethodInvocation(Java2TypeScriptTranslator.java:146)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
```
Here is the problematic class:
```package org.jsweet.examples.iterable;

import java.util.Iterator;

public class Iterables {
    public static <T> Iterable<T> exclude(final Iterable<T> original, T value) {
        return conditional(original, new Condition<T>() {
            @Override
            public boolean apply(T var1) {
                if(var1 == null) {
                    return var1 != value;
                } else {
                    return !var1.equals(value);
                }
            }
        });
    }

    public static <T> Iterable<T> conditional(final Iterable<T> original, final Condition<? super T> condition) {
        return new Iterable<T>() {
            @Override
            public Iterator<T> iterator() {
                return new Iterator<T>() {
                    Iterator<T> it = original.iterator();
                    T nextEntry = null;
                    boolean queryNext = true;

                    @Override
                    public boolean hasNext() {
                        if (queryNext) {
                            nextEntry = findNext();
                            queryNext = false;
                        }
                        return nextEntry != null;
                    }

                    @Override
                    public T next() {
                        if (queryNext) {
                            nextEntry = findNext();
                        }
                        queryNext = true;
                        return nextEntry;
                    }

                    private T findNext() {
                        while (it.hasNext()) {
                            T t = it.next();
                            if (condition.apply(t)) {
                                return t;
                            }
                        }
                        return null;
                    }

                    @Override
                    public void remove() {
                        throw new UnsupportedOperationException();
                    }
                };
            }
        };
    }

    public interface Condition<T> {
        boolean apply(T var1);
    }
}
```

**Comment by lgrignon** [comment]
Thanks for reporting.
There was an error indeed, which I fixed in my last commit (see above), but it's actually still failing because of generic nested anonymous classes. I think it was failing in JSweet 2 as well though. I will create an issue to fix it

**Comment by lgrignon** [comment]
Making [J4TS work with JSweet 3](https://github.com/cincheo/jsweet/issues/491) seems complicated IMHO. I've tried to play around with it without success.

**Comment by lgrignon** [comment]
So far, all those projects are migrated for JSweet 3:
✔️ https://github.com/cincheo/jsweet-examples/
✔️ https://github.com/cincheo/jsweet-quickstart
✔️ https://github.com/lgrignon/jsweet-examples-threejs
✔️ https://github.com/lgrignon/jsweet-jqueryui-example
✔️ https://github.com/lgrignon/jsweet-async-await-json-deserialization
✔️ https://github.com/lgrignon/jsweet-node-example
✔️ https://github.com/lgrignon/jsweet-node-example-fs
✔️ https://github.com/lgrignon/jsweet-node-example-simple-http

**Comment by lgrignon** [comment]
3.0.0-RC1 is now deployed!
https://github.com/cincheo/jsweet/releases/tag/3.0.0-RC1
https://github.com/lgrignon/jsweet-maven-plugin/releases/tag/3.0.0-RC1
https://github.com/lgrignon/jsweet-gradle-plugin/releases/tag/3.0.0-RC1

**Comment by lgrignon** [comment]
FYI the related J4TS migration issue: https://github.com/j4ts/j4ts/issues/56
