### ISSUE TITLE
Get JS from Jar files

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/jsweet#52]
The candy processor should be able to find and use the JS in the candies Jar files when available.

It should follow the Webjar conventions to package the JS code. So, programmers would be able to include the definitions and the JS code and it should work right away. Note that the JS file should probably be packaged for commonjs so that we can use the "bundle" option.

**Comment by lgrignon** [comment]
Great idea. Working on it.

**Comment by renaudpawlak** [comment]
Thanks for the PR Louis. It works well :)
