### ISSUE TITLE
org.jsweet:jsweet-transpiler:2.2.0 requires fr.opensagres.js:ts.core:1.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by nedtwigg** [cincheo/jsweet#520]
Looks like this in the pom:

```xml
		<dependency>
			<groupId>fr.opensagres.js</groupId>
			<artifactId>ts.core</artifactId>
			<version>1.4.0-SNAPSHOT</version>
		</dependency>
```

**Comment by lgrignon** [comment]
Thanks for noticing. 
Unfortunately, typescript.java 1.4.0 (which is fr.opensagres.js:ts.core) was never published on maven, and AFAIK, never released.
Please see https://github.com/angelozerr/typescript.java

Do you have something in mind to suggest?

**Comment by dodgex** [comment]
@lgrignon I just encountered the same and unfortunately we have a NO-SNAPSHOT-Policy. 

You guys could fork the repo/project and release that fork as e.g. `org.jsweet:ts.core` or integrate the code into the jsweet jar using https://maven.apache.org/plugins/maven-shade-plugin at build time.

**Comment by lgrignon** [comment]
Hello @dodgex 
I was thinking of doing such a thing. I will try to do it today

**Comment by lgrignon** [comment]
JSweet 2.3.1 is released, with no snapshot dependencies.
