### ISSUE TITLE
cant find node.js error eclipse plugin

### ISSUE THREAD

**Issue by shamwoo** [cincheo/jsweet#521]
windows 10 home version 10.0.17763.437
Eclipse IDE for PHP Developers
Version: 2019-03 (4.11.0)
Build id: 20190314-1200
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 1.8.0_201

**Comment by lgrignon** [comment]
Hello, thanks for reporting. This issue has been moved to the JSweet Eclipse plugin repo

**Comment by lgrignon** [comment]
@shamwoo do you want to try to upgrade the plugin and file a PR?

**Comment by shamwoo** [comment]
how would I do that, im still new to all this
