### ISSUE TITLE
cannot find name 'java'

### ISSUE THREAD

**Issue by pedy711** [cincheo/jsweet#525]
When I try to transpile Java Regex like the following code:

    Pattern pattern = Pattern.compile ("");

I get the following output:
 ```
INFO  TypeScript2JavaScriptWithTscTranspiler:90 - quickstart/IP4Address.ts(11,53): error TS2304: Ca
nnot find name 'java'.
2019-05-04 11:52:59.059 ERROR output:55 - cannot find name 'java' at C:\Users\pedra\git\jsweet-quickstart\src\main\java\qui
ckstart\IP4Address.java(12)
```

**Comment by lgrignon** [comment]
Hello again. JSweet does not intend to support the whole Java API. Please take a look at j4ts which could interest you.
