### ISSUE TITLE
External library import fails

### ISSUE THREAD

**Issue by qualitesys** [cincheo/jsweet#528]
I would like to port a complete java project. 
An external library (org.apache.maven.plugin) is not recognized.
What is the procedure to add it as a candy ?
Thanks for your help

PS : I use version 2.3.0-SNASHOT

**Comment by lgrignon** [comment]
Did you see https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#generating-jsweet-candies-from-existing-typescript-definitions

and

https://github.com/cincheo/jsweet/tree/develop/candy-generator

?

**Comment by lgrignon** [comment]
Hello @qualitesys. Any news on this?
