### ISSUE TITLE
how can i check window.somecustomproperty in jsweet?

### ISSUE THREAD

**Issue by aneer-anwar** [cincheo/jsweet#534]
I have a question which may be simple but I can't figure it out. how can i check window.somecustomproperty in jsweet?

**Comment by lgrignon** [comment]
Like in JS, please use hasOwnProperty

Please close issue if ok for you

**Comment by aneer-anwar** [comment]
Oh silly me! . 'hasOwnProperty' solved my issue. Thanks a lot for the quick response.
