### ISSUE TITLE
How to Learn the Principle of jsweet and Add New feature？

### ISSUE THREAD

**Issue by qinkaiyuan** [cincheo/jsweet#536]
Hello, I want to learn the principles of jsweet and try to add some new feature. What should I do? I want to write jsweet like Vue for js.

Create a new file format in which you can write both HTML and Java and CSS.

Like this    D:\Hello.jsweet ，A new file format called jsweet

```
<template>
	<div id="hello">
		{{hello}}
	</div>
</template>

<java>
public class HelloWorld extends JavaView{
    private String hello = "hello world";
}
</java>

<style scoped lang="scss">
 #id{
    font-size:36px;
}
</style>

```
Then compile the file into JS and HTML and CSS through maven

But I don't know how to start. I read doc, but I haven't found anything about the principle. Can you tell me how to start learning jsweet principle and where to learn jsweet principle? Thank you.

**Comment by lgrignon** [comment]
Hello,
First of all let me tell you that I think this is a great idea, there is AFAIK no such thing existing.
This will however require a huge work to do so. 
It would be great to write your runtime in JSweet so you could interact with existing JS tools such as vue.js, mustache js
If you want to learn about JSweet, the first place to look is http://www.jsweet.org/ 
More specifically, you will find:

- [FAQ](http://www.jsweet.org/faq/)
- [Language specs](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md)
- [Papers & Publications](http://www.jsweet.org/papers-and-publications/)

I think the following may also be very useful for you:
- [JSweet examples](http://www.jsweet.org/examples/)
- [JSweet maven plugin implementation](https://github.com/lgrignon/jsweet-maven-plugin)
- [JSweet online sandbox implementation](https://github.com/lgrignon/jsweet-live-sandbox)
