### ISSUE TITLE
Released maven-plugin cant be found in artefactory('plugins-release-local') while snapshots can in ('plugins-snapshot-local')

### ISSUE THREAD

**Issue by HenningL** [cincheo/jsweet#538]
The maven-plugin doesnt get published when released. Using the latest SNAPSHOT of the maven plugin, than doesnt find the transpiler of this SNAPSHOT version. Makes it bit complicated to use it OOTB

**Comment by lgrignon** [comment]
Hey,
You can find stable release versions here:
http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/plugins-release-local/org/jsweet/jsweet-maven-plugin/2.3.0/jsweet-maven-plugin-2.3.0.jar
http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-local/org/jsweet/jsweet-transpiler/2.3.0/jsweet-transpiler-2.3.0.jar

and latest snapshot versions here:
http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/jsweet/jsweet-transpiler/2.3.1-SNAPSHOT
http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/plugins-snapshot-local/org/jsweet/jsweet-maven-plugin/2.3.1-SNAPSHOT

I think everything is there. What do you suggest?

**Comment by HenningL** [comment]
Thanks, dont know which old tutorial i followed.
