### ISSUE TITLE
Copy constructor for ArrayList does not work

### ISSUE THREAD

**Issue by Icare67** [cincheo/jsweet#539]
In the following example , I expect `a2` to be a copy of `al`. But it creates an array of array.
```java
public static void test()
	{
	        ArrayList<String> al = new ArrayList<String>();
		al.add("foo");
		al.add("bar");
		ArrayList<String> a2 = new ArrayList<String>(al);
		assert al.size() == a2.size();
	}
```

**Comment by lgrignon** [comment]
Thanks @Icare67 for reporting those bugs.
Would you have time to contribute a bit? I will try to fix as much as possible

**Comment by lgrignon** [comment]
Sorry, but I cannot reproduce your problem. Please see
https://github.com/cincheo/jsweet/commit/7fd8496dc357f0c273f8f35c55b7335b4451f351

Which version of JSweet are you using?

**Comment by lgrignon** [comment]
Please reopen if problem still occurs with last version of JSweet

**Comment by Icare67** [comment]
I'm using
" JSweet transpiler version 2.3.0-SNAPSHOT (build date: 2019-05-01 10:19:57)"
