### ISSUE TITLE
Double not converted to double

### ISSUE THREAD

**Issue by Icare67** [cincheo/jsweet#542]
Double is not unboxed even if unboxing is called explicitly.
```java
double a = 1;
Double d = new Double(1);
double b = d.doubleValue();
if (a!=b)
{
	System.err.println("Houston we have a problem");
};
```

**Comment by lgrignon** [comment]
Hello, 
I cannot reproduce https://github.com/cincheo/jsweet/commit/8a68a70555afd66e5399a880ee957776e5263fff

Are you using J4TS please?
