### ISSUE TITLE
Transpilation issue with `super`

### ISSUE THREAD

**Issue by lapo-luchini** [cincheo/jsweet#544]
This could be a duplicate of #147 but as far as I can read there it was just side-stepped.

I generated a minimal test-case that fails:

```Java
public class Test extends HashMap<String, Object> {
    
    public Test() {
    }
    
    @Override
    public boolean containsKey(Object key) {
        return get(key) != null;
    }

    @Override
    public Object get(Object key) {
        Object o = super.get(key);
        if ("null".equals(o))
            return null;
        return o;
    }

}
```

and fails like this:
```
$ gradle jsweet
[…]
> Task :jsweet FAILED
'super' must be followed by an argument list or member access at /home/lapo/svn/java/pdf.parser/trunk/java2js.minimal/t/src/main/java/Test.java(15)
```

Using `tsOnly` hides the error, but the produced TS still fails to compile with the same error, and the code indeed looks strange, with `super` used like a variable name:
```TypeScript
    public get(key : any) : any {
        let o : any = /* get */((m,k) => m[k]===undefined?null:m[k])(super, key);
        if(/* equals */(<any>((o1: any, o2: any) => { if(o1 && o1.equals) { return o1.equals(o2); } else { return o1 === o2; } })("null",o))) return null;
        return o;
    }
```
Full test-case:
[super.zip](https://github.com/cincheo/jsweet/files/3690068/super.zip)

**Comment by lgrignon** [comment]
Hello,
This seems to be a nice one, thanks for reporting!

I will take a look

**Comment by lgrignon** [comment]
It is fixed (added a unit test) and deployed on Maven / Gradle repo

**Comment by lgrignon** [comment]
2.3.5-SNAPSHOT

**Comment by lapo-luchini** [comment]
I tried `2.3.6-SNAPSHOT` and it worked, thanks!
