### ISSUE TITLE
Angular 6/8 Question

### ISSUE THREAD

**Issue by mfreeman-xtivia** [cincheo/jsweet#553]
So i have a new project to write that requires minimally Angular 6, but preferably A8. I would love to try and use JSweet for this project, but that leads me to the following questions:

- Should i use the existing A2 candy and massage any issues that come up?
- If no, should i use the candy generator to build my own candy for A6/A8?
- Something else altogether?

**Comment by gochev** [comment]
I would suggest candy generation for completely new candies.

**Comment by lgrignon** [comment]
Hello,
@gochev is right, it is sometimes good to try candy generation, but I think in this case it would be better to start from existing candy for several reasons :
1) candy generation has not been updated for more ~ 2 years, and TypeScript definition files format evolves fast so chances are the current tool is not up to date to handle Angular 8's TS definitions.
2) you have a working example of an Angular 2 project with JSweet. It could be easier to start from here.

Anyway, it would be super nice to see a working example of Angular 8 + JSweet! Please keep us informed! :)

Maybe you could try to generate candy with candy generation tool and see how many errors you get. 
For most of the candies I created, I used the candy generation tool to perform 90% of the job, and fixed remaining errors by myself.

**Comment by mfreeman-xtivia** [comment]
I appreciate all thats been done so far but i will probably have to try something else right now as my current schedule does not permit that kind of investment of time right now. :-(
