### ISSUE TITLE
Ancient version of tsc

### ISSUE THREAD

**Issue by lucgirardin** [cincheo/jsweet#561]
Is there a compelling reason why JSweet still relies on an somewhat ancient version of tsc (2.1). One of my transpiled file does not compile with that version, while it compiles just fine with the latest (3.7.4)!

**Comment by lgrignon** [comment]
Hey, the backing typescript transpiler has not been upgraded since 2.1 for stability sake, but we could consider upgrade it for JSweet 3.1
Would you want to try to do it as a contribution?

**Comment by lgrignon** [comment]
Fixed with: 
https://github.com/cincheo/jsweet/pull/560
