### ISSUE TITLE
Not handling valid Java "function" variable name

### ISSUE THREAD

**Issue by rgladwell** [cincheo/jsweet#582]
Using the latest JSweet transpiler (2.3.7) getting  compilation errors for valid Java a bit like this:

```
ERROR: identifier expected. 'function' is a reserved word that cannot be used here at itext7/kernel/src/main/java/com/itextpdf/kernel/pdf/function/PdfFunction.java(58)
```

With the following code:

```java
            for (PdfFunction function : functions)
                array.add(function.getPdfObject());
```

Workaround: Renaming the variable name resolves this compilation issue.

Note: `function` is a reserved keyword in JavaScript.

**Comment by lgrignon** [comment]
Thanks for reporting, it will be fixed.

**Comment by rgladwell** [comment]
Thanks!

**Comment by lgrignon** [comment]
@renaudpawlak did you deploy a snapshot version?

**Comment by lgrignon** [comment]
Okay, just did it. 2.3.8-SNAPSHOT is up to date

**Comment by rgladwell** [comment]
I'm getting a similar error for this, despite the fact I think you did fix this. When I compile this file using the latest SNAPSHOT:

https://github.com/ink-elements/itext7-js/blob/master/itext7/kernel/src/main/java/com/itextpdf/kernel/pdf/function/PdfFunction.java

With the following error:

```ERROR: identifier expected. 'function' is a reserved word that cannot be used here at itext7/kernel/src/main/java/com/itextpdf/kernel/pdf/function/PdfFunction.java(58)
ERROR: identifier expected at itext7/kernel/src/main/java/com/itextpdf/kernel/pdf/function/PdfFunction.java(58)```

**Comment by lgrignon** [comment]
Hello again @rgladwell 
3.0.0-RC4 has been deployed (and maven plugin is up to date) if you want to give it a shot
Warning : if you declare jsweet-core as a dependency, groupId is now `<groupId>org.jsweet.v3</groupId>`

I hope it will work for you 🤞

**Comment by rgladwell** [comment]
Thanks @lgrignon.

I can't seem to find the `3.0.0-RC4` dependency:

```
  <dependencies>
    <dependency>
      <groupId>org.jsweet.v3</groupId>
      <artifactId>jsweet-core</artifactId>
      <version>3.0.0-RC4</version>
    </dependency>
  </dependencies>
```

Which repo/dependency should I be using? Is the transpiler bundled in the core package now?

**Comment by lgrignon** [comment]
jsweet-transpiler is 3.0.0-RC4
jsweet-core is 6.0.0 (meaning it's es6+ api)

**Comment by rgladwell** [comment]
Trying: 

```xml
  <dependencies>
    <dependency>
      <groupId>org.jsweet.v3</groupId>
      <artifactId>jsweet-transpiler</artifactId>
      <version>3.0.0-RC4</version>
    </dependency>
  </dependencies>
```

But it still won't resolve

**Comment by lgrignon** [comment]
<groupId>org.jsweet</groupId>

sorry for the (temporary) inconvenience

**Comment by rgladwell** [comment]
Thanks, this seemed to fix this issue.

**Comment by rgladwell** [comment]
Unfortunately, there is a further error:

https://github.com/cincheo/jsweet/issues/624

**Comment by lgrignon** [comment]
I close this one, we will focus on https://github.com/cincheo/jsweet/issues/624
