### ISSUE TITLE
Conditional Code Transpilation Support

### ISSUE THREAD

**Issue by tomansill** [cincheo/jsweet#586]
Hi,

First of all, this project looks awesome and I am looking forward to use it in my project. I have a question about JSweet transpilation.

I am wondering if it's possible to have conditional branching on what code to be transpiled to JS. 

My issue is that I want to have methods that have 2 versions where one will be run on client-side in browser with javascript and one run on server-side in Java.

I think this feature will benefit us as it can allow us to implement server-side rendering functionality in Java and get 'free' client-side rendering functionality.

Example:
  - method that manipulates DOM
     - client: manipulates DOM in usual ways using browser's DOM model
     - server: manipulates instanced JSoup's DOM inside server
  - method that retrieves data
    - client: uses XMLHttpRequest to fetch data from server at API endpoint
    - server: simply access data from inside of server

Is this possible in JSweet? If so, can you point or provide examples on how to do so?

Thank you

**Comment by renaudpawlak** [comment]
JSweet is highly extensible and you can have different configurations or adapters to tune the behavior. Also, an alternative is to have your method to switch at runtime on an environment variable. If you still believe that some feature is missing, please provide a more concrete minimalist example and explain what would be missing exactly.

**Comment by renaudpawlak** [comment]
BTW, here is a pointer on the documentation to extend JSweet behavior: https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#extending-the-transpiler

**Comment by lgrignon** [comment]
Hello @tomansill 
Did you manage to accomplish what you had in mind?
