### ISSUE TITLE
Double.isFinite(0.1); fails to compile

### ISSUE THREAD

**Issue by keithphw** [cincheo/jsweet#591]
Hi,
I noticed that this method fails to compile. 
`Double.isFinite(0.1);`

It's unusual since Double.isInfinite(0.1) works fine.

I'm using this version of JSweet in my POM:
```
<jsweet.transpiler.version>3.0.0-RC3</jsweet.transpiler.version>
<jsweet.core.version>6.2.0</jsweet.core.version>
```
Thanks for your help.
Cheers,
Keith

**Comment by lgrignon** [comment]
Will be fixed in RC5

**Comment by lgrignon** [comment]
(and 2.4.0 just for information)
