### ISSUE TITLE
Support declarations generation with modules

### ISSUE THREAD

**Issue by lgrignon** [cincheo/jsweet#60]
Declarations are only partially generated while using module mode. The package tree of directories is generated with a module.d.ts in each of those directories BUT the root module.d.ts is missing.
Ex:
tsdeclarations/
&nbsp;&nbsp;org/
&nbsp;&nbsp;&nbsp;&nbsp;module.d.ts	
&nbsp;&nbsp;&nbsp;&nbsp;jsweet/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module.d.ts
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...

The root module.d.ts in tsdeclarations is missing.

**Comment by renaudpawlak** [comment]
This seems to be working now (at least for me). I assume it was fixed as a side effect when working on the ``@Root`` annotations... If it is not working, please be more specific about your configuration.
