### ISSUE TITLE
Support for string enums

### ISSUE THREAD

**Issue by basti-schneider** [cincheo/jsweet#607]
For our project it would be useful to have the support for generating [string enums](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) in typescript.

I've added the functionallity in my fork and created a pull request: #606

**Comment by lgrignon** [comment]
And it was merged :) Thanks for contributing!

**Comment by basti-schneider** [comment]
Hi @lgrignon, is there a plan for a new release?

**Comment by lgrignon** [comment]
There is a 2.4.0 underway, yes, but no specific target date.

However, JSweet 3 should be released soon, by octobre I'd say.

Would you be using JSweet 2.x ou JSweet 3 (Java 11+)?

**Comment by basti-schneider** [comment]
Okay thanks, so we wait for 2.4.0 ;)
We are using JSweet 2.x at the moment.
