### ISSUE TITLE
JSweet 3 (Java 11) : bug with extensions

### ISSUE THREAD

**Issue by erezws** [cincheo/jsweet#611]
Hi,
We are using Jsweet version 2.0.0, With Java 1.8.
now upgrading our Java to 11, and the Jsweet to the current latest version (3.0.0-RC3)
we ran into a problem using our Adapter, we receive 2 Errors.
"local extensions are not supported in this environment, please use a packaged extension"
"fail to initialize extension classpath".
the Adapter is configured by the spec, is there any change about that in version 3.X.X?
thank you

**Comment by lgrignon** [comment]
Hi @erezws 
That's very interesting, thanks a lot for reporting.
Could you please link a small repro repo or zip?
I will try asap to fix it!

**Comment by lgrignon** [comment]
I am sorry I cannot reproduce.

Are you using maven plugin? Which exact versions of Java / JSweet maven plugin please?

**Comment by lgrignon** [comment]
Hello again @erezws 
3.0.0-RC4 has been deployed (and maven plugin is up to date) if you want to give it a shot
Warning : if you declare jsweet-core as a dependency, groupId is now `<groupId>org.jsweet.v3</groupId>`

I hope it will work for you 🤞

**Comment by lgrignon** [comment]
3.0.0-RC5 is deployed, please test it on this version.
groupId is org.jsweet.v3 for almost all artifacts now (please see pom.xml & build.gradle here: https://github.com/cincheo/jsweet-examples)
