### ISSUE TITLE
Fail to convert byte[] to typed array

### ISSUE THREAD

**Issue by thomasAtToem** [cincheo/jsweet#615]
By default , jsweet  converts java arrays to standard js array. I tried several tricks to convert byte[] to a type uint8array but failed. What would be the proposed way of doing this (and not changing the java code). 

thanks,
thomas

**Comment by lgrignon** [comment]
Hello @thomasAtToem 
You are probably looking for a custom adapter: https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#extending-the-transpiler
Did you check this out?

If you want to share your adapter, which could be useful to the community, you could add your class here https://github.com/cincheo/jsweet/tree/develop/transpiler/src/main/java/org/jsweet/transpiler/extension and PR

**Comment by thomasAtToem** [comment]
thanks for the input !
