### ISSUE TITLE
Easier iteration on object (maps)

### ISSUE THREAD

**Issue by lgrignon** [cincheo/jsweet#62]
For now, we need to use jsweet.lang.Object.keys() or for ... in with Object.hasOwnProperty which is very painful, like in Javascript :)

We could provide a better way of iterating through object, like myObject.forEach or myObject.iterate:

``` java
jsweet.lang.Object o;
o.each((Tuple<String, Object> entry) -> {
  console.log("key=" + entry.$0 +  " value=" + entry.$1);
});
```

``` typescript
var o: Object;
for (var key in o) {
  if (o.hasOwnProperty(key)) {
    var entry = { "$0": key, "$1": o[key] }; // Or directly replace later call to $0 / $1 with key / o[key]
    console.log("key=" + entry.$0 +  " value=" + entry.$1);
  }
}
```

**Comment by renaudpawlak** [comment]
Currently, iteration on properties can be done this way:

```
jsweet.lang.Object o;
for(String key : jsweet.lang.Object.keys(o)) -> {
  console.log("key=" + key +  " value=" + o.$get(key));
});
```

I am not sure that it is worth introducing a new non-standard way to iterate on object properties. It may even become redundant with future JS features... Careful discussion should be done before introducing such features.

**Comment by lgrignon** [comment]
ECMA specifications could indeed surprisingly introduce a proper way to iterate through objects but I'm not sure since the advanced version of the ECMA specifications.
That being said, iterating on an object in Javascript is not that painful, however I don't feel this way in JSweet because of the $get call, which I try to avoid when possible. Yet, I'm iterating on objects pretty often :)

**Comment by ssatguru** [comment]
maybe implement java.util.map or jsweet.util.Map/jsweet.lang.Map ?
