### ISSUE TITLE
@Root annotation is ignored when the 'module' output is turned on

### ISSUE THREAD

**Issue by angexis** [cincheo/jsweet#63]
To reproduce:
1. create a package org.foo.bar with a class FooBar.java
2. Add a `@jsweet.lang.Root ` annotation on the package
3. Run the jsweet transpiler w/o the module option
=> observe how the generated FooBar.ts directly under the root output folder (as expected)
4. Now turn on the module output (for instance using `module = 'amd'` in the gradle options)
=> observe how this time FooBar.ts is located under a org/foo/bar sub-folder

**Comment by renaudpawlak** [comment]
This issue is actually closely linked to #64. Shall resolve both at a time.

**Comment by renaudpawlak** [comment]
Now the ``@Root`` annotation is not ignored, but you can have only one ``@Root`` annotation, as explained with mode detail at #64.
