### ISSUE TITLE
StringBuilder performance

### ISSUE THREAD

**Issue by norzak** [cincheo/jsweet#637]
The code generated for StringBuilder append makes use of concat method which is a very slow operation. It would make it more agile if we use '+' operator for simple appends which is much faster than concat.

		StringBuilder a=new StringBuilder();
		a.append("Hi");
		a.append(" there");

from
```
      var a = { str: "", toString: function () { return this.str; } };
                /* append */ (function (sb) { sb.str = sb.str.concat("Hi"); return sb; })(a);
                /* append */ (function (sb) { sb.str = sb.str.concat(" there"); return sb; })(a);
```
to
```
      var a = { str: "", toString: function () { return this.str; } };
                /* append */ (function (sb) { sb.str += "Hi"; return sb; })(a);
                /* append */ (function (sb) { sb.str += " there"; return sb; })(a);

```

**Comment by lgrignon** [comment]
Hello @norzak 
Thanks for your suggestions. Sounds like a good idea indeed given [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat#Performance).
Would you like to try to add this improvment and PR? I think you will find this in RemoveJavaDependenciesAdapter

**Comment by norzak** [comment]
https://github.com/cincheo/jsweet/pull/638

**Comment by lgrignon** [comment]
Perfect, thanks
