### ISSUE TITLE
document.getElementsByClassName return type definition

### ISSUE THREAD

**Issue by stephdz** [cincheo/jsweet#649]
https://github.com/cincheo/jsweet/blob/1b3a4fd5f7d2e33288c5acf4de03a8db63d2e0c0/core-lib/es6/src/main/java/def/dom/Document.java#L665

Using jsweet I get this kinds of errors : `type 'HTMLCollectionOf<Element>' is not assignable to type 'NodeListOf<Element>'`

As you can see below, getElementsByClassName should return an HTMLCollectionOf<Element> : 
https://github.com/microsoft/TypeScript/blob/9ba45fcaace07510ef259d4cda2bc5ec523cf6d1/lib/lib.dom.d.ts#L4897

**Comment by lgrignon** [comment]
Thanks @stephdz for reporting. You can enhance jsweet-core definitions any time you want, and PR. We will be glad to review & merge it, then deploy it to the next minor version :)

**Comment by renaudpawlak** [comment]
I think you can also try to use lib-core 5. If it works, maybe you can check how it is done in core lib 5 and report it on core lib 6 if you have the time :)

**Comment by lgrignon** [comment]
fixed and deployed in core 6.3.1
