### ISSUE TITLE
Javascript to Java ?

### ISSUE THREAD

**Issue by eix128** [cincheo/jsweet#657]
Hi , i want to convert and use javascript library in java.
I did not find any Good solution.
I can use javascript in GraalVM Like this:

    public static void main(String[] args) {
        Context polyglot = Context.create();
        Value array = polyglot.eval("js", "[1,2,42,4]");
        System.out.println(array.getArrayElement(2).asInt());
    }

But i need to use all library as
polyglot.eval
is there anything jsweet can do for that ?

can i use javascript library with high performance java ?
I dont want any VM.
Well if i need VM like GraalVM , is there any wrapper that generates all javascript function calls for java ?

**Comment by renaudpawlak** [comment]
Nope, JSweet is Java to TypeScript/JavaScript only. Thank you for asking and good luck in your search!
