### ISSUE TITLE
Referencing a static method from the same object is not transpiled correctly

### ISSUE THREAD

**Issue by angexis** [cincheo/jsweet#67]
A code like
```
class Foo {
    public static void foo() {
    }
    public static void bar() {
        foo();
    }
```
Will yield an error of `foo` not being known.
Following code is required to work properly:
```
class Foo {
    public static void foo() {
    }
    public static void bar() {
        Foo.foo();
    }
```
More context can be found [here](https://bitbucket.org/jvorwerk/orientbase/src/fdf0f1ea671a055c183c5709c13d6c3fab6c47f8/src/main/java/org/orientbase/shared/YHydrater.java?at=default&fileviewer=file-view-default#YHydrater.java-59) if required.

**Comment by renaudpawlak** [comment]
The code you show in the issue works. However, in the link you provide, the method you use have a type parameter. This is a derivative of bug #47, but for static method accesses having type parameters. So I am closing this one and copying your link to the original issue.
