### ISSUE TITLE
jsweet-candy-js-quickstart no longer builds

### ISSUE THREAD

**Issue by Scoder12** [cincheo/jsweet#686]
I'm trying to make my own JS candy but I can't seem to get the example to build. I opened [an issue](https://github.com/cincheo/jsweet-candy-js-quickstart/issues/4) on that repo but I haven't gotten any response so I thought I'd open one here. 

I have tried this on multiple versions of java with no success, I'd love to have some insight on how I can get this working.

**Comment by lgrignon** [comment]
Hello @Scoder12 
we did not notive your issue on the other repo. It seems rather obsolete by the way.

I suggest that you rely on this repo which is really really more up to date: https://github.com/lgrignon/jsweet-candy-example

**Comment by Scoder12** [comment]
Thanks
