### ISSUE TITLE
Broken URL on http://sandbox.jsweet.org/

### ISSUE THREAD

**Issue by jarble** [cincheo/jsweet#699]
When I ran a compiled Java program on the [sandbox page](http://sandbox.jsweet.org/), the page tried to load a JavaScript library from a broken URL (http://sandbox.jsweet.org/js/j4ts-0.3.0-SNAPSHOT/bundle.js).

Is it possible to fix this broken URL, so that the sandbox will work correctly again?

**Comment by lgrignon** [comment]
This should be fixed. Could you please try again?

**Comment by jarble** [comment]
Yes, it was fixed in the last update.
