### ISSUE TITLE
More efficient Getting Started

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/jsweet#7]
We need a project template so that developers can start with JSweet very quickly through Maven... the getting started doc needs to be rewritten to reflect this change.

**Comment by sekaijin** [comment]
Hi,

I think the Getting started is much too brief.

executing maven is finished with a sucess
but the opening in chrome of index.html, generates an exception.
QuickStart.js 52 Uncaught Error: invalid overload

As there is no explanation of what should be the example, it is impossible for a beginner to go further.

A+JYT

**Comment by renaudpawlak** [comment]
I am sorry but this is a mistake. I have commited it by error. Thanks for reporting. I will fix asap.

**Comment by renaudpawlak** [comment]
Ok. I was testing a complex overriding bug with JSweet and I guess I committed my test by mistake 4 weeks ago without noticing :( Thank you so much for telling me. I think it should work again now.
