### ISSUE TITLE
Sandbox doesn't handle charCode 160 (non breaking space).

### ISSUE THREAD

**Issue by tdebroc** [cincheo/jsweet#70]
http://www.jsweet.org/jsweet-live-sandbox/ doesn't handle charCode 160.
If you put char 160 which is " " the Java won't compile.
Error " is  illegal start of expression" so very hard to detect
It looks like an empty space but it's non breaking space. So it's very hard to detect where the bug come from. Eclipse or other IDE handle it bu replacing it with a real space " ".
Best regards
Thibaut

**Comment by renaudpawlak** [comment]
This is out of scope. Sandbox is now open source and can be modified if necessary.
Anyway, if you want in-browser Java, check out https://www.javapoly.com/ or http://doppiojvm.org/. Clearly, it is not JSweet purpose to emulate Java on top of JS.
