### ISSUE TITLE
Simple way to convert Java source

### ISSUE THREAD

**Issue by stefan-reich** [cincheo/jsweet#700]
Hi. I don't understand your deployment system. Let's say I have one long .java file and want it converted to .js on the command line. How would I do this.

**Comment by lgrignon** [comment]
Did you please refer to the documentation? It clearly points to the quick start
http://www.jsweet.org/getting-started/

**Comment by stefan-reich** [comment]
@lgrignon Thank you. What I ultimately want to do is run JSweet without Maven. Can I do this by running JSweetCommandLineLauncher after building an example project?

**Comment by lgrignon** [comment]
Please, discover here an example using JSweetCommandLineLauncher (wrapped in an Ant script)
https://github.com/cincheo/jsweet-examples/blob/master/build.xml#L27

**Comment by stefan-reich** [comment]
Sounds good, thanks a lot. Will try that.

**Comment by lgrignon** [comment]
Yes, Maven is just amazing sometimes :)
Anyway, it's clearly possible to transpile with command line without maven or gradle if you need it, so please get back to us if you are stucked again in the future
