### ISSUE TITLE
JSweet Live sandbox is unavailable

### ISSUE THREAD

**Issue by gregdingle** [cincheo/jsweet#706]
See http://www.jsweet.org/jsweet-live-sandbox/

```
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

![image](https://user-images.githubusercontent.com/28797/138598819-a09d9b8c-1067-4fcc-9d99-427dbe58a6a9.png)

**Comment by lgrignon** [comment]
For now it's fixed through HTTP http://sandbox.jsweet.org/ 

HTTPS will be available soon

**Comment by lgrignon** [comment]
Fixed
