### ISSUE TITLE
Division should produce integer results on integer variables

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/jsweet#71]
int i = 3;
i/2; // 1 and not 1.5
float f = 3;
int j = (int)f/2; // 1 and not 1.5
j = (int)(f*1.5); // 7

**Comment by vivekg13186** [comment]
Hi even for floating point I am getting zero example code gen for a double asignment
rl.angle = (360 * ((i / size |0)));

**Comment by renaudpawlak** [comment]
Can you show original Java code, and all variable Java types (angle, i, size)? Then could you please show a couple of wrong assigned values and what would be the expected results? Thanks for you help.

**Comment by vivekg13186** [comment]
Java code
```
public static void test() {
		int b = 100;
		double c = 90/b;	
	}
	
	public static void testw() {
		int b = 100;
		double temp =90;
		double c = temp/b;	
	}      

```
Generated code 

```
  static test() {
            let b = 100;
            let c = (90 / b | 0);
        }
        static testw() {
            let b = 100;
            let temp = 90;
            let c = temp / b;
        }
```

 'test' function is generating zero as it got a int value in the expression
 'testw' function works as I replaced the value '90' with variable
