### ISSUE TITLE
question about @Ambient

### ISSUE THREAD

**Issue by ssatguru** [cincheo/jsweet#82]
I have a javascript class - Colorpicker
It has a constructor and a single method called setRGB
How would I define this using @Ambient
Tried the following

```java
@Ambient
class  ColorPicker extends jsweet.lang.Object {
	public ColorPicker(HTMLElement e, TriConsumer<Object, Object, RGB> f){}; 
        public void setRGB(RGB rgb){};
}

class RGB {
	double r;
	double g;
	double b;

}
```
I get the following compilation error
```
ERROR: method 'setRGB' cannot define a body in interface 'ColorPicker' 
```
If i remove the method and just leave the constructor it works

**Comment by renaudpawlak** [comment]
Just use the ``native`` keyword (when you think of it, it makes sense to use it).

```java
@Ambient
class  ColorPicker extends jsweet.lang.Object {
    public ColorPicker(HTMLElement e, TriConsumer<Object, Object, RGB> f) {}; 
    public native void setRGB(RGB rgb);
}

class RGB {
    double r;
    double g;
    double b;
}
```

Maybe you also want to define RGB as an ambient an/or and ``@Interface``.
I will add some indication for using the ``native`` modifier in the error message.

**Comment by ssatguru** [comment]
That worked. Nice!
Yes , some more documentation on this would be helpful.
Thanks

**Comment by renaudpawlak** [comment]
I have updated the error message to give an hint for using modifiers such as 'abstract' and 'native'. Thanks for the feedback.
