### ISSUE TITLE
When generating sourcemaps, move the "../../src/" prefix to the sourceRoot property of the generated sourcemap

### ISSUE THREAD

**Issue by ivmarkov** [cincheo/jsweet#85]
Currently, each and every source name in the generated source map contains a "../../src/" prefix. This however, breaks the heuristics used by SDBG to locate & pull the correct source file from within the Eclipse workspace itself. As a result, a readonly copy of the Java sourcefile is used during debugging (the file is retrieved form the Chrome browser itself, using the WIP debugging connection).

As a result, the debugging experience in Eclipse is sub-optimal, because during debugging, the e.g. "HelloWorld.java" file is opened for a second time, as a readonly copy.

Solution: promote the "../..src/" prefix to the "sourceRoot" property of the sourcemap spec. This will also save some space in the sourcemap. Don't forget the trailing slash when promoting though.

**Comment by ivmarkov** [comment]
Btw if you would like to try out the Eclipse debugging experience with jsweet, use the latest SDBG beta from here: http://sdbg.github.io/p2beta/

**Comment by renaudpawlak** [comment]
Wow. Cool. This is a really good thing for JSweet to have SDBG working with it. I have just tried it and I like it a lot :D

Also, I saw the problem you are talking about (the read-only duplicated source file). I did not know about the "sourceRoot" property. I will investigate and will adjust.

Thanks!

**Comment by renaudpawlak** [comment]
I did as advised and it works now :)
I will update the documentation to link to SDBG.

**Comment by renaudpawlak** [comment]
So, I still need to update the Eclipse plugin to have it available to everyone, but your can test it with the latest JSweet snapshot using ``mvn generate-sources``.

I have added some links to SDBG on the main web site (home page, FAQ, and Eclipse plugin pages). When I will find the time (if only I had more!), I will try to post a small tutorial on how to debug JSweet programs within Eclipse with SDBG.

**Comment by ivmarkov** [comment]
OK thanks for referencing SDBG. You might want to try out the JavaScript sourcemap support in JIDEA as well - I know they also support javascript + sourcemaps debugging.

**Comment by ivmarkov** [comment]
BTW the latest SDBG beta got a few more fixes and is now promoted to the main channel: http://sdbg.github.io/p2/

**Comment by renaudpawlak** [comment]
Note: source map support is planned to be using Sorcery soon :)
