### ISSUE TITLE
When targeting ES6 trough the maven plugin

### ISSUE THREAD

**Issue by EPOTH** [cincheo/jsweet#98]
[INFO] JSweet transpiler version 1.1.0-SNAPSHOT (build date: 2016-03-15 18:23:17)
ERROR: duplicate identifier 'Promise' at ../../.jsweet/candies/typings/src/typings/es6-promise/es6-promise.d.ts(12)
ERROR: duplicate identifier 'Promise' at ../../.jsweet/candies/typings/src/typings/es6-promise/es6-promise.d.ts(43)
ERROR: duplicate identifier 'Promise' at ../../../../../.jsweet-node_modules/lib/node_modules/typescript/lib/lib.es6.d.ts(1257)
ERROR: duplicate identifier 'Promise' at ../../../../../.jsweet-node_modules/lib/node_modules/typescript/lib/lib.es6.d.ts(1347)

**Comment by renaudpawlak** [comment]
1. make sure that you remove the es6-promise candy from your pom.xml.
2. make sure that you clean JSweet cache by removing the .jsweet directory in your project

It should work then.

**Comment by EPOTH** [comment]
It works now , thanks

**Comment by pbtura** [comment]
I have this issue as well and the solution above does not fix it. I tracked the dependency to the angular2 candy but no matter what I try it still pulls the es6 candy in every time I run the maven command. 

I added on exclusion to my pom.xml

```
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>angular2</artifactId>
			<version>2.0.0-20170726</version>
			<exclusions>
				<exclusion>
					<groupId>org.jsweet.candies</groupId>
					<artifactId>es6-promise</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

I deleted the jsweet directory from the maven cache (.m2). I deleted the .jsweet directory from my project. I then ran the mvn generate-sources command and it re-downloaded the es6 promise candy and threw the same error. What do I have to do to get rid of this thing?

**Comment by lgrignon** [comment]
You must have another transitive reference to the es6 promise candy. Please check the pom's dependency tree in Eclipse and look for es6 promise jar to add the proper exclusions.
Please tell me if something is unclear

**Comment by pbtura** [comment]
The dependency for 'es6-promise' comes from 'rxjs' which in turn comes from 'angular2'. I have tried doing the exclusion through eclipse and by directly editing the pom. I tried excluding it at the level of the angular2 dependency and at the rxjs level. Somehow, it is still pulling in the es6-promise dependency.

**Comment by lgrignon** [comment]
It must come from somewhere else if it is downloaded. Wasn't there any other transitive dependency to es6-promise? Maybe in the jsweet core?

**Comment by lgrignon** [comment]
BTW your pom extract is the right way to exclude transitive dependency

**Comment by pbtura** [comment]
Sorry for the long delay, I got diverted to work on another project for a few weeks. I finally got a chance to try your suggestion. If I completely remove the angular2 and rxjs dependencies from the pom, the es6promise does not get pulled in. That indicates to me that the dependency is coming only from those two candies. 
My next step was to try flattening out the heirarchy. I excluded rxjs from the angular dependency and added an explicit dependency. I excluded es6promise from both dependencies. After running the maven command, es6promise got pulled in again.

The next step was to try removing the angular dependency from the pom and just have rxjs. Same results. So I added the angular dependency back and tried excluding rxjs from there. Not only did es6promise still get pulled, so did rxjs.

For some reason, the maven command seems to be ignoring my exclude statements and pulling in everything. Any thoughts?

**Comment by lgrignon** [comment]
Sorry, no, usually maven exclusions just work.

We should consider pushing an angular candy depending on es5 and not es6

**Comment by pbtura** [comment]
I found a workaround, but I have no idea WHY it works. I took the dependency block for the angular2 candy out of the pom dependencies. I then added a dependencies block nested inside the <plugin> tag for jsweet-maven-plugin and pasted the candy dependency there. I cleared out the files in maven and re-ran the generate-sources. This time everything worked. angular2 and rxjs get pulled in and es6promise is excluded.

**Working:**

```
	<dependencies>
		<dependency>
			<groupId>commons-validator</groupId>
			<artifactId>commons-validator</artifactId>
			<version>1.4.0</version>
		</dependency>
		<dependency>
			<groupId>commons-configuration</groupId>
			<artifactId>commons-configuration</artifactId>
			<version>1.10</version>
			<exclusions>
				<exclusion>
					<groupId>commons-lang</groupId>
					<artifactId>commons-lang</artifactId>	
				</exclusion>
			</exclusions>
		</dependency>		
	</dependencies>
	<build>
		<plugins>
                <plugin>
                <groupId>org.jsweet</groupId>
                <artifactId>jsweet-maven-plugin</artifactId>
                <version>2.0.0</version>
                <configuration>
                    <targetVersion>ES5</targetVersion>
                 </configuration>
                <executions>
                    <execution>
                        <id>generate-js</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>jsweet</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>angular2</artifactId>
			<version>2.0.0-20170726</version>
			<exclusions>
				<exclusion>
					<groupId>org.jsweet.candies</groupId>
					<artifactId>es6-promise</artifactId>
				</exclusion>
			</exclusions>
		</dependency> 					
			
				</dependencies>
			</plugin>			
		</plugins>							
</build>
```


**Failing:**

```
<dependencies>
		<dependency>
			<groupId>commons-validator</groupId>
			<artifactId>commons-validator</artifactId>
			<version>1.4.0</version>
		</dependency>
		<dependency>
			<groupId>commons-configuration</groupId>
			<artifactId>commons-configuration</artifactId>
			<version>1.10</version>
			<exclusions>
				<exclusion>
					<groupId>commons-lang</groupId>
					<artifactId>commons-lang</artifactId>	
				</exclusion>
			</exclusions>
		</dependency>	
		<dependency>
			<groupId>org.jsweet.candies</groupId>
			<artifactId>angular2</artifactId>
			<version>2.0.0-20170726</version>
			<exclusions>
				<exclusion>
					<groupId>org.jsweet.candies</groupId>
					<artifactId>es6-promise</artifactId>
				</exclusion>
			</exclusions>
		</dependency>	
	</dependencies>
	<build>
		<plugins>
                <plugin>
                <groupId>org.jsweet</groupId>
                <artifactId>jsweet-maven-plugin</artifactId>
                <version>2.0.0</version>
                <configuration>
                    <targetVersion>ES5</targetVersion>
                 </configuration>
                <executions>
                    <execution>
                        <id>generate-js</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>jsweet</goal>
                        </goals>
                    </execution>
                </executions>

			</plugin>			
		</plugins>							
</build>
```

**Comment by lgrignon** [comment]
Ok, quite surprising indeed. Please tell us if anything goes wrong again.
