### ISSUE TITLE
support for more than one catch clause

### ISSUE THREAD

**Issue by metrospiegel** [cincheo/jsweet#99]
Hello,

is it possible, to provide support for more than one catch clause and make the error an warning?

Like: 
        }
        catch (AbortExecutionException exception)
        {
          command.dispose();
        }
        catch (RuntimeException exception)
        {
           ....
        }
To:

```
    }
    catch (e) {
    if (e instanceof AbortExecutionException)
    {
      exception : AbortExecutionException = e;
      command.dispose();
    }
    catch (RuntimeException exception)
    {
       exception : RuntimeException = e;
       ....
    }
```

Best,
  Michael

**Comment by lgrignon** [comment]
```
Did you mean:
}
    catch (e) {
    if (e instanceof AbortExecutionException)
    {
      command.dispose();
    }
    else if (e instanceof RuntimeException)
    {
       ....
    }

```
It seems reasonable indeed.

**Comment by metrospiegel** [comment]
Yes. But trying to preserve the variable name for the thrown object. I wrote Renaud that i would try to provide a PR for you on this.

**Comment by renaudpawlak** [comment]
I confirm that it is probably a good idea to use local variables in the catches (it is simpler). Here are a couple hints.

For both methods, you need to generate a fresh (unique name) variable (the one you call ``e`` in your example). For simplicity (at least for a first version), you can use the ``Util.getId()`` method that generates a unique id. 

Please use the ``Java2TypeScriptTranslator.printInstanceOf`` method for generating the ``instanceof`` tests.

Thanks!

**Comment by renaudpawlak** [comment]
Hi @metrospiegel!
So, how is this going on?
JSweet implementation has been moving a lot lately to adapt to GWT's runtime, but now it is working and it should be quite stable.

**Comment by renaudpawlak** [comment]
This one should be working now: https://github.com/cincheo/jsweet/blob/master/src/test/java/source/throwable/MultipleTryCatchTest.java
